### ISSUE TITLE
豆瓣电台在某些地区显示版权受限

### ISSUE THREAD

**Issue by zhuzhuor** [Unblocker/Unblock-Youku#122]
有两个人来反馈说豆瓣电台在香港不能用了
不知道还有别的国家或者地区还有同样的问题吗
加拿大我这里还是正常的

![qq20130829215320 1](https://f.cloud.github.com/assets/928905/1057658/b2b65924-1178-11e3-98bd-8776ec4d5aee.jpg)

**Comment by zhuzhuor** [comment]
最近把 youku 和 tudou 的 html 页面都代理了，看起来压力还好
想试试把之前的这些问题再改进改进

@tommyzhaozbh @whuhacker 这网站在香港还是不能访问吗？

**Comment by tommyzhaozbh** [comment]
额，现在还是返回400呢。

**Comment by zhuzhuor** [comment]
douban.fm 应该已经添加到最新的扩展程序里了，有香港的同学能帮忙试试吗

**Comment by tommyzhaozbh** [comment]
这个之前我测试过，他貌似会有些许随机码验证的东西…过不了的话会400，过了之后就没事了

**Comment by zhuzhuor** [comment]
@tommyzhaozbh 就是说还是会随机地遇到 400 错误？你最近有空了再试试，不会是我们的服务器当时没更新吧

**Comment by tommyzhaozbh** [comment]
我刚好不在香港，回头再去测试。当时规则已经更新了，而且插件也能够识别相应地址。

**Comment by zhuzhuor** [comment]
@tommyzhaozbh 好的，不着急。现在服务器端需要我手动 push 一下，可能你当时试的时候我忘记 push 了...

**Comment by zhuzhuor** [comment]
@tommyzhaozbh 我看到 douban.fm/* 下面的东西也都不多，于是都过了代理，这下应该没你之前说的那个问题了。有问题再试试看

**Comment by tommyzhaozbh** [comment]
现在问题已经解决，可以使用了。

**Comment by zhuzhuor** [comment]
@tommyzhaozbh 多谢！
