### ISSUE TITLE
建议：建一个新的repo去存放需要代理的urls

### ISSUE THREAD

**Issue by tywtyw2002** [Unblocker/Unblock-Youku#423]
建议而已，单独的repo方便大家去parse url和检查更新。

比如squid，dns 等规则。

**Comment by zhuzhuor** [comment]
我现在是这么个想法

1. 因为安全和带宽的考虑，最好还是把 url list 直接存在 Chrome extension 里比较好
    1.1. 安全的考虑是指，如果把 url list 存在 online server 上，如果 server 被黑 url list 被篡改，用户的隐私数据经过代理服务器就不好了。PS，虽然 Adblock 之类的扩展程序是在线更新 url list，但是 url list 被篡改而导致安全问题的可能性还是比较小，因为 url list 被窜改了也只是 block 了错误的 url
    1.2. 之前在 #304 提到，PAC 文件下载流量还是挺高的，如果 url list 弄成在线更新的话应该也不会低

2. 如果 url list 是存在 Chrome extension 里，但是在另外一个 repo 里更新
简单的方法就是把 url list 的 repo 当做 Chrome extension 的 repo 的 submodule
但是感觉整个测试和更新的流程都要变得更加复杂
    2.1. url list 更新了，还要更新 Chrome extension repo 的 manifest.json 以及 submodule 的 hash tag
    2.2. 有给 Chrome 扩展程序专用的子 url list，这个 url list 还得和主 url list repo 分开来维护
    2.3. 服务器自动更新的流程需要同时监控两个 repo，服务器更新还要考虑正确的流程什么的

感觉把 url list 拆分出去弄个新的 repo 还需要大动干戈，改写改写扩展程序和服务器的架构什么的，还需要仔细想想

**Comment by zhuzhuor** [comment]
另外想到，为了方便给别的 app 或者 project 分享我们的 url，可以给 heroku 的 app 弄个 url 专门输出 url list 或者 regex list，这样应该更加容易 parse 和检查更新

**Comment by zhuzhuor** [comment]
给 heroku 的 app 新加了个地址
访问 http://pac.uku.im/regex 就可以看到最新的 regex 列表

**Comment by tywtyw2002** [comment]
首先我很同意你的观点，我也不赞成在线更新url列表之类的东西。

但是我感觉你在上面回复的和我的初衷有点不大一样，有可能是我当时没有解释清楚吧。

对于这个问题，我的想法是单独为urls 开一个repo，然后用issue去管理所有的url添加和删除，这样可以方便的去tracking url。

主要是对urls实行version control，分享url到是其次的。

另外你说关于chrome的extension编译，我不是很了解。不知道是自动编译（提交repo给play store），还是需要在本地手动编译再手动上传。

关于extension的编译，我们完全可以把这个url repo理解成unblock-youku repo的一个submodule。对于编译extension来说，我们checkout了主repo也会checkout 这个repo中的submodule。

 对于直接把url放在unblock-youku这个repo里面和单独为url 建立一个repo我认为是没有什么区别的。

url repo来说我们可以给url分类，然后写个make脚本去把这些url转换成js可以识别的格式。最终变成了先编译url repo再去编extension。
