### ISSUE TITLE
给 Unblock Youku 增加捐款的选项

### ISSUE THREAD

**Issue by zhuzhuor** [Unblocker/Unblock-Youku#438]
随着这个项目的受益的人越来越多（Chrome extension 的[周活跃用户已经超过 300 万人](https://chrome.google.com/webstore/detail/unblock-youku/pdnfnkhpgegpcingjbfihlkjeighnddk/)），我们服务器的压力也越来越大。现在 Chrome 扩展程序、DNS 服务器、Firefox 扩展程序所用的代理服务器都是我一个人在付款。最近想多添加几个国内的代理服务器（见 #427 和 #397），但是都有点力不从心。另外还有国外 Heroku, Wufoo, Pingdom, DigitalOcean 等服务，每个月加起来也不少钱

为了能让我们这开源项目更加健康地发展下去，最近觉得还是给我们的项目增加个捐款的选项。大致的想法就简单地弄个 Paypal 的捐款按钮或者链接，放在扩展程序的菜单里，或者在安装的时候弹出个捐款页面

欢迎大家集思广议，说说自己的想法

BTW, 我最近正在主动减轻自己在学校的工作，争取多点时间来修修 bug，改善这个项目的代码
估计还有 2-3 个月我就要去公司开始正式工作了，希望能在那之前让我们这项目走上正轨

**Comment by whuhacker** [comment]
支持

另外可否加上 FB page 的 like 按钮？

**Comment by sequoiar** [comment]
顶
每周300百万（3亿）活跃用户，这个市场很大

**Comment by whuhacker** [comment]
@sequoiar 哈哈，typo

**Comment by zhuzhuor** [comment]
@sequoiar 汗，改成 300 万啦
@whuhacker 好，准备最近有时间一起搞了。最近服务器的  TLS 证书要过期了，还想顺势 update 一下服务器的设置什么的

**Comment by nilveryawesome** [comment]
zan

**Comment by alexking99** [comment]
Firefox 扩展应该没有再维护了吧 好久没更新 反而chrome扩展经常更新

**Comment by zhuzhuor** [comment]
@alexking99 Firefox 的 Unblock-Youku 扩展程序是 @whuhacker 同学做的，见 [whuhacker/Unblock-Youku-Firefox](https://github.com/whuhacker/Unblock-Youku-Firefox)。但是也是基于我们的 [PAC 文件](http://uku.im/proxy) 和代理服务器

我印象中 Firefox 的扩展更新前都都要人工审核，审核的要求比较严(?)，所以影响 Firefox 扩展程序更新的速度和频率

**Comment by alexking99** [comment]
@zhuzhuor Firefox Unblock-Youku 1月更新后再也没更新过 另外你说基于你们的PAC 文件和代理服务器也就说就算不更新Firefox Unblock-Youku 没什么影响   有你们更新PAC 文件和代理服务器 Firefox Unblock-Youku就能正常使用我可不可以这样理解? 望解答
我也希望@whuhacker 持续维护Firefox Unblock-Youku

**Comment by zhuzhuor** [comment]
@alexking99 我不确定 Firefox 的 Unblock-Youku 扩展程序能不能自动更新 PAC 文件，你可以等等 @whuhacker 的解答

**Comment by alexking99** [comment]
@zhuzhuor 感謝回答

**Comment by whuhacker** [comment]
@alexking99 Firefox 不允许动态更新 PAC 文件，现在都是写在代码里的，并非 URL
我会继续更新 Firefox 版本的

**Comment by alexking99** [comment]
@whuhacker 感谢解答 还以为放弃了 现在可以安心用firefox

**Comment by enerai** [comment]
能不能加支付宝的捐款链接？有些时候想要捐款，但是 paypal 这个支付途径有时候捐不成功。或者直接把 donate 按钮加载扩展的设置菜单里面就好

**Comment by enerai** [comment]
哈哈发现一个 typo，“随着这个项目的收益的人越来越多”应该是“随着这个项目的*受益*的人越来越多”

**Comment by zhuzhuor** [comment]
@enerai 多谢！已经改过来了

支付宝我也考虑考虑，多谢建议！

**Comment by chinglim0732** [comment]
其實可以試試用月費或年費制度,數據都說大概有300百萬人在使用,我當有一半人願意付錢,一人付一元一個月都有一百五十萬了~

**Comment by gaosong2101** [comment]
建议采用自愿捐款的形式，然后款项透明（收入支出），这样的话应该很多人都会愿意捐款的，有1/4的人捐1块钱总共加起来也是很多了。

**Comment by enerai** [comment]
楼上说1/2和1/4的…你们是没募捐过么…能有1/20就很好了…=_=

**Comment by gaosong2101** [comment]
嗯。。。没有╮(╯▽╰)╭
不过1/20也是不错的数值

**Comment by enerai** [comment]
1/20是个很好很好的情况了，真实的话…

**Comment by gaosong2101** [comment]
.....1/1000的收入也很可观了

**Comment by chinglim0732** [comment]
募捐當然是不可能達到我所說的成果,只有強制收費才可行,一來收費後會大幅減低伺服器的負擔,二來如果收一個真的非常相宜的價格就能保證品質跟收支了,所以我覺得募捐是不設實際- -""

**Comment by zhuzhuor** [comment]
我觉得我们适当收点捐款用来 cover 服务器的费用就行了，收得多了可能反而招来不必要的麻烦
如果有 1/1000 的用户每人捐 $1 的话，估计能 cover 半年多的服务器费用吧。估计能说服 1/100 的用户捐款就很不错了，我们可以多弄几台服务器运行上几年

问题是，现在用户数量基本上饱和了，新用户不怎么增加了。捐款的话，最好得弄成细水长流形的，免得一开始很多之后慢慢就没有了
可以开始随机只给一部分用户展示，测试下效果，然后再照情况调控下比例

**Comment by whuhacker** [comment]
@zhuzhuor 用户增长有周期的，等今年八九月新一波留学生吧

**Comment by enerai** [comment]
现在有捐款用的账号吗？

**Comment by gaosong2101** [comment]
像维基百科那样定期号召捐款怎么样

**Comment by zhuzhuor** [comment]
@whuhacker soga，这回可以仔细观察观察。那最好就在这个时间点把捐款的功能搞定吧哈哈
@enerai 现在还没有，不想用我私人的帐号来弄，但是最近又有点杂事缠身还没来得及弄新的账户
@gaosong2101 这是个好办法，也可以和我上面说的随机提示捐款的功能结合起来，弄个细水长流

**Comment by chinglim0732** [comment]
老實說我本人因你們的無私服務受惠多年了,使我免得被我老婆罵的煩惱,所以不管你們作什麼決定,我都一定會支持^^

**Comment by xkk** [comment]
我经常上的网站上是这样搞的 每个月开始的时候会提出本月需要的费用然后 大家捐款也可以看到目前的捐款进度
![cut](https://cloud.githubusercontent.com/assets/6011197/8894301/8d32919c-33e3-11e5-8372-5fb9cf322772.png)
一直受益也希望能反馈一点给这个项目 祝愿这个项目可以一直活跃

**Comment by r-learner** [comment]
支持自愿捐款！

**Comment by Chris-17** [comment]
多年用户了 望尽绵薄之力BTW:: xkk的建议很靠谱  支持

**Comment by au0750** [comment]
我可以捐款啊. 但是, 你们有概率会被国内视频网站(尤其是那些有版权的)和国外有版权的网站起诉. 
建议预先做做法律方面的准备吧.

**Comment by hli8** [comment]
我也觉得可行，另外很多国外的没有支付宝啊，paypal更方便吧。$1的话我完全没有意见的。
