### ISSUE TITLE
iPad BiliBili 正版依然看不了

### ISSUE THREAD

**Issue by TungNg** [Unblocker/Unblock-Youku#439]
在iPad BiliBili App 正版的番劇依然是看不了
在電腦上一切正常
能幫忙解決下就好了

#426 #427 
![img_0007](https://cloud.githubusercontent.com/assets/9154576/7964185/1301fb38-0a49-11e5-9c20-fdea52614e2e.PNG)

**Comment by CaptainCan** [comment]
我也有这个问题

**Comment by jackyol** [comment]
把 DNS 改一下就好了

**Comment by CaptainCan** [comment]
怎么改？

**Comment by jackyol** [comment]
把unlock youku的DNS加到ipad上
CaptainCan <notifications@github.com>于2015年6月27日 周六13:36写道：

**Comment by CaptainCan** [comment]
这个？
DNS IPv4地址：192.241.222.103
DNS IPv6地址：2001:470:832e:1024:6969:5269::1

**Comment by jackyol** [comment]
YES

CaptainCan <notifications@github.com>于2015年6月27日周六 下午2:04写道：

**Comment by Alais** [comment]
bilibili貌似没法使用pac http://ipservice.163.com/isFromMainland 检测为true，依然没法看
貌似只能用dns，dns最近不是很稳定，改用pc插件流畅观看。
