### ISSUE TITLE
Youku 不能读取，停留在转菊花画面

### ISSUE THREAD

**Issue by gorsonh** [Unblocker/Unblock-Youku#445]
从6/25号开始，但凡需要海外权限的视频，都会停留在转菊花页面，（意思是，菊花没转，视频也不出来，甚至广告都没有）其他国内电视剧正常，就只是需要海外权限的会这样。Flash 18.0.0.194，没有去广告插件，只有unblock youku，是最近大家都有的问题吗？还是我个人？地址在美国东岸，纽约。 谢谢各位！

**Comment by zhuzhuor** [comment]
的确发现有一些视频是这样，但是用不用扩展程序都会这样，猜测 youku 的最近的 flash 文件有问题
见 https://github.com/zhuzhuor/Unblock-Youku/issues/441#issuecomment-115802833

**Comment by gorsonh** [comment]
对，我用普通ie 也是这样！就是读不了，目前有什么解决方法吗？chrome好像不能降级flash的吧？谢谢您的回复

Bo Zhu <notifications@github.com>于2015年6月28日星期日写道：

**Comment by zhuzhuor** [comment]
那估计没办法，只能等着 youku 更新了

**Comment by gorsonh** [comment]
了解，谢谢您了！

Bo Zhu <notifications@github.com>于2015年6月28日星期日写道：

**Comment by batiatus** [comment]
windows 8.1 
用 pac 代理， youku app 也用不了 
麻烦 看看

**Comment by zhuzhuor** [comment]
这个 issue 先 close 了，如果还有问题再来 reopen 吧
