### ISSUE TITLE
Drony好像失效了……

### ISSUE THREAD

**Issue by tommyzhaozbh** [Unblocker/Unblock-Youku#446]
其实我本人倾向用DNS代理的,但是如果是安卓机子要换DNS必须要改静态IP,在公共网络却必须得用DHCP，这只好用Drony。但我发现这玩意会令所有视频没法播放,我的设置是没问题的，网页也能正常打开，但就是不能看视频(换言之所有要经过代理的链接全部没法连通)，怎么回事呢?

**Comment by zhuzhuor** [comment]
@mozbugbox

**Comment by yoonhakcher** [comment]
同有这个问题

**Comment by yanggis** [comment]
好像有些视频可以，有些不行。Drony软件本身也有问题，非常不稳定，如果你发现是所有视频都连接不了，可以把手机重启一下，重新运行Drony试试。其实Proxydroid最稳定，但是不支持pac file，没法用。所以现在Android端没有太好的解决办法。
