### ISSUE TITLE
一些建议（自己搭建代理服务器）

### ISSUE THREAD

**Issue by tommyzhaozbh** [Unblocker/Unblock-Youku#453]
鉴于目前服务器被定时Dos攻击，使得unblock youku几乎完全瘫痪。而DNS到现在都没恢复过。其实这个情况我也有担心过，就是服务器被蓄意攻击。看来现在唯一的办法就是我们自己搭建代理服务器或者DNS去解决这个问题。但是我们都不懂怎么搭建和使用(尤其是DNS)，所以我们亟需一个教程去帮忙，至于列表更新，我觉得可以用在线更新或者手动更新都行。

**Comment by zhuzhuor** [comment]
DNS 我也没弄过，只能让 @karlcheong 或者 @whuhacker 来搞了教程了
普通模式的代理服务器，我回头写个美团云的教程吧

**Comment by alexking99** [comment]
同意 我也想要教程

**Comment by tommyzhaozbh** [comment]
@zhuzhuor 尽快吧，教程这东西确实非常需要，另外普通模式要添加自定义服务器了要不然我们弄了也没用。现在所有服务器基本上每天都有12个小时左右是无法使用的，看来这家伙是故意要弄瘫服务器而不是单纯的恶作剧。现在连镜像服务器都被炸，真的很头痛。如果有自己的服务器，一方面可以减轻主服务器的负担，而更重要的是这些服务器都是自用的，地址一般不会外泄，被炸的几率也低很多。都不知道这家伙为啥这么死缠烂打……

**Comment by zhuzhuor** [comment]
我这两天在搬家有点忙，下周看看时间写写教程吧

代理服务器只是一个 squid，配置文件我公开在这里了 http://git.io/vOLcM
扩展程序的话可以临时先改改 source code 用用 http://git.io/vOLcm

的确是用 VPS，但是价格不是非常高，很少人数的人用的话用最低配置的机器就足够了
例如美团云的 1 核 1GB 内存 1Mb 带宽 0GB 数据盘就够用了，每月 65 RMB

> ![screen shot 2015-07-31 at 11 34 54 am](https://cloud.githubusercontent.com/assets/928905/9010990/6420c934-3778-11e5-8c49-ae8390426759.png)

**Comment by tommyzhaozbh** [comment]
@zhuzhuor 另外有一个方法不知道可行不，就是把服务器接入360网站卫士。这样的话网站要备案，但毕竟360的网络资源远远比我们自己的强大得多，防Dos的能力也好得多(毕竟人家有大量cdn，你炸了一个炸不了第二个)如果可行不妨考虑一下

**Comment by zhuzhuor** [comment]
这些CDN一般不能给代理服务器用，我之前试过cloudflare和cloudfront都不行
另外想用国内的这些CDN还得先备案

**Comment by tommyzhaozbh** [comment]
不知道这样行不行:直接在vps上面弄个论坛什么的，反正他们都是检查主域名而已，不知道这样可不可以骗过检查。我刚试过360的，输入proxy.mainland.io的话，它只检查mainland.io而无视了proxy的开头。

**Comment by xin-zhang** [comment]
@zhuzhuor 
第一次发言，よろしくお願いしますmm

> 代理服务器只是一个 squid，配置文件我公开在这里了 http://git.io/vOLcM
> 扩展程序的话可以临时先改改 source code 用用 http://git.io/vOLcm
> squid.conf 文件里面的 /opt/crx_url_list.txt 可以直接用这里的内容 http://pac.uku.im/regex
> 的确是用 VPS，但是价格不是非常高，很少人数的人用的话用最低配置的机器就足够了
> 例如美团云的 1 核 1GB 内存 1Mb 带宽 0GB 数据盘就够用了，每月 65 RMB

按照你给的这些信息，在美团云上搭了一个squid的proxy，至少chrome的插件可以用了。赞 :+1: 

不过搭squid3的时候，遇到了几点琐碎问题，我也在这里记录一下，有其他自己在照着搭squid的人可以做个参考
（我是第一次用squid，不是很确定是不是这样，都是边google边尝试出来的结果。看起来，美团云ubuntu14.04现在提供的squid版本（squid3_3.3.8-1ubuntu6.2_amd64.deb）可能比较新，http://git.io/vOLcM 这个里面的配置文件必须要修改几行才能使用。）
 - 第一行会报fatal error，必须注释掉
 - 第二、三行会报warning，注释掉也行，放在那儿也行
 - 原来的指定port的格式，`http_port 8888` ，似乎只会监听ipv6了，要强制监听ipv4的话，要写成 `http_port 0.0.0.0:8888`
 - 如果不想自己配置iptables过滤端口，想就用美团云默认的防火墙端口过滤的话，可以直接用默认开着的3389端口。

**Comment by zhuzhuor** [comment]
@xin-zhang 多谢反馈！！估计的确是版本的原因，我应该当时用的是 ubuntu 12.04

@tommyzhaozbh 你是说先给主域名备案吗，那个估计也要很久很麻烦，而且我也不在国内
我之前试过 cloudflare 和 cloudfront 都不能用在代理服务器前面，所以我怀疑 360 的应该也不行
这些 CDN 本质就是类似用 nginx 做 reverse proxy，发给代理服务器的 URL 经过 reverse proxy 的时候被 分解重构了，发给 origin 代理服务器的的 URL 可能就不完整了

**Comment by benhong** [comment]
原本也想说利用美团云架设一个proxy，后来爬了一些文章才知道，在内地的网域好像要先备案
，虽然我并不知道proxy是否要备案，后来我的方案是，直接找一个付费的vpn，vpn server 在内地
利用route table 的方式，让某些ip 只走vpn 其他ip 还是维持原来的线路，来达成在海外也可以看内地的
视频,觉得这种方法还满适合个人使用的，费用也很低

**Comment by zhuzhuor** [comment]
@benhong 你说的办法应该也行，但是要解析 IP 比较麻烦吧?
美团云用 80 以外的端口不用备案，阿里云用 HTTPS 也没事

**Comment by xkk** [comment]
备案的话如果只是简单的 可以X宝搜一下 好像可以两种方式 用你的资料（自己提供）申请 和随便找一个人的资料（对方提供）申请

**Comment by yanggis** [comment]
@xin-zhang,我也有自己的服务器，也是用Squid3代理，但是我不知道你有没有发现一个问题，就是在Android客户端上，直接在Settings里面设置上我在中国的服务器，然后打开优酷看视频的话，播放的视频数据也是需要走我在中国的服务器转发给我，这样就非常慢，看视频非常卡。但是，我在Ipad上WIFI设置里设置上全局代理，用优酷客户端访问，视频数据就不走我在中国的服务器，所以播放就非常流畅。Android上本来想有Drony配合Pac文件使用，但是Drony还是有点不太稳定，运行几个小时就会报莫名其妙的错误，必须手动重启，这在家里电视盒子上就很不方便。不知道大家都是怎么解决的？

**Comment by xin-zhang** [comment]
@yanggis 你好~
不好意思，我一直都只是在电脑上用chrome的插件，几乎不用其他的方式。Squid上周末刚搭上，Drony也还没有搭过。
这周末有空的话试试看。也许那时候可以再讨论讨论~ :)

**Comment by benhong** [comment]
@xin-zhang 
在自己的服務器架VPN server 然後在自己的
對外路由器上連上自己服務器的server 
之後修改route table 將特定IP走VPN 期他IP 維持不變
有點類試這裡的方法 https://code.google.com/p/autoddvpn/
只是設定的IP 不一樣

另一種方法，在自己的伺服器架DNS  ,
然後在對外的路由器上將特定的網址導到你的 DNS  去

已上2種方法都可以達到
只要透過 對外那台路由器 的手機 電腦 小盒子
通通都不用設定，就可以翻牆到內地快快樂樂去看影片了

差異在一個看IP 一個試看網址

**Comment by benhong** [comment]
@xin-zhang 你好
請問一下 若我自己代理伺服器，可以用阿里雲的嗎(因為他比較便宜)
另外~是不是我還要另外申請一個網址呢，
在阿里雲使用代理伺服器，是否需要备案呢

**Comment by zhuzhuor** [comment]
@yanggis 如果 squid 服务器已经建好了，你只用 PAC 的话，只用改一下 PAC 文件里的代理服务器地址就行了，不用 drony。下载 http://pac.uku.im/pac.pac 文件，然后把里面的 `proxy.uku.im:8888` 改成你自己的服务器地址，然后再把 pac.pac 文件上传到哪个 webserver 就行了

@benhong 阿里云是便宜点，但是需要备案才能用，见 https://github.com/zhuzhuor/Unblock-Youku/issues/320

**Comment by zhuzhuor** [comment]
@tommyzhaozbh 我今天又试了一下 cloudflare，如果给代理服务器用的话，会有问题没法代理
我给 cloudflare 也发了个 feature request

>  ![screen shot 2015-08-04 at 12 16 26 am](https://cloud.githubusercontent.com/assets/928905/9061520/4fe0953e-3a8a-11e5-9e30-030cd79c68a4.png)

**Comment by zhuzhuor** [comment]
想用美团云架设自己服务器的话，欢迎用我们的推荐链接 https://mos.meituan.com/r/6a643d0d9a
用这连接注册的话，“被引荐者在MOS的第一笔充值或者第一笔消费金额的20%作为奖励”

今天内我就写出来一个在美团云上设置代理服务器的完整教程

**Comment by tywtyw2002** [comment]
@xin-zhang squid版本问题 我推荐3.1X，或者3.2X 这个是目前比较好的squid版本。

2.7是最经典的，但是太老了，如果你想二次开发用2.7玩吧。3.x都是C++写的了。

**Comment by zhuzhuor** [comment]
在美团云上架设私人用的 Squid 代理服务器的教程已经写好了，见 http://git.io/vOa4i
如有问题欢迎再来反馈，另外我尽快把 Chrome 扩展程序里配置部分也写好吧

鼓励大家分享自己的代理服务器给身边的朋友，最低配置的服务器也应该能支持很多人

**Comment by yanggis** [comment]
@zhuzhuor 谢谢回复，PAC文件我在电脑上和IPad上已经弄好了。但是Android系统本身不支持PAC文件，不用Drony的话，怎么解决啊？设个全局代理，所有http的数据都走代理也不太方便呀。

**Comment by zhuzhuor** [comment]
@yanggis 抱歉，我理解成 @mozbugbox 写得 droxy 了 https://github.com/zhuzhuor/Unblock-Youku/tree/84ebf2f21f05a364697f6e594bfd7c943af242b2/dns-reverse-proxy

**Comment by zrlu** [comment]
@zhuzhuor 你好，我试了在Firefox下不用Unblock-Youku插件载入 <a href="http://pac.uku.im/pac.pac">http://pac.uku.im/pac.pac</a> 。我在<code>pac.pac</code>添加了<code>"www.bilibili.com": [/^\/video\/av/i],</code> 并且把服务器改成 <code>"PROXY 117.177.243.71:8081; DIRECT"</code> (网上随便找到服务器) 发现可以正常观看正版新番。然后试了在Firefox下不用PAC直接连接这个代理服务器也能正常观看。但是在iOS下载入修改后的PAC或者用全局代理，还是无法用客户端看新番 （正在分析视频地址...失败)。

之后我试了试用Fiddler监测Bilibili iOS客户端的HTTP活动，发现并不能找到类似网页版那种存放视频地址的XML或者其他数据。我试了用电脑挂中国VPN，然后用电脑创建Wifi热点。iOS端可以正常获取视频地址，新番也能播放，然而还是找不到任何关于视频地址的数据。难道在移动端上视频地址数据不是由HTTP传输的？会不会处于某种原因，HTTP代理对移动端无效？

**Comment by whuhacker** [comment]
@zrlu 
移动客户端与 API 服务器的通信，严谨一点都会使用 HTTPS 加密，所以你用 Fiddler 之类的工具看不到。
至于电脑开 VPN，再共享 WiFi 给移动客户端，也是无效的。共享的 WiFi 在 OSI 七层网络模型中属于数据链路层，而 VPN 更在 TCP/IP 网络层之上。所以移动设备经过 WiFi，并没有走电脑上的 VPN。这种方式不可行。

**Comment by zrlu** [comment]
@whuhacker 谢谢你的回复，受教了。那是不是除了VPN就没有其他方法了？

**Comment by benhong** [comment]
@zhuzhuor 剛剛去註冊美团云 就卡關了，居難要內地的手機才可以註冊
有甚麼辦法可以克服，原來要在內地搞一台代理伺服器 是那麼麻煩

**Comment by whuhacker** [comment]
@zrlu 
用 VPN 流量会全局走国内，然后访问 Facebook 之类的在国内估计会挂……想做智能分流得配路由表，挺麻烦的
要么参考 @zhuzhuor 刚发的教程自己搭建国内代理，要么等 Unblock Youku 恢复正常吧

**Comment by yanggis** [comment]
@zhuzhuor 我想问一下，
acl crx_url url_regex -i "/opt/crx_url_list.txt" 这个是通过正则表达来显示只允许这个list里的网站可以用这个代理，其他的网站访问会被拒绝，对吗？

**Comment by zhuzhuor** [comment]
@benhong 的确是这样，我写教程的时候都忘记了，你看看能不能找个朋友帮你用手机验证下
我是弄了个上海的手机号一直在国际漫游接收各种短信验证码，每月 7 人民币，收短信不花钱

@yanggis 对，只有在这个 list 里的网站才允许通过代理，所以要配合 Chrome/Firefox 扩展程序或者 PAC 文件一起使用

**Comment by tywtyw2002** [comment]
@whuhacker 抓api用mitmproxy。无视https。

**Comment by csyangning** [comment]
@zhuzhuor 不好意思 请问根据教程架好了之后如何用呢 PC端就直接用proxy ios用修改后的pac?

**Comment by tommyzhaozbh** [comment]
@zhuzhuor 那看来是CDN不兼容了，另外我想问问架设好服务器之后怎么用pac呢？

**Comment by benhong** [comment]
@tommyzhaozbh  
1.下載 http://yo.uku.im/proxy.pac 
2.編輯他 ，將 proxy.uku.im:443 改成你的代理伺服器
3.將修改好的檔案上傳到網路空間
4.在IOS端原本要填 http://yo.uku.im/proxy.pac 改成你的網路空間的位置極可

**Comment by tommyzhaozbh** [comment]
@benhong 感谢

**Comment by benhong** [comment]
@zhuzhuor 我终于搞定自己的代理伺服器了，但是我的代理伺服起的ip被 腾讯检测为 日本ip 
所以我的代理伺服器 一样不能看 腾讯....

今天我有研究到一个可以在ios 上使用行动上网，还可以看内地的影片
方法很简单在server上建立openvpn ，然后再openvpn server config 上设定
当user连线时 将特定的ip 走vpn 其馀不走vpn ，实现了智能vpn

**Comment by kiyor** [comment]
@benhong 用openvpn在大量IP段(上百)的时候会有问题, 我的解决方式是一台linux router上连接openvpn服务器, 用cronjob跑[脚本](https://gist.github.com/kiyor/e0115fa4ccf70abd9c6c), 然后用`ip route add`去做添加指定路由. 脚本最好使用自己的dns, 这样还能加一些规则.
另外关于http://yo.uku.im/proxy.pac 我的做法是用nginx做反向代理, lua做regex replace.
配置文件像[这样](https://gist.github.com/kiyor/5bd62c704ead46e2bbdf)

**Comment by benhong** [comment]
@kiyor  解決 router IP 上百個的辦法
在CLINET 端加上 max-routes 300
預設值是100 所已超過100 會不能連
以目前的@zhuzhuor  所提供的PAC 
去做route table 大約只要116個吧

**Comment by kiyor** [comment]
@benhong 又学到了,可惜我的vpn client用的较混, 有些不支持.:worried:

**Comment by zhuzhuor** [comment]
我发现 aliyun 可以用国外的手机号注册，回头可以试试用国外手机注册的整个流程
有人感兴趣也可以试试看

**Comment by mc16888** [comment]
@zhuzhuor aliyun seems need 实名认证 before you can purchase any VPS.

**Comment by kclonline** [comment]
@zhuzhuor @whuhacker
请问DNS优酷修复了吗？
显示：http://i.imgur.com/mzfP9ti.png
视频网址：
http://v.youku.com/v_show/id_XNjI0MTkxNjAw.html
http://v.youku.com/v_show/id_XMTMxMjM1NTY1Mg==.html?from=y1.3-tv-grid-1007-9910.86804.1-1
希望DNS能修复，电脑容易解决，但手机盒子比较需要DNS。
期待DNS架设教学，也期待aliyun测试结果，不过楼上反应要实名认证，感觉诸多限制。
不知道哪一家是比较推荐架设DNS的呢？谢谢

**Comment by zhuzhuor** [comment]
新给自建代理服务器的教程添加了 自动更新 Squid 配置的 部分，见  http://git.io/vOa4i 步骤四

**Comment by zhuzhuor** [comment]
美团云现在的新区都改成 主机+浮动 IP 这样的设置模式了吗？刚才才注意到
这样貌似是个技术上的进步+大宽带服务的降价，但是最便宜的 1Mb 服务器价格变贵了

一个主机最便宜 RMB 40/month，一个 IP 0.02/hour，然后 1Mb 带宽 0.04/hour
于是一个月要 40 + (0.02 + 0.04) * 24 * 30 = 83

**Comment by benhong** [comment]
@zhuzhuor 你算錯了1個ip 0.02/hour 1mb 0.02/hour

**Comment by zhuzhuor** [comment]
@benhong 我这里看到的确是 1Mb 0.04/hour
可能你是不同区的原因？或者是 0.04 里面包含了 IP 的价格吗？

> ![screen shot 2015-08-30 at 10 47 35 am](https://cloud.githubusercontent.com/assets/928905/9573168/d3dfb49e-4f6d-11e5-8fe4-0038e12e16c7.png)

**Comment by benhong** [comment]
是的 0.04 已经包含ip的价格了，因为我目前正在使用中

**Comment by Migflyway** [comment]
老大们很感谢共享和付出，已经通过美团云搭建成功。 但是发现，土豆，爱奇艺，芒果，无法unlock。youku工作很正常。有什么办法，让tvbox也可以使用代理么？

**Comment by zhuzhuor** [comment]
@Migflyway 你说的“土豆，爱奇艺，芒果”是指 tvbox 上的吗
另外你用的 tvbox 是哪个，android 的吗

**Comment by Migflyway** [comment]
@zhuzhuor  土豆，爱奇艺，芒果 是指网页。我在mac上看的视频。 tvbox 类似于小米这样的android设备。

**Comment by zhuzhuor** [comment]
@Migflyway 
Youku 工作正常就说明代理服务器已经基本上设置成功了，你看看你的 crx_url_list.txt 列表是完整的吗
美团的有些 IP 可能会被误判成日本的，之前有人找客服重新要了个 IP 给解决了（我找不到之前那个 issue 了），你看看你是不是类似的问题

**Comment by Migflyway** [comment]
@zhuzhuor 好的，我看看。谢谢～

**Comment by Migflyway** [comment]
@zhuzhuor 已经让客服更换IP，但是还是同样的问题。查看了crx_url_list.txt 列表完整，土豆等还是提示海外。

**Comment by benhong** [comment]
@Migflyway  建議你這樣測試，先讓土豆整個網域走你的代理伺服器
要是一樣出現海外，那肯定是IP 的問題，換IP是沒用的
因為IP 再怎樣換都是在同一個B class 下
唯一的解法請客服寫信去靠杯土豆根新IP資料庫，
我之前也是這樣克服不能看QQ視平的問題

**Comment by Migflyway** [comment]
@benhong 好的，我试试。谢谢

**Comment by yijia-zhan** [comment]
我按照美团云搭建unblock-youk代理的教程搭了一个服务器，第一天工作完全正常。可现在突然就不工作了。

具体状况是，服务器8888端口检测还是打开的，squid也正常运行，可是设置代理后尝试链接就一直是timeout。请问有没有什么办法可以debug squid是否正常工作？谢谢！

下边使一些服务器信息：

firewall-cmd --zone=public --list-all
```
public (default, active)
  interfaces: eth0 eth1
  sources:
  services: dhcpv6-client http https ssh
  ports: 32766/tcp 8888/tcp
  masquerade: no
  forward-ports:
  icmp-blocks:
  rich rules:
```
netstat -tulpn | grep 8888
```
tcp6       0      0 :::8888                 :::*                    LISTEN      2348/(squid-1)
```



systemctl status squid
```
squid.service - Squid caching proxy
   Loaded: loaded (/usr/lib/systemd/system/squid.service; enabled)
   Active: active (running) since Thu 2015-11-26 23:33:20 EST; 4min 20s ago
  Process: 2324 ExecStop=/usr/sbin/squid -k shutdown -f $SQUID_CONF (code=exited, status=0/SUCCESS)
  Process: 2343 ExecStart=/usr/sbin/squid $SQUID_OPTS -f $SQUID_CONF (code=exited, status=0/SUCCESS)
  Process: 2338 ExecStartPre=/usr/libexec/squid/cache_swap.sh (code=exited, status=0/SUCCESS)
 Main PID: 2346 (squid)
   CGroup: /system.slice/squid.service
           ├─2346 /usr/sbin/squid -f /etc/squid/squid.conf
           ├─2348 (squid-1) -f /etc/squid/squid.conf
           ├─2349 (logfile-daemon) /var/log/squid/access.log
           └─2350 (unlinkd)

Nov 26 23:33:20 unblock-youku-yj systemd[1]: Starting Squid caching proxy...
Nov 26 23:33:20 unblock-youku-yj systemd[1]: Started Squid caching proxy.
Nov 26 23:33:20 unblock-youku-yj squid[2346]: Squid Parent: will start 1 kids
Nov 26 23:33:20 unblock-youku-yj squid[2346]: Squid Parent: (squid-1) process 2348 ...ed
Hint: Some lines were ellipsized, use -l to show in full.
```

squid.conf
```
acl crx_url url_regex -i "/opt/crx_url_list.txt"
acl localnet src 10.0.0.0/8 # RFC1918 possible internal network
acl localnet src 172.16.0.0/12  # RFC1918 possible internal network
acl localnet src 192.168.0.0/16 # RFC1918 possible internal network
acl localnet src fc00::/7       # RFC 4193 local private network range
acl localnet src fe80::/10      # RFC 4291 link-local (directly plugged) machines
acl SSL_ports port 443
acl Safe_ports port 80      # http
acl Safe_ports port 443     # https
acl Safe_ports port 1025-65535  # unregistered ports
acl CONNECT method CONNECT
http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_access deny manager
http_access deny to_localhost
http_access allow crx_url
http_access allow all
http_port 8888
cache_dir ufs /var/spool/squid 2048 16 256
coredump_dir /var/spool/squid
refresh_pattern .       0   20% 4320
via off
request_header_access X-Sogou-Auth deny all
request_header_access X-Sogou-Timestamp deny all
request_header_access X-Sogou-Tag deny all
request_header_access Server deny all
request_header_access WWW-Authenticate deny all
request_header_access All allow all
httpd_suppress_version_string on
visible_hostname localhost
forwarded_for transparent
```

**Comment by yanggis** [comment]
你这个要查Squid的日志才能知道问题出在哪里。

**Comment by daiying-zhang** [comment]
请教一个问题，我用国外的vps搭建了一个squid的代理服务器，然后用了pac的自动代理。我发现在一个局域网里面，比如在公司，只有我一个人能用，我设置了登陆验证，只有我的电脑和手机能用，其他的电脑不能用，但是在其他公司，可以使用，有谁了解，指导下，谢谢

**Comment by beatFeTiger** [comment]
@zhuzhuor 请问小米盒子之类的按照您配置的服务器该如何使用呢，帖子中看到貌似这样配置服务器只针对PAC文件和CHROME端的UNBLOCK YOUKU有效，请问是那个列表的关系嘛，该如何设置呢？

谢谢！
