### ISSUE TITLE
网易云音乐支持

### ISSUE THREAD

**Issue by fireattack** [Unblocker/Unblock-Youku#456]
由于某公文网易云音乐网络版从前几天起完全屏蔽了国外ip（客户端、Apps暂时还能用）（之前只有少数歌曲不能听）。

希望unblock youku能跟进，谢谢！

**Comment by fireattack** [comment]
麻烦哪位加个enhancement的label。

**Comment by aar0u** [comment]
希望添加对云音乐的支持。

**Comment by xkk** [comment]
就过了个周末这就不能听了 周五还好好的

**Comment by fireattack** [comment]
@xkk 应该与此有关
http://www.ncac.gov.cn/chinacopyright/contents/518/255834.html

**Comment by ethanyoung** [comment]
完全屏蔽了。刚想来发个贴。。。。

**Comment by albertnetymk** [comment]
While waiting for support, this hack seems to work.

1. Go to one playlist: e.g: http://music.163.com/#/playlist?id=28162761
2. Open the console, assuming you are using chrome.
3. Paste the following, and hit enter.
```
GAbroad = false; _iframe = document.getElementById('g_iframe');_iframe.contentWindow.GAbroad = false;
```

**Comment by zhuzhuor** [comment]
@albertnetymk Thanks for your method！

这样的话，做成个 bookmark 也行
手动新建一个 bookmark，然后链接填
```
javascript:(function(){GAbroad=false;document.getElementById('g_iframe').contentWindow.GAbroad=false;})();
```
回头只要在 playlist 的页面上点一下这个 bookmark 就行了

**Comment by albertnetymk** [comment]
Excellent, but this is just a hack. Looking forward to the final solution.

**Comment by aar0u** [comment]
@albertnetymk awesome!!!
@zhuzhuor 书签很实用。 
感谢两位，更省事儿的办法就是自己放user script了。

**Comment by ming21788** [comment]
是不是好像沒效了? 前天还可以的.

**Comment by ethanyoung** [comment]
在澳大利亚可以用。

**Comment by outofbound** [comment]
加拿大手机端可以用 网页基本全部歌曲失效

**Comment by zhuzhuor** [comment]
发现我这边（加拿大）现在直接打开网页也没有限制了，播放也没问题
前两天实验那个 js bookmarklet 的时候歌单还是灰色的

>  ![screen shot 2015-08-08 at 12 04 20 am](https://cloud.githubusercontent.com/assets/928905/9148980/37f2f37a-3d61-11e5-9dd6-b9916ee9d364.png)

**Comment by CaptainCan** [comment]
美国不行 刚试了下 iphone上有什么办法么？

**Comment by xkk** [comment]
刚刚测试了一下貌似又恢复正常了

**Comment by hihitoni** [comment]
使用unlockyouku 路由器 iOS 客户端 pc客户端一起正常

**Comment by tripall** [comment]
在台灣試了也不行 javascript hack那方法好像也行不通 還有什麼辦法嗎?

**Comment by gnibre** [comment]
好像是作者typo， GAbroad打成GAboard了， 估计能很快修复吧 ：）

**Comment by fireattack** [comment]
好像还是不好使啊 @zhuzhuor
