### ISSUE TITLE
dns好像还是不能用

### ISSUE THREAD

**Issue by carilwang** [Unblocker/Unblock-Youku#460]
刚在弄小米盒子，装了易翻墙，检查了dns设置。确认dns ip是unblock youku的dns ip.测试了网络都正常。但是腾讯视频跟优酷里面的花千骨都不能看。在电脑上用unblock youku的chrome插件就能看。

**Comment by Dummykid** [comment]
我家里的盒子也是这个问题. 我dns设置的是192.241.222.103

**Comment by yanggis** [comment]
@Dummykid 你设置盒子的DNS为104.236.189.178试试。

**Comment by carilwang** [comment]
刚在小米盒子里面试了，不行

On Monday, September 7, 2015, yanggis <notifications@github.com> wrote:

> @Dummykid <https://github.com/Dummykid> 你设置盒子的DNS为104.236.189.178试试。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Unblocker/Unblock-Youku/issues/460#issuecomment-138394074>
> .
>


-- 
Tony

**Comment by yanggis** [comment]
@carilwang 你家公网IP是多少？你在小米盒子上用浏览器打开www.ip138.com看看显示的公网IP是多少，我看看你的盒子有没有连到我的服务器。

**Comment by carilwang** [comment]
76.102.251.13
On Tuesday, September 8, 2015, yanggis <notifications@github.com> wrote:

> @carilwang <https://github.com/carilwang> 你家公网IP是多少？你在小米盒子上用浏览器打开
> www.ip138.com看看显示的公网IP是多少，我看看你的盒子有没有连到我的服务器。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Unblocker/Unblock-Youku/issues/460#issuecomment-138777755>
> .
>


-- 
Tony

**Comment by yanggis** [comment]
@carilwang 你说你把DNS设置成104.236189.178后，在小米盒子上用浏览器打开www.ip138.com看看显示的公网IP是76.102.251.13吗？
这说明你的本地网络有问题，如果你是在家里的话，应该是路由器DNS缓存没有清理，如果是在单位就是单位有强制性的DNS劫持。当你向我的DNS请求数据的时候，你自己的路由器或者单位路由器缓存先返回了数据给你，导致我发送给你的正确数据被忽略掉了。

**Comment by carilwang** [comment]
我以为你问我ip。在小米盒子里用浏览器得到的ip是124.234.127.214

On Wednesday, September 9, 2015, yanggis <notifications@github.com> wrote:

> @carilwang <https://github.com/carilwang>
> 你说你把DNS设置成104.236189.178后，在小米盒子上用浏览器打开www.ip138.com
> 看看显示的公网IP是76.102.251.13吗？
>
> 这说明你的本地网络有问题，如果你是在家里的话，应该是路由器DNS缓存没有清理，如果是在单位就是单位有强制性的DNS劫持。当你向我的DNS请求数据的时候，你自己的路由器或者单位路由器缓存先返回了数据给你，导致我发送给你的正确数据被忽略掉了。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Unblocker/Unblock-Youku/issues/460#issuecomment-138810413>
> .
>


-- 
Tony

**Comment by yanggis** [comment]
@carilwang 那应该就是对的啊，你在小米盒子上装个优酷视频，或者VST全聚合，看搜狐视频，或者优酷视频等等，会提示有版权限制吗？

**Comment by carilwang** [comment]
在云视听里面用花千骨来测试是一个null错误。然后在优酷tv就说不是国内ip

2015-09-09 9:37 GMT-07:00 yanggis <notifications@github.com>:

> @carilwang <https://github.com/carilwang>
> 那应该就是对的啊，你在小米盒子上装个优酷视频，或者VST全聚合，看搜狐视频，或者优酷视频等等，会提示有版权限制吗？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Unblocker/Unblock-Youku/issues/460#issuecomment-138966076>
> .
>



-- 
Tony

**Comment by yanggis** [comment]
@carilwang 企鹅.云试听是他们自己软件的问题。你把你自己的笔记本电脑的dns设置成104.236.189.178试一下能不能看优酷视频的美剧。记着只设置一个dns，第二个空着就可以了。

**Comment by carilwang** [comment]
下了一个优酷xl，可以用了。云视听看来的确是软件问题。还有我想请教一下你的dns是怎么弄的。因为我自己弄的DNS在Apple
TV跟kodi都能用。但是到了盒子就不行了

On Wednesday, September 9, 2015, yanggis <notifications@github.com> wrote:

> @carilwang <https://github.com/carilwang>
> 企鹅.云试听是他们自己软件的问题。你把你自己的笔记本电脑的dns设置成104.236.189.178试一下能不能看优酷视频的美剧。记着只设置一个dns，第二个空着就可以了。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Unblocker/Unblock-Youku/issues/460#issuecomment-139083786>
> .
>


-- 
Tony

**Comment by yanggis** [comment]
@carilwang 我建议你装个VST全聚合，上面电视剧和电影全部都有了，可以选择不同的源播放。优酷XL有时候网络很慢，只有60k/s看视频高峰期会卡。DNS就是装个dnsmasq软件，提供DNS服务就好了。

**Comment by carilwang** [comment]
I am trying to make a dns as well. Can you send me the /etc/hosts?

On Thursday, September 10, 2015, yanggis <notifications@github.com> wrote:

> @carilwang <https://github.com/carilwang>
> 我建议你装个VST全聚合，上面电视剧和电影全部都有了，可以选择不同的源播放。优酷XL有时候网络很慢，只有60k/s看视频高峰期会卡。DNS就是装个dnsmasq软件，提供DNS服务就好了。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Unblocker/Unblock-Youku/issues/460#issuecomment-139419829>
> .
>


-- 
Tony
