### ISSUE TITLE
求大神开发个Safari版本~

### ISSUE THREAD

**Issue by au0750** [Unblocker/Unblock-Youku#461]
Chrome实在是太费cpu和费电了...

**Comment by zhuzhuor** [comment]
我觉得我个人精力有限，如果能全力做好 Chrome 版本就很好了
所以欢迎有能力有兴趣的人来做个 Safari 版本

类似 @whuhacker 做的 Firefox 版本，就是先做了内置 PAC 文件的功能

**Comment by au0750** [comment]
Firefox版本挂了, 现在只剩chrome版能用了. 
(我也试过用pac设置, ip 163 也显示为true, 但是其他浏览器还是看不了.)

**Comment by hihitoni** [comment]
@zhuzhuor  K大最近都没有更新路由器文件 觉得路由器全网解锁蛮方便的，可以使用PAC的地址，也可以使用dns，希望跟进。 在此表示谢谢你们的工作

**Comment by zhuzhuor** [comment]
@hihitoni 我前两天发邮件问了 @karlcheong，他说他最近有点忙，没有时间来维护 github 上的事情

DNS 和 PAC 的服务器我已经交给 @whuhacker，有什么事情 @ 他，看看他之后怎么更新和维护吧
