### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by tommyzhaozbh** [Unblocker/Unblock-Youku#462]
话说之前该死的DOS攻击终于告一段落，但我发现两个问题:
1. 虽然现在是停止了攻击，但服务器偶尔还是会有downtime，不知道是服务器问题还是哪里出了问题?
2. Unblock DNS的代理服务器时常不稳定，监控以来一直都有downtime，今天傍晚干脆罢工了，直到现在还没恢复，结果我的手机也就不能看片了。看来这服务器得争气点才行

**Comment by zhuzhuor** [comment]
**Chrome 代理服务器的架构问题**
最近因为攻击，大改了服务器架构，还在一点点完善。特别是用了几个新的运营商的服务器，比如 M1 今天早上就不知道为什么出问题，而且也牵连了 redirect mode service

不过 Chrome 扩展用的这些服务器都互为冗余，一个 down 了后台会自动切换到别的，所以用户受影响不是很大，而且我们可以慢慢来修复有问题的机器

关于 M1 这机器的问题，我也不知道为啥这样，在后台也看不出来问题，前两天也没有问题，猜测是运营商的网络哪里出了问题吧。如果我解决不了了，回头也得让别人帮忙看看

**DNS 的问题**
DNS 的问题貌似是 @whuhacker 用了 Baidu BAE 的东西，说是那东西经常能碰到 bug 什么的，具体等他来解答吧

**另外一些题外话**
另外 99.9% uptime 其实很难的，每天的 downtime 要不小于 90 秒。可以看到 pingdom 上昨天有个 downtime 2 分钟的标了黄色感叹号
没有雇佣全职的 devops 盯着，没有很多的备份服务器，高的 uptime 很难达到，我们只能尽力去把系统做的更加稳定。用业余时间给 300 万用户提供稳定的服务不是件容易的事情，希望你能够理解
不过这也是一个非常有责任、非常 rewarding 的过程，希望有兴趣有能力的人都可以加入我们，来帮助大家

**Comment by tommyzhaozbh** [comment]
@zhuzhuor 辛苦了。希望这些不稳定能够尽快解决吧。还有刚发现iqiyi ipad客户端即便用了pac仍然有地区限制，但网页版则没有，猜测是有新地址了。但是我用Connectify+Wireshark就只能检测到response却检查不到request。我不太会用mitmproxy，能帮一下忙么？

**Comment by zhuzhuor** [comment]
@tommyzhaozbh 我自己没用过 mitmproxy，网上搜了下找到这么几篇文章你可以看看
http://jasdev.me/intercepting-ios-traffic/
http://faizalzakaria.github.io/2015/06/25/intercept-request-using-mitmproxy/

**Comment by xkk** [comment]
@zhuzhuor 如果你说的M1是新加坡的运营商的话 我建议你换一个 貌似他家的网经常出问题

**Comment by zhuzhuor** [comment]
@xkk 多谢提醒！

**Comment by yanggis** [comment]
@zhuzhuor 现在还有没有dnsmasq用的配置文件呀？记得以前有的，还有教程，现在找了一圈也没找到。呵呵。

**Comment by yanggis** [comment]
@zhuzhuor 原来是在这里，https://www.dropbox.com/s/su1p0j95igcycv1/reverseproxysetting.7z

password: karlcheong
现在文件被删掉了，下载不了。能再提供一下吗？

**Comment by whuhacker** [comment]
@yanggis Check it [here](https://github.com/karlcheong/unblock_youku_privoxy_rules)

**Comment by hihitoni** [comment]
@whuhacker  最近手机客户端的乐视美剧不能观看

**Comment by whuhacker** [comment]
@hihitoni 你是用的 PAC 吗？

**Comment by hihitoni** [comment]
@whuhacker  iphone手机客户端  试过直接用PAC  DNS，  路由器用PAC地址或者DNS 都不行 .pc网页就可以

**Comment by hihitoni** [comment]
@whuhacker  顺便提一下，iPhone直接用pac QQ音乐客户端不能解锁，还有腾讯视频电视剧部分不能解锁。

**Comment by tommyzhaozbh** [comment]
@hihitoni ipad客户端单用pac测试正常，如果不行的话你就dns和pac一起用。

**Comment by mc16888** [comment]
@whuhacker for iOS LETV app, can you check if add following url to pac/dns will fix the problem.
I try to watch movie 左耳, but got blocked, then I add this domain api.mob.app.letv.com to my China VPN connection, then I can watch it.

The url looks like this.
http://api.mob.app.letv.com/play?tss=ios&playid=0&tm=1439605213xxxxxxxxxxxxxxxxx

**Comment by zhuzhuor** [comment]
我发现 aliyun 可以用国外的手机号注册，回头可以试试用国外手机注册的整个流程
有人感兴趣也可以试试看
