### ISSUE TITLE
Bug:关于dns问题反馈

### ISSUE THREAD

**Issue by tommyzhaozbh** [Unblocker/Unblock-Youku#465]
首先，感谢两位大神在维护服务器所作出的努力，目前浏览器插件运行正常还是非常感谢的，但dns好像出了问题要看一下，目前部分视频网站以及音乐软件的代理出现异常，已知的问题网站包括爱奇艺和优酷(客户端和网页版均失效，全部无法获取视频真实地址，爱奇艺连网页播放器都没法加载)，音乐软件则有百度音乐(会显示网络不给力)，而qq音乐和搜狐则运行正常。希望能够尽快处理一下，我也会继续留意并及时报告新的检测链接，谢谢!

**Comment by tommyzhaozbh** [comment]
另外，由于pac和dns的代理服务器合二为一了，这也就意味着两个同时出现问题。目前上述提到的网站在移动端完全是瘫痪的，所以请尽快修复。

**Comment by zhuzhuor** [comment]
@tommyzhaozbh 你这关注非常紧密啊...
昨天 @whuhacker 给 DNS 临时用了一下 PAC 的代理服务器，现在已经分开了

**Comment by whuhacker** [comment]
我们怀疑 DNS 服务器正在被滥用，现在经常会出问题，我看了下 log 有很多电视盒子的无效访问。
如果有需要我可以为你们开设独立的 DNS 服务器，请不要过多消耗免费资源，不然出了问题大家都用不到。

**Comment by tommyzhaozbh** [comment]
@zhuzhuor 那是肯定的，因为前几天就发现DNS不能用就时常去检查一下状态，刚好发现了。
@whuhacker 不知道是不是有人蓄意所为，那能不能设置规则过滤这些无效请求呢？

**Comment by xkk** [comment]
@whuhacker 想问下什么样的算是无效访问呢？目前盒子在用dns 不过youku很多视频不能看 已经有段时间了

**Comment by osososo** [comment]
@whuhacker @zhuzhuor 谢谢大大们辛苦开发和维护，让无数人收益。我就是其中一员。我人在美国，靠着您们的劳动才看到众多国内节目。谢谢！看到了前两天@zhuzhuor 的教程（建立自己的代理），我不能算小白，但也差不太多，教程看的基本明白，实践中目前卡在没有国内的手机无法注册，正在想办法解决。另外请问DNS怎么建立，可以麻烦大大们写个教程吗？192.241.222.103应该是如whuhacker大大所说的，可能被滥用了，至少我身边的朋友的机顶盒都是靠它，不过已经几个星期不能用了。所以在想要是不是太难的话，希望自己能开设一个DNS，不知道行不行。

**Comment by carilwang** [comment]
有个想法不知道行不行得通。在家里用raspberry pi建一个squid的服务器。然后用一些类似于pac的rule，把符合的连接转到proxy.uku.im:443。 盒子就把proxy设置成squid的内网地址

**Comment by benhong** [comment]
@osososo carilwang 
找一台支援openvpn 的router 之后利用vpn 连线到我架的VPN server (#466  )
连上线后 router  就解放了

**Comment by iamyangchen** [comment]
@carilwang 你的想法有实现过嘛？我最近在想办法解决Kodi (XBMC) 上国内视频插件的unblock youku问题，不清楚要怎么配置

**Comment by carilwang** [comment]
@iamyangchen 我想法是实现了。一个python的代理服务器，使用pac的regex来判断是否连接unblock youku的代理。iPhone测试可以使用。如果kodi的话可以python放在同一台机器上，然后把kodi的代理设成本地应该就可以。我改天把代码上传一下

**Comment by yanggis** [comment]
@xkk, @osososo, @carilwang, @iamyangchen 
可以用一下我的DNS服务器试试，DNS IP是104.236.189.178。设置后访问ip138.com，如果显示的是国内ip就可以正常在电视盒子上看国内视频了。有些地方尤其是工作单位或者学校路由器设置有DNS缓存，配置这个DNS就可能无效。
仅作测试之用。

**Comment by carilwang** [comment]
@iamyangchen 
试试这个python的proxy，把你的xbmc的代理设成本地看行不行
https://drive.google.com/file/d/0B22dKUPrll63bUZSN1ROOU1zN2s/view?usp=sharing
