### ISSUE TITLE
教学 如何让iphone使用行动网路，也可以看内地视频

### ISSUE THREAD

**Issue by benhong** [Unblocker/Unblock-Youku#466]
ios config      http://zqgd.org/ios.php
pc config       http://zqgd.org/pc.php
router config http://zqgd.org/router.php 
pac file http://zqgd.org/proxy.pac
3者差异在，
ios config 连线vpn server 后，server 是推送pac 的网址给client，pac 网址为 https://goo.gl/YPyciK
pc config 连线vpn server后 ，server 是推送 route table 给client，可用平台 android ,ios ,pc,，只要支援openvpn基本上都可以使用
router config 基本上原本和pc config 是一样的差异在，连线成功后会执行以下指令，"iptables -A POSTROUTING -t nat -o tun0 -j MASQUERADE" ，可用平台支援openvpn的路由器

以下是ios 的使用范例，
其他平台请参考这里，http://www.vpngate.net/cn/howto_openvpn.aspx
基本上不一样的地方就只有config 

开启 "App Store" ，搜索并下载 "OpenVPN Connect" 。
![image](https://cloud.githubusercontent.com/assets/13610597/9218171/8af548e4-4102-11e5-80a9-03b25e8630d4.png)

开启 "Safari" ，并且到这个网址　http://emset306.2fh.co/
点 "在 open vpn 里打开"
![image](https://cloud.githubusercontent.com/assets/13610597/9218218/0811a584-4103-11e5-91d5-a686231c7b36.png)
会自动开启openvpn，点选＋
![image](https://cloud.githubusercontent.com/assets/13610597/9218251/6b725862-4103-11e5-883e-9c5b603801a0.png)
按一下就可以连接VPN server 了
![image](https://cloud.githubusercontent.com/assets/13610597/9218274/9e9072a6-4103-11e5-8b87-37ffb6e6684a.png)
等到变成这样，就表示连线成功
![image](https://cloud.githubusercontent.com/assets/13610597/9218310/f0f9f86e-4103-11e5-91cc-82765712a6e9.png)

验证是否成功
开启 "Safari" ，并且到这个网址　www.whatismyip.com.tw
看看IP是否为 43.241.217.35
![image](https://cloud.githubusercontent.com/assets/13610597/9218425/fa439726-4104-11e5-9cf3-7cb82281c43f.png)

**Comment by zhuzhuor** [comment]
感谢教学帖

但是你说的这 `http://emset306.2fh.co/` 安全吗，是你自己弄的服务器还是别人提供的？

如果是你自己架设的，欢迎写个详细的安装教程

另外这个的 VPN 连接在手机锁屏的时候会保持吗，我记得一般的 iOS VPN app 在手机锁屏之后经常要手动重连

**Comment by benhong** [comment]
http://emset306.2fh.co/ 這裡只是放config檔
他是免費的php 網頁空間
vpn主機是我自己架設的

因為我不熟悉內地的法律規範，我的網站沒有備案
所以我不敢將config 檔放在vpn的主機內
ios 的部份等我測試玩心得我在告訴你

教學的部分 我這幾天有空會做出來

**Comment by carilwang** [comment]
@benhong: 好像vpn能连，但是盒子完全不能看东西

**Comment by benhong** [comment]
@carilwang  不知道你是否可以用ssh 進去router 內
若可以，連上vpn 後執行 
iptables -A POSTROUTING -t nat -o tun0 -j MASQUERADE
若執行玩後可以用我在教你改設定檔

**Comment by ilove12girl** [comment]
@benhong 感謝教學，不過iphone6 ios8.4使用後，雖連上Von,但優酷app或是土豆app都還是不行欸，有什麼需要另外設定的嗎？

**Comment by benhong** [comment]
@ilove12girl  這部分 我會去修改VPN server 的配置檔

**Comment by benhong** [comment]
@ilove12girl  我變更了vpn server 的配置，重推送 router table 方式，改成推送 pac 檔了
pac 檔我放在google 不知道有沒有流量限制就是了

**Comment by ilove12girl** [comment]
@benhong  目前連vpn servver都會timeout了

**Comment by ilove12girl** [comment]
@benhong 剛剛試可以了!!~~謝謝~~希望之後可以有vpn server架設教學文,讓我們也能自行架設,這樣才不會造成你的vpn server負擔過重

**Comment by benhong** [comment]
@ilove12girl  目前沒甚麼人在用，所以應該沒有付載過量的問題，"vpn server架設教學文" ，重PO文到現在有連線進去的應該不到10個，我連寫教學都沒有動力，

**Comment by kclonline** [comment]
@benhong 这个VPN只要是能连上OpenVPN服务就可以使用吗？比如PC、Android、IOS、IPhone、盒子？

**Comment by benhong** [comment]
目前這份設定檔指針對ios
Android pC需要令一份設定檔才可以

盒子指的是？看電影那種機上盒嗎？
若是就看他是否有支援openvpn

要是指的是路由器，那還需要另一份設定檔

**Comment by ilove12girl** [comment]
@benhong 如果之後你有空的話，可以麻煩你弄個android的設定檔嗎？謝謝你～～

**Comment by zhuzhuor** [comment]
@benhong 你可以试试用 Cisco AnyConnect 和 ocserv
http://www.infradead.org/ocserv/index.html

**Comment by mc16888** [comment]
@benhong 請問這個服務器是不是設在美團云上面 ? 如果是的話,請問美團云可不可以用海外發的信用卡給錢, 還是一定要用支付寶 ? 謝謝.

**Comment by benhong** [comment]
@mc16888  是的在團云上面 ，我是这样付费的，用支付宝，然后支付宝使用者人代付，
在台湾还满多帮人代付的，汇率手续费都比信用卡还要优惠，我是用转帐给帮人代付的人
若你是台湾人我可以介绍给你

＠zhuzhuor  若我在美團云 架一个http 但是我不是使用80或8080 port 目前网站没有备案，这样我会违反法律规定嘛，因为我有些档案还是必须要有网页空间，

**Comment by benhong** [comment]
＠ilove12girl  android  设定档我已经提供了，你测试看看吧

**Comment by hihitoni** [comment]
@zhuzhuor  购买了美团云的主机 购买主机时没有公网IP ,我现在是分开购买， 40+公网ip每小时0.04.
@benhong 你的美团云unlockyouku主机可以QQ音乐解锁吗？

**Comment by benhong** [comment]
＠hihitoni  我不确定耶，可以给我网址我去确认嘛，若真的还是不行，我在请客服帮我协调qq那边处理
之前客服我帮我处理过qq视频网站ip 被档的问题

＠hihitoni 老实说美团云 还满贵的（1个人用的话），1个月最少要68元
目前打算去阿里云费用应该可以更低

**Comment by carilwang** [comment]
@benhong 这个功能是不是一直要连着vpn才能用。还是只需要一次推送就行？是所有数据都走vpn还是只是在访问专门的url时使用？Apple TV能用吗？

**Comment by benhong** [comment]
@carilwang 1.要一直連線才有用 2.ios版是看特定的url，奇他平台則看ip,才會走Vpn. 3.apple TV 沒測試過，也不知道你怎樣運用apple TV

**Comment by mc16888** [comment]
@benhong 謝謝,我是香港人,我已經請我內地朋友代付.

**Comment by hihitoni** [comment]
@benhong 已经解决了 不过还是非常感谢。美团云服务器我有10几个人在用 用路由器或者PAC，价格算起来还可以 ，最麻烦的是付钱。

**Comment by carilwang** [comment]
@benhong 可以写个vpn设置的教学吗

**Comment by mc16888** [comment]
@hihitoni 我的美团云IP 一樣被QQ音乐 (iOS App) 誤判成日本的 IP, 請問是不是要請客服处理? QQ视频网反到沒問題.

**Comment by hihitoni** [comment]
@mc16888 向客服反映处理了下 ，QQ音乐 （IOS App）还是一样不能使用。你可以使用PAC ，倒是可以

**Comment by mc16888** [comment]
@hihitoni 谢谢，我以向美团云客服反映。

**Comment by carilwang** [comment]
@ilove12girl你试了在盒子上能用吗？需要root吗

**Comment by ilove12girl** [comment]
@carilwang 目前都會timeout連不上vpn server,所以也不知道，不過root是不用的

**Comment by ilove12girl** [comment]
@benhong 試了下android的，看影片會顯示連接伺服器異常，沒辦法使用

**Comment by benhong** [comment]
@ilove12girl  連線會timeout 的問題 ，我目前也在找原因

**Comment by mc16888** [comment]
@benhong @ilove12girl OpenVPN 連線會timeout 的問題會不會是 MTU 的問題 ?

https://www.sonassihosting.com/help/magestack/setting-correct-mtu-for-openvpn/

**Comment by benhong** [comment]
@mc16888  我在大陆的美团云和阿里云的vpn通通不能使用
并且都在昨天晚上开始，所以设定档都没有变动，看来应该备万里长城给挡住了
不知道你们是否也会

**Comment by mc16888** [comment]
@benhong 我没在美团云上弄VPN服务器，所以不知道是不是万里长城给挡住了。我还在弄Ｓｑｕｉｄ　Ｐｒｏｘｙ，因为ＱＱ音乐和乐视网把我的浮动ＩＰ误判成日本的ＩＰ，美团云的客服今天早上说已经解决，可我刚试了一下，还是不行。

**Comment by yanggis** [comment]
@benhong ,就不用想在美团云上面建VPN，现在所有中国的出站VPN都是被干扰的，基本都连不上。最好的就是用SS。

**Comment by benhong** [comment]
@mc16888  其实美团云真的有处理，我记得钱几天不能登陆qq的网页，现在可以了，只不过app一样不行，看来回报给客服 要更详细一点更明确一点

＠yanggis 我懒得处理了，现在家里的路由器直接改成 privoxy 将特定的网站做代理，在使用iptable 将lan 的资料有关port 80 的资料通通往privoxy 送，实现了在路由器下的装置，都不需要做任何设定
就可以直接翻墙了，并且在路由器下架设vpn server给iphone使用，目的是当iphone 连线vpn 后只有推送pac 文档给iphone ，并且所有流量都不走vpn，实现了在4g网路下也可以翻墙

@zhuzhuor 由于内地的的政策，干扰了vpn 的运作，目前我在阿里云，美团云都无法正常的vpn连线，我是否可以将我发表的文章给移除呢？

**Comment by yanggis** [comment]
@benhong 其实和中国通讯是一个麻烦事，我自己的VPS设在San Francisco，在上面架设了一个DNS服务器看大陆视频，DNS IP是104.236.189.178，也是使用iptables把特定数据包转发到中国的服务器上。但是需要中国一个服务器做配合，并且能够稳定通讯。你可以试一下那个DNS，在北京时间7点-9点的网络高峰期就会有点不稳定。

**Comment by ilove12girl** [comment]
@benhong  剛剛試vpn server又可以連了,我是覺得這個vpn server假如可以的話可以先放在上面不要移掉,如果到時候有要移掉的話,希望大大能夠寫個vpn server教學文供我們學習學習,感謝~~

**Comment by mc16888** [comment]
@benhong 我回报的时候已经截图給他们。另外我去阿里云买的时候，好像一定要我实名认证。不知道我是不是哪里操作有误。>_<

**Comment by benhong** [comment]
@mc16888 阿里雲 不只要实名认证，网站也都要备案
我是这样做啦，实名认证去google收寻实名认证v2，选有可关联的数量看自己，难后把自己的支付宝给关联进去，之后用自己的支付宝到阿里云进行实名认证，备案的部份，去淘x购买以备案过的域名，并且要购买阿里云或万网入口商的，以上都是偷鸡的方法，所以点到为止罗～

@ilove12girl  
VPN 安装方式请看这里，http://www.unixmen.com/install-openvpn-centos-7/
设定玩后再根据以下修改就可以了
1.将SERVER 设定档 push "redirect-gateway def1 bypass-dhcp"  , 取消
2.在SERCER 设定档 新增一行 push "dhcp-option PROXY_AUTO_CONFIG_URL https://goo.gl/YPyciK",
其中 https://goo.gl/YPyciK 为你的pac档的位置，这一行只有ios可以用
等你有遇到问题在提问吧

**Comment by zhuzhuor** [comment]
@benhong 你是想删除这整个 issue 吗？你要是确定要删除的话我可以帮你删除
不过推荐你可以把教程之类先匿名贴到 pastebin 之类上去

**Comment by mc16888** [comment]
@benhong 阿里雲这么麻烦，我还是乖乖的用美团云算了。

**Comment by ilove12girl** [comment]
@benhong 請問現在Vpn server 還有開著嗎？好像ios跟android都不能連了

**Comment by ilove12girl** [comment]
@benhong 我可以再請教關於android的推送 route table 给client該如何做呢?又推送pac跟推送route table可以同時弄在同一台,方便android跟ios都能一起用嗎?再謝謝解答了
