### ISSUE TITLE
Apple tv的一个问题

### ISSUE THREAD

**Issue by carilwang** [Unblocker/Unblock-Youku#469]
我现在无论Apple TV还是iPhone，iPad都是用相同的pac，iPhone，iPad都能放腾讯视频，但是一AirPlay就不行。首先会是说AirPlay 停止然后重新菊花，又立刻说AirPlay停止，又立刻菊花。这次就无限菊花了

**Comment by reilee** [comment]
应该是需要在apple tv上也设置相同的pac。
虽然我也没试验成功过。

**Comment by zhuzhuor** [comment]
@reilee Good idea! 
@carilwang 你试试能不能也给 Apple TV 设置上 PAC 文件之后再试试

**Comment by carilwang** [comment]
我是设置成一样的pac.查了一下数据的走向，看来是当apple tv连的时候，可能数据量特别大。要等2分钟才会播放

**Comment by zhuzhuor** [comment]
@carilwang 等两分钟之后就能正常播放了吗，播放的时候卡不卡
理应不会有特别大的数据量呢，可能是对 Apple TV 的 URL 优化没做好
