### ISSUE TITLE
有些在日本经常不好使的网页

### ISSUE THREAD

**Issue by greendee7** [Unblocker/Unblock-Youku#475]
最常见的为爱奇艺，如果直接在网页搜爱奇艺，百分之90是打不开的，一直空白页面加载的状态，我最爱看的是康熙来了，如果直接输入综艺的名字反而比较容易进去，不过偶尔还是会出现播放失败的时候。但如果输入电视剧名字，比如说花千骨，那么失败几率仍然很大。
第二个是优酷，我用的不多，因为印象中很少有能看的时候，基本上都是一开始加载，之后就再也不动了

如果可以更加完善就更好啦，谢谢你们哦

**Comment by zhuzhuor** [comment]
“在页面搜索爱奇艺” 具体指的是？
如果你指的是爱奇艺的网页打不开的话，我们其实对爱奇艺的网页部分没有做任何的操作
我们只对视频播放前的地区验证部分通过了大陆的代理服务器

推荐你检查一下你所用的网络、已安装的别的扩展程序
另外可以尝试卸载 Unblock-Youku 扩展程序，然后试试还有没有你提到的问题，如果卸载了之后问题不出现了请再来汇报，如果卸载了之后还是有问题就可能是你本地网络的问题

**Comment by reilee** [comment]
楼主说的应该是“在爱奇艺网站中搜索指定资源”，确实大多数情况下爱奇艺会返回404或者版权限制。但如果是在搜索引擎中直接搜索到的爱奇艺资源是可以打开的。

**Comment by zhuzhuor** [comment]
@reilee 你也是在日本吗，能举个具体的搜索例子吗
我现在在美国，貌似不能重现这个问题

**Comment by reilee** [comment]
爱奇艺并不常看，现在似乎没有这个问题了。
之前确实有过，好像是看《寄生兽》，在www.iqiyi.com的搜索里一搜就挂。但是如果在google指定site:iqiyi.com这样搜到的内容就可以看。

**Comment by reilee** [comment]
个人猜测这个原因是插件并没有代理所有爱奇艺url pattern，而爱奇艺的站内搜索发现搜索请求来自海外就返回错误页面。
