### ISSUE TITLE
有没有DNS的教程

### ISSUE THREAD

**Issue by carilwang** [Unblocker/Unblock-Youku#477]
是不是可以写个dns的教学

**Comment by zhuzhuor** [comment]
@whuhacker 那里有个简易的教程，等他完善了之后看什么时候可以放出来吧

我个人觉得建个公共 DNS 不复杂，但是要避免被人用来放大 DDoS 攻击
https://www.incapsula.com/ddos/attack-glossary/dns-amplification.html
https://blog.cloudflare.com/deep-inside-a-dns-amplification-ddos-attack/
之前我们经常收到 DigitalOcean 客服的警告，而 @karlcheong 做了很多的工作来防止这个

另外建设公共 DNS 要担负起巨大的责任，如果 DNS 服务器被黑，用户的很多隐私信息可能就遭殃了
相比较而言，一个基于白名单的代理服务器则要安全很多，经过服务器的只有那几个特定的网站

所以我个人希望这个  DNS 教程能弄得完善一点再放出来，特别是要强调一些安全的设置部分
另外请把这个 DNS 架设在自己的内网中，例如用 [Raspberry Pi](https://www.raspberrypi.org/) 弄个小的服务器；或者设置防火墙让 DNS 服务器只能通过特定的 IP 网段才能访问

**Comment by yanggis** [comment]
@zhuzhuor，@carilwang，我自己做了一个DNS服务器，IP地址104.236.189.178，欢迎测试。如Zhuzhuor所言，自己建DNS服务器的确比较麻烦，而且稳定性很难保证。

**Comment by tywtyw2002** [comment]
路由器刷了ddwrt 或者openwrt的话可以用dnsmasq做dns服务器。

公网的话最好用iptables 去限制每个ip每分钟的请求数量。

**Comment by yuiop99** [comment]
@tywtyw2002 可以写个详细的教程吗？谢谢

**Comment by lzfxxx** [comment]
@zhuzhuor 请问教程完善了吗

**Comment by zhuzhuor** [comment]
@lzfxxx 我自己没弄过 DNS
可以问问 @whuhacker 和 @yanggis

**Comment by alexking99** [comment]
同求DNS教学@zhuzhuor @whuhacker @yanggis

**Comment by batiatus** [comment]
同求
104 那个看东西好卡 
以前192那个好像不会这样

**Comment by KanVivii** [comment]
DNS教程还有写嘛
