### ISSUE TITLE
Unblock Youku 整个开源项目的架构重构

### ISSUE THREAD

**Issue by zhuzhuor** [Unblocker/Unblock-Youku#478]
随着项目的越来越壮大和复杂，以我个人的名义已经不太方便管理项目的方方面面。很长时间以来我都想把这个项目转到这样的一个 GitHub Organizaiton 里，这样可以分成不同的子项目来交给专人分别管理。另外我明天就要开始 full-time 的工作，虽然我还是会抽时间积极开发和维护整个项目 (到目前为止几乎所有的服务器都是由我个人出资购买的)，但是工作日不能保证有大块的时间来写代码和回复各种问题，所以转到一个 GitHub Org 里说不定能让人帮忙来解决一些突然的着急的问题

并且，得益于 GitHub 的[新的 redirect 功能](https://developer.github.com/changes/2015-04-17-preview-repository-redirects/)，整个项目从 zhuzhuor/Unblock-Youku 迁移到 Unblocker/Unblock-Youku 应该也不会影响太多的第三方程序和软件。大家访问旧的链接例如 https://github.com/Unblocker/Unblock-Youku，也会自动跳转到新的项目主页

之前的 @tywtyw2002 的建议 #423 我之后也好好想了想。如果 URL 列表的部分拆开成这 Org 下面的单独的 repo，别的各个功能也可以分别拆开来。比如 Chrome 扩展程序和 redirect mode 服务器就可以拆开来成为两个 repo，@mozbugbox 做的 droxy 也可以单独放在一个 repo 里了，这样方便管理，每个 repo 也可以有自己的 GitHub issue + wiki

Org 的人员也可以分为好几个 team，例如 Chrome, Firefox, DNS, DevOps，分别来开发和维护不同的功能部分。我们也欢迎更多的朋友来加入我们，来为海外的朋友们做出贡献

**Comment by zhuzhuor** [comment]
另外现有的 wufoo 表格的 feedback 系统已经有点感觉不太能用了，用户反馈信息多得我早已看不过来了，只能挑一些重要的有很多人反馈的信息来首先处理
于是在考虑弄个 Google Group 或者论坛之类的东西，普通用户的反馈都发到那里去，这样大家都可以看到，大家也都可以互相帮助，简单的问题应该能更快得到解决。这样 GitHub 的 issue 系统也能更专注于 technical 的东西

**Comment by zhuzhuor** [comment]
占楼，未完待续

欢迎讨论

**Comment by whuhacker** [comment]
我尝试将 Firefox 项目迁移过来，出了些问题……
详见 IM 消息

**Comment by zhuzhuor** [comment]
@whuhacker 我把你的 Firefox 项目整个 fork 过来了
如果你喜欢的话，可以在原项目主页弄个 pointer 到新的项目
你想开发新的功能的话可以直接在这 Unblocker 下面开发，或者 push 到你的项目之后再 merge 过来

**Comment by yanggis** [comment]
@zhuzhuor 支持，希望这个项目能继续健康稳定的发展下去。如果有需要我可以贡献自己的VPS或者人力帮点小忙。

**Comment by tommyzhaozbh** [comment]
完全支持。其实开论坛可以减轻不少负担，另外我也想问如何加入这些team呢?

**Comment by kiyor** [comment]
关注中, 也希望尽一份力, 本人也有一些服务器可以做贡献. 也写过DNS, proxy.

**Comment by Dummykid** [comment]
我也想帮忙,但是我不会写码....

**Comment by csyangning** [comment]
报名！自己也是dev 一直在用这个service，希望也能贡献一点力

**Comment by Chasego** [comment]
报名报名！虽然没贡献过这个项目的代码，但是最近不停大家看到为了Unblock Youku努力，整个人都燃了起来！

**Comment by likeca** [comment]
我专攻Android + Kodi, 希望也能贡献一点力. UniXmc

**Comment by tywtyw2002** [comment]
恭喜恭喜，有需要的直接im我，我周五就休假结束了。

**Comment by zhuzhuor** [comment]
@yanggis @tommyzhaozbh @kiyor @Dummykid @csyangning @Chasego @likeca 
非常感谢！欢迎给海外的朋友们做出贡献，这是一个非常锻炼人也非常有责任感和荣誉感的事情
最好的给我们开源项目贡献的方法就是提交 pull request，如果经常给大家贡献高质量的 pull request 或者 solution 的话，我们会考虑逐渐给予 commit/admin 权限的

例如在现在的 Org 的 teams 里
@Unblocker/unblock-dns 负责 DNS 的维护和开发，现在有 @karlcheong 和 @whuhacker 
@Unblocker/firefox 负责 Firefox 扩展的维护的开发，有 @whuhacker 
@Unblocker/devops 负责后台代理服务器的维护的调优，有 @tywtyw2002 
他们都是一直逐步地给我们的项目贡献自己的代码和工作
（ BTW，如果有问题可以直接 @ 相应的 team，例如 @Unblocker/unblock-dns）

想要给我们的项目贡献的话，可以看看现有的 [open issues](https://github.com/Unblocker/Unblock-Youku/issues)
比如可以先试试一些看起来比较直截了当的工作，例如
* LETV iOS app 的问题 https://github.com/Unblocker/Unblock-Youku/issues/479
* 添加自定义代理服务器的功能 https://github.com/Unblocker/Unblock-Youku/issues/453
* 乐视直播的更新 https://github.com/Unblocker/Unblock-Youku/issues/473

**Comment by zhuzhuor** [comment]
另外 DNS 和 FIrefox 的扩展都弄了单独的 repo
有问题可以直接去特定的地方来提交问题

Unblock DNS 的 https://github.com/Unblocker/Unblock-DNS/issues
Firefox 扩展的 https://github.com/Unblocker/Unblock-Youku-Firefox/issues

**Comment by RogerFederer03** [comment]
弱弱的问一下，大神去哪里full-time工作呀？

打心眼里佩服大神 \(^o^)/~

**Comment by happier** [comment]
不怎么会写code，但还是留言支持下！
希望这个项目能继续健康稳定的发展下去+1

**Comment by NoAnyLove** [comment]
Raspbian/Kodi上的解决方案还更新吗？NPM上的ub.uku.js已经不见了，直接从github安装也无法运行。

**Comment by zhuzhuor** [comment]
@NoAnyLove `Raspbian/Kodi上的解决方案` 指的是？
ub.uku.js 已经不能用了，见 #331

**Comment by NoAnyLove** [comment]
@zhuzhuor 主要是指能在Linux系统上使用的，设置一个HTTP代理，然后能够智能判断，只让需要的链接走unblock-youku的服务器，而不影响其他链接。类似于《让Squid带有Unblock Youku功能》和《unblock youku路由器進階篇, 區域網絡下所有裝置全自動解鎖!》的解决方案。

第一个方案需要ub.uku.js，第二个方案好像有点问题，无法启动privoxy。

**Comment by jctank88** [comment]
这个add on跟shadowsocks的原理有什么不同吗？ https://github.com/shadowsocks  今天很多repo被要求删除了。

**Comment by yanggis** [comment]
@jctank88 shadowsocks作者被请去喝茶了，回来repo才遭大面积删除的。

**Comment by biankasyo** [comment]
如果能专门做一个路由器用的repo，定期更新代理规则(¯﹃¯)

**Comment by zhuzhuor** [comment]
@jctank88 完全不一样的东西
shadowsocks 是加密/混淆网络流量防止被咔嚓的，用户需要在本地和服务器都装 shadowsocks 的软件才行。我们这只是个简单用现成的 Squid 代理软件

**Comment by hihitoni** [comment]
@zhuzhuor 这几天PAC服务器IP地址是不是换了 qq音乐app（ios）出现版权限制 ，跟我自己的美团云服务器一样被视为日本，letv 美剧通过Finddler查看 ip也是日本。而通过192.241.222.103 ，letvapp（IOS）美剧出现视频暂不能观看，而使用@yanggis dns104.236.189.178 一切正常

**Comment by mc16888** [comment]
@hihitoni 估计您美团云服务器的浮动IP和我的一样，都是 43.241.xx.xx 开头的。Letv和QQ音乐到昨天为止一直把这一段IP判定为日本的。客服说Letv昨天以经解决，今天早上试，只有网页直播可以，网页的电影/美剧和iOS app 所有都不行。

**Comment by zhuzhuor** [comment]
@hihitoni 的确是这两天刚改回美团云
之前是 海外服务器->阿里云 这种单连线模式，不怎么稳定
最近有台服务器又出了问题，就赶紧切换到只用美团云了

@mc16888 估计他们的 IP 库还要点时间才能全更新，如果之后还是有问题再去反馈反馈

**Comment by zhuzhuor** [comment]
弄了个 Google Group，准备来替代现在的 Wufoo 的反馈表格
https://groups.google.com/forum/#!forum/unblock-youku
有人有兴趣可以试试看，如果没什么大问题过两天更新到 Chrome Web Store 上去

**Comment by mc16888** [comment]
@zhuzhuor, @hihitoni  刚刚美团云客服直接用电话连系我，帮我换了IP， 103.37.xx.xx 开头的, Letv和QQ音乐都行了。你们可以试请客服帮忙换一下。

**Comment by tommyzhaozbh** [comment]
@zhuzhuor 用google group的话有一个很大的问题就是人在国内的话就会很麻烦，像@whuhacker 就是在国内的。而且有时候我也会回去，这样要去看的话会很不方便。

**Comment by wyhfrank** [comment]
关注这个项目很久了，看着大伙儿都为了这个项目积极努力，很受感染也很想贡献自己一点力量。可是我技术不精，对Web开发不太熟，（可是很感兴趣。。:sweat_smile:）所以我想一边学习一边试着帮忙改进项目。

那么问题来了，我找了一下好像没有找到项目的开发文档，有时候想咨询一些技术的问题的时候不知道应该在以什么方式发呢？（发Issue、私聊？）

我现在遇到问题有，比如：

- 如何让插件支持新的URL？
具体是百度随心听（http://fm.baidu.com/ ），我直接把这个URL添加到`urls.js`的 `unblock_youku.common_urls` 列表里试了下好像不行。因为我看百度音乐（http://play.baidu.com/ ）也并非直接用的这个URL。所以我想知道这个添加原则应该是什么样的呢？

- 把URL列表放在**配置文件**之类的地方是否会更方便调试？
比如在插件的`Options`页面有一个可编辑的文本框可以加载和保存URL列表，这样就不用每次修改列表都重新加载插件了。把数据和代码分离开也许会更方便管理。（我还没仔细看Chrome插件的对应实现，不知道这样做是否合适。）

好像扯远了。。总之就是，诸如这类问题应该在哪里提呢？非常感谢！

**Comment by Heeeeeeeeh** [comment]
您好,有兴趣把此程序做大吗？ 有的话就联系b980182410@gmail.com

**Comment by zhuzhuor** [comment]
@tommyzhaozbh 我觉得这问题不大，我们的用户都在海外
只有个别几个 dev 在国内的话，用一些代理工具就好吧，@whuhacker 应该就是在长期翻墙中
我还有个给朋友弄的代理服务器，如果你有需要我可以给你试试看

另外没有找到 Google Group 的廉价/好用的替代品
看了下 Discourse，要么每月最便宜也要 $100，要么就只能自己搭建+维护服务器

**Comment by zhuzhuor** [comment]
@wyhfrank 热烈欢迎！

1. 的确现在没什么文档... 但是好在代码都不太多，Chrome 扩展部分的代码都在 chrome/ 和 shared/ 文件夹下。如果有问题看不懂可以发 issue 用 question tag
Chrome extension 的 Google 官方开发文档可以看看 https://developer.chrome.com/extensions

2. 改 urls.js 里面的列表是对的，只是我们现在后台的 Squid 代理服务器用同样的 URL 列表做了白名单过滤，所以如果还是用同样的代理服务器，只改前端的代码是没用的
Debug 的时候可以去搜个临时的代理服务器用用 http://www.proxynova.com/proxy-server-list/country-cn/

3. 添加 URL 的原则是让 URL 越详细具体越好，这样通过代理的数据少，用户访问速度快，我们的服务器压力也小

4. 之前有考虑过在 Options page 弄个自定义 URL 的功能，但是后来主要因为时间原因还没弄
有人感兴趣可以做做这个，唯一的考虑就是自定义 URL list 的时候也需要同时更改代理服务器才行

**Comment by ethanyoung** [comment]
建议将开发相关文档写进wiki里面，方便查阅。

**Comment by wyhfrank** [comment]
@zhuzhuor 
> 改 urls.js 里面的列表是对的，只是我们现在后台的 Squid 代理服务器用同样的 URL 列表做了白名单过滤，所以如果还是用同样的代理服务器，只改前端的代码是没用的
Debug 的时候可以去搜个临时的代理服务器用用 http://www.proxynova.com/proxy-server-list/country-cn/

原来如此，下来研究研究这块。

同意 @ethanyoung 。我觉得如果时间不够的话，可以先把一些重要的比较tricky的问题以及目前的解决思路简单写一下，这样方便像我这种小白迅速上手。如果能列一些相关的关键词，方便去网上搜索就更好了。

**Comment by O-zhang** [comment]
关注很久了，感觉发起者一直苦于服务器不稳定，正好我这里有闲置的独立服务器，配置不太高，但是带宽独享100M，如果发起者感觉适合这个项目，免费提供使用，服务很稳定，一年内应该没问题，具体私聊吧，不想在公开提供太多信息。

**Comment by zhuzhuor** [comment]
@O-zhang 非常感谢你的慷慨帮助！
100M 带宽挺多的了，我们可以尝试把之前没能代理的网站都代理看看
怎么联系你？你可以在 gitter 上私信我  https://gitter.im/zhuzhuor 直接用 GitHub 的账户登录就行

**Comment by codermango** [comment]
不太懂这方面的开发，不过一直想学习，希望能帮上忙。

**Comment by mc16888** [comment]
@zhuzhuor quick question, how can I submit pull request for new url ? 

I want to submit below new url for #502 for 回放
http://static.api.sports.letv.com/*vod?*

**Comment by tommyzhaozbh** [comment]
@mc16888 Just edit the urls.js and then submit the pull request.

**Comment by mc16888** [comment]
@tommyzhaozbh got it, thanks.
