### ISSUE TITLE
iOS PAC的问题

### ISSUE THREAD

**Issue by Dummykid** [Unblocker/Unblock-Youku#479]
是不是iphone,ipad使用PAC连接的时候,不可以通过app看电视剧?
我的LETV app就无法观看电视剧,比如 二胎时代, 但是我用浏览器登陆LETV的话,就可以直接观看,不会显示 "此节目只允许在大陆播放"的提示.

**Comment by zhuzhuor** [comment]
可能 App 访问的网络地址也许和浏览器不一样的原因
等看有人有条件测试一下看 LETV 的 app 的网络访问情况吧

**Comment by mc16888** [comment]
@zhuzhuor 我之前在 #462 里面提过要加这个地址。

http://api.mob.app.letv.com/play?tss=ios&playid=0&tm=1439605213xxxxxxxxxxxxxxxxx

**Comment by zhuzhuor** [comment]
@mc16888 谢谢！欢迎给我们提交一个 pull request

估计 `http://api.mob.app.letv.com/play*` 这样就行了

**Comment by whuhacker** [comment]
@mc16888 之前那个是提给 DNS 的，我待会加上
请问 Chrome 插件现在也不能播吗？

**Comment by whuhacker** [comment]
刚提交了，估计等 PAC 文件 CDN 全球更新还得一段时间

**Comment by zhuzhuor** [comment]
@whuhacker  想起来 PAC 用的这几个服务器是最近才弄的，还没弄 Squid 的 regex 自动更新的功能
等我这两天用之前的脚本改个吧

**Comment by mc16888** [comment]
@zhuzhuor @whuhacker 谢谢！两位辛苦了。其实我不知道 Pull request 怎么用。还有那个地址应该只适于iOS APP。Browser Extension 估计不需要。
