### ISSUE TITLE
ipad ios 8 使用url后，没有任何帮助

### ISSUE THREAD

**Issue by jimmywzm00** [Unblocker/Unblock-Youku#482]
我的ipad 是iOS8 系统。用了http://pac.uku.im/pac.pac这个url，但是没有任何帮助。任何国内的视频都不能看。同样设置，我的另一个ipad ios7 的就没问题。是不是iOS8系统的问题？还是说iOS8设置方法跟iOS7不一样？（两个ipad，都是把url填写在wif里的自动http代理）
求解答。

谢谢

**Comment by whuhacker** [comment]
与 iOS 8 没有关系，请检查你的 URL 是否填写无误。以及，每次更换 WiFi 环境，都需要重新填写。

**Comment by hihitoni** [comment]
@whuhacker 更新pac以后，app（iOS）letv任何视频会出现 ：视频暂不能播放。自己更改路由器也发生一样的情况
![image](https://cloud.githubusercontent.com/assets/5806831/9475040/12245ff4-4b5c-11e5-9f33-753c66551e99.jpg)

**Comment by hihitoni** [comment]
@whuhacker  pac 更新之前只有美剧，还有几部国内电视剧chux版权限制

**Comment by jimmywzm00** [comment]
我手打试过，粘贴复制试过，都不行。难道说，我的url地址不对？
不是http://pac.uku.im/pac.pac这个么？

**Comment by yanggis** [comment]
@jimmywzm00 你应该试试http://yo.uku.im/proxy.pac

**Comment by jimmywzm00** [comment]
@yanggis 多谢你的建议。我试了，http://yo.uku.im/proxy.pac 也不行。
无论是用网页，还是app都没法看任何bilibili和爱奇艺上只限国内浏览的视频。

**Comment by whuhacker** [comment]
@zhuzhuor 估计得看看新加的 LETV 的链接，是不是后端服务器的域名限制不允许代理？

**Comment by yanggis** [comment]
@jimmywzm00 你试试把Ipad Mini的DNS设置成104.236.189.178试试看看可以不可以。
@whuhacker 乐视域名那边应该是检测不出来你使用没有使用代理的，因为代理设置上已经不允许他们访问代理信息了。

**Comment by zhuzhuor** [comment]
@whuhacker 刚更新了后台的服务器

**Comment by jimmywzm00** [comment]
@yanggis 行了，能看bilibili了。如果不复杂的话，可以麻烦解释解释原因吗？
我之前的dns是64.59.144.18, 64.59.150.134。这是shaw cable的primary和secondary dns。
我另一个ipad ios7 的系统用的就是这个就没问题。为什么会有不同?

**Comment by whuhacker** [comment]
@hihitoni 可以再试试

**Comment by yanggis** [comment]
@jimmywzm00，具体为什么PAC文件在IOS 7上可以用，却在IOS 8上用不了我也不太清楚，不过正常情况下应该是都一样才对啊。
