### ISSUE TITLE
网易云音乐现在只能听播放列表，主界面上的播放键依然无效

### ISSUE THREAD

**Issue by fireattack** [Unblocker/Unblock-Youku#484]
用这个脚本：http://git.oschina.net/bobshi/NetEaseMusicHelper/raw/master/netease_music_helper.user.js 就可以用主界面上的播放键。

原理都是改window.GAbroad为false，不知道为什么效果有区别。

**Comment by mmxcraft** [comment]
这个没用的.刚试过

**Comment by ethanyoung** [comment]
Ubuntu 14.04 在 Australia 一直都可以。

**Comment by fireattack** [comment]
@zhuzhuor 呃，为啥close了，还是不行呀……

**Comment by zhuzhuor** [comment]
@fireattack reopen 了，这问题最近还有啥好的解决办法吗
我看到另外一个 issue 里的讨论更活跃一些，是一样的问题吗 https://github.com/Unblocker/Unblock-Youku/issues/488

**Comment by fireattack** [comment]
麻烦你了
其实之前就是看到那个issue里讨论出用一个脚本可以绕过，然后那段js加到unblock youku了
但是很快那个脚本就失效了，所以我猜开了这个issue，如果要合并的话也无妨吧

至于解决办法，我觉得似乎只有把网易云音乐全部走代理吧…好像别的没有什么特别的好的破解办法了

**Comment by zhuzhuor** [comment]
@fireattack 多谢回复，那我就保留另外一个 issue 把这个 close 了，有时间我也仔细研究下
