### ISSUE TITLE
pac里面的那些ip

### ISSUE THREAD

**Issue by carilwang** [Unblocker/Unblock-Youku#485]
我做了一个dns给一些域名重定向。但是pac里面有些是ip的，我不大清这些ip是用来做什么的? 例如123.126.99.57

**Comment by zhuzhuor** [comment]
有一些网站的某些服务用 IP 不用域名
你可以用 blame 功能来查看每一行的 change 都是源自那个 commit 的，然后看 comment 就能大致看到这个 IP 当时是为了什么而加进来的，例如 http://git.io/vGxd3
