### ISSUE TITLE
FireFox版無法使用?

### ISSUE THREAD

**Issue by kbboss7416** [Unblocker/Unblock-Youku#486]
如題，從上禮拜開始FireFox版本一直無法使用(無法使用bilibi、愛奇藝、土豆網等)，希望能儘快修復，謝謝!

**Comment by yanggis** [comment]
@kbboss7416 可能正在修复中，大神们都很忙，建议用Chrome插件，或者把电脑DNS设置成104.236.189.178临时应急，不过DNS方法一般只能在家用比较好，有些工作单位网络会对DNS近行劫持，就无效了。

**Comment by zhuzhuor** [comment]
@Unblocker/firefox @whuhacker 

@kbboss7416 Firefox addon 对所有的网站的都不行吗？
理应不会对所有的网站都失效，你试试卸载这个 firefox addon 再安装一次
另外网站无法使用的具体错误提示是什么

**Comment by kbboss7416** [comment]
bilibi的網站錯誤訊息(觀看食戟之灵 22):
「非常抱歉，本视频可能由于以下原因导致无法正常播放
视频链接失效
视频内容不和谐
UP主自主删除
侵犯他人着作权」

愛奇藝網站(觀看钻石王牌第三季 20):
「呃.....播放失败了
你知道用爱奇艺视频桌面版播放率可以少一半吗?」

土豆網(觀看Overlord 03):
「抱歉，该视频仅限中国大陆地区播放，请您观看其他视频！错误代码:Y1000」

優酷(觀看亚尔斯兰战记 04):
「抱歉，该视频仅限中国大陆地区播放，请您观看其他视频！代码:1000」

主要是這四個網站，但騰訊視頻和樂視網可以看

先謝謝各位的回應了!

**Comment by whuhacker** [comment]
@kbboss7416 感謝報告
我抽空看看

**Comment by tommyzhaozbh** [comment]
@zhuzhuor @whuhacker 经过测试，发现部分需要经过代理的链接没有response。本人测试过youku上面的running man没有问题。但是测试cache.video.qiyi.com、interface.bilibili.com，还有web-play.pplive.cn、web-play.pptv.com/crossdomain.xml等这些链接全部会返回这个结果
![capture](https://cloud.githubusercontent.com/assets/8757104/9869266/d39cd360-5bb4-11e5-8d88-550629b6caa7.PNG)
而且我没记错的话Firefox也是用pac的，加上有用户反映说手机上也用不了pac，看来要看看服务器哪里出问题了。

**Comment by zhuzhuor** [comment]
@kbboss7416 @whuhacker 这个问题还存在吗

**Comment by tommyzhaozbh** [comment]
@zhuzhuor 还是不行，打开需要代理的链接仍然提示refusing connection

**Comment by kbboss7416** [comment]
@zhuzhuor：仍然無法使用

**Comment by zhou13** [comment]
我这里开unlock youku for firefox所有的bilibili视频都返回“本视频可能由于以下原因无法播放……”

**Comment by seventhsky** [comment]
bilibili 上 unlock youku for firefox 失效很久了

**Comment by zhou13** [comment]
为啥关闭这个Issue？

**Comment by zhuzhuor** [comment]
@zhou13 这个 issue 有很长时间没有人回复了，如果问题依旧还存在的话可以 reopen 以及再 AT whuhacker

另外 Firefox 扩展相关的问题可以去这里重提下 https://github.com/whuhacker/Unblock-Youku-Firefox/issues
