### ISSUE TITLE
【hosts】DNS QQ音乐失效了？

### ISSUE THREAD

**Issue by alexking99** [Unblocker/Unblock-Youku#487]
android
我是修改hosts
192.241.222.103  3g.music.qq.com
192.241.222.103  mqqplayer.3g.qq.com
192.241.222.103  proxy.music.qq.com

失效了？出现境外限制

**Comment by yanggis** [comment]
@alexking99 前一段被攻击了，再维护，可以先把DNS替换为104.236.189.178试试，等192.241.222.103能用了再换回来。服务器受攻击比较严重，比较难维护。

**Comment by alexking99** [comment]
@yanggis 好的 感谢
