### ISSUE TITLE
请问192.241.222.103是不是down了?

### ISSUE THREAD

**Issue by yweili** [Unblocker/Unblock-Youku#489]
美东地区，android 4.4 nexus 7，bilibili解析视频地址失败有好几天了，但是看http://stats.pingdom.com/7w8lzo3be6k1 显示的状态，unblock DNS显示的是绿色？

**Comment by yanggis** [comment]
被攻击了，先用104.236.189.178作DNS，临时替换一下吧，修复了再换回来，目前Android没有太好的办法。

**Comment by yweili** [comment]
试过了，104.236.189.178同样解析错误，这个也被攻击了么？

**Comment by yanggis** [comment]
@yweili 我刚才在Android盒子和IPhone上试了，bilibili的视频都可以播啊，没你说的问题。你把dns设置成104.236.189.178后，用手机访问www.ip138.com看看显示的ip是国内的吗？手机上有没有安装其他unblock的插件或者代理之类的啊？

**Comment by tommyzhaozbh** [comment]
@yanggis @yweili 刚刚测试过两台DNS服务器都没问题。因为我是在学校测试的，学校机房有连接proxy来保护网络，如果同时改DNS的话就会出现无法连接proxy server的现象。所以建议 @yweili 检查一下你的手机和网络是否有接入proxy，否则有可能会发生代理冲突的。

**Comment by yanggis** [comment]
不要在学校和单位测试，因为现在很多学校和单位都有DNS保护，所以在这种公共场合一般是不成功的，自己家里网络一般是没有问题的，改了DNS应该就可以解锁国内视频了。

**Comment by yweili** [comment]
奇怪，我是用家里的网络，路由器刚换成easy tomato的firmware。

我一直是在安卓的wifi设置里面设定DNS的，会不会必须要在路由器上设定DNS？

**Comment by yanggis** [comment]
@yweili 有些高级的路由器有DNS缓冲，用DNS解析就会有问题。你把你的手机dns设置成104.236.189.178后，用手机访问www.ip138.com看看显示的ip是国内的不？或者在电脑上设置成dns，用命令ping一下这个网站v.youku.com或者pl.youku.com，看看返回的ip地址是什么，如果是104.236.189.178就应该没问题了。如果返回的是其他IP就说明你的dns设置有问题。

**Comment by yweili** [comment]
最后换了个路由器固件搞定了，看来还是tomato的设定有问题
