### ISSUE TITLE
Chrome Extension 转发模式现在无法使用？

### ISSUE THREAD

**Issue by xin-zhang** [Unblocker/Unblock-Youku#491]
Chrome Extension代理模式（普通模式）用的好好的没有问题。
转发模式昨今两天在家和在外面各试了一下，一直有同样的问题。所以想问问是只有我还是大家都是这样。

## 问题描述
用Chrome Extension转发模式尝试观看优酷，爱奇艺和土豆，均无法收看。土豆的错误信息显示为「对不起，该视频暂时无法播放」。
![2015-09-12 3 29 28](https://cloud.githubusercontent.com/assets/12769983/9830320/8c1e6b68-5964-11e5-9830-0dd118335954.png)

Chrome Inspector 的 Network 信息（见上图）显示，被转发到 www.yōukù.com/proxy 的 request，要么是 (cancelled)，要么是 (failed) net::ERR_CONTENT_DECODING_FAILED

用 Charles 看 Mac OS X Proxy，发到 www.yōukù.com/proxy 的 request 都会报错 Not in GZIP format（见下图）
![2015-09-12 3 29 09](https://cloud.githubusercontent.com/assets/12769983/9830335/4cbefdb0-5965-11e5-9860-96e7da9182ab.png)

用代理模式访问 http://ipservice.163.com/isFromMainland ，以及在选项中转发地址测试的地方都没有问题（见下图）
![2015-09-12 3 29 19](https://cloud.githubusercontent.com/assets/12769983/9830339/7bdf34b6-5965-11e5-818d-909c44ccc8a9.png)

![2015-09-12 3 29 40](https://cloud.githubusercontent.com/assets/12769983/9830340/8470ab96-5965-11e5-92d0-57eef210b545.png)

## 环境
OS X Yosemite 10.10.5
Chrome: 45.0.2545.85 (64-bit)
Adobe Flash Player: 18.0.0.232 (Shockwave Flash 18.0 r0)
![2015-09-12 3 30 03](https://cloud.githubusercontent.com/assets/12769983/9830349/c9bc1de8-5965-11e5-8c71-badd54ffb7fe.png)

![2015-09-12 3 29 51](https://cloud.githubusercontent.com/assets/12769983/9830350/ce959d4e-5965-11e5-9d52-bc9d5aecdacb.png)

**Comment by whuhacker** [comment]
@zhuzhuor 可能是 Heroku 或者 CloudFlare 哪里挂了……

**Comment by xin-zhang** [comment]
可是转发 http://ipservice.163.com/isFromMainland 没有问题呀。。。
该不是又是 Flash Player 的问题吧（看到了1年半以前的Issue）

**Comment by zhuzhuor** [comment]
可能是 encoding 的问题？比如 youku 返回的是 gzip 的，但是转发模式没有处理好？

**Comment by zhuzhuor** [comment]
感觉这问题还挺严重的，用上面的 link 我一直都能重现这问题

**Comment by whuhacker** [comment]
@zhuzhuor Heroku 那头是不是对请求做了什么处理？
