### ISSUE TITLE
观看部分Youku视频以及爱奇艺视频存在的问题

### ISSUE THREAD

**Issue by steven923923** [Unblocker/Unblock-Youku#492]
我是澳大利亚的，近几个月观看部分Youku视频的问题主要是广告结束之后就完全黑屏，然而其他一些Youku视频可以正常播放。在播放爱奇艺视频的时候，缓冲速度仅仅是维持在50kb/s 至 100kb/s 左右，这个问题以前从来没有出现过，我也检查过网速没有什么异常，观看土豆视频却没有类似的问题，缓冲速度可以达到带宽上限。不知开发者能否解决这个问题，非常感谢！

**Comment by tommyzhaozbh** [comment]
这跟插件无关，所有视频加载都是直接连接到服务器的。这只能说视频网站的海外CDN速度不佳，或者是分配的服务器过于繁忙。建议换个时间再加载。
