### ISSUE TITLE
PAC 无法解析ipservice.163.com 和 interface.bilibili.com

### ISSUE THREAD

**Issue by hihi427** [Unblocker/Unblock-Youku#493]
用PROXY proxy.uku.im:443 是No DNS records
用HTTPS secure.uku.im:993 ipservice.163.com ok  interface.bilibili.com Access Denied.

请拜托不要停止解析interface.bilibili.com  用些优酷源的老视频 海外无法播放 需要国内解析才能播放

**Comment by tommyzhaozbh** [comment]
pac服务器出现故障，要等他们看看哪里出问题了。

**Comment by zhuzhuor** [comment]
@hihi427 这个问题还存在吗？之前 PAC 的服务器是有点问题， @tywtyw2002 给修了下之后应该是好了

**Comment by hihi427** [comment]
试了下  没问题了   之前用@yanggis的代替了一段时间

**Comment by hihi427** [comment]
谢谢!
