### ISSUE TITLE
PAC 在iOS上面的问题

### ISSUE THREAD

**Issue by Dummykid** [Unblocker/Unblock-Youku#494]
用LETV通过PAC看节目现在很正常,但是youku视频的APP就无法看,总是显示出错.
然后我用VPN代理连接国内服务器,就可以继续观看了.
是不是youku app又更新了,所以pac被block了?

**Comment by tommyzhaozbh** [comment]
pac服务器有点故障了，得让管理员们看看

**Comment by zhuzhuor** [comment]
@Dummykid 这个问题还存在吗？之前 PAC 的服务器是有点问题， @tywtyw2002 给修了下之后就好了

**Comment by axot** [comment]
iOS上用 http://pac.uku.im/pac.pac 后
看视频连接超时

**Comment by tommyzhaozbh** [comment]
@axot 代理服务器被攻击了，详见#534
