### ISSUE TITLE
腾讯视频不能看

### ISSUE THREAD

**Issue by kclonline** [Unblocker/Unblock-Youku#495]
刚刚看腾讯视频发现不能看。
貌似是这串网址回报404
http://qzs.qq.com/tencentvideo_v1/script/hash/txv.coverplay.d4ef242b.js?v=201503200&max_age=604800
有尝试挂其他全域CN-PROXY，网页可是可以显示。
是不是要把qzs.qq.com加入清单就能看了？
谢谢

**Comment by tommyzhaozbh** [comment]
给个有问题的视频地址看看

**Comment by kclonline** [comment]
http://v.qq.com/cover/e/e7hi6lep1yc51ca.html
nslookup到qzs.qq.com返回的是a1165.b.akamai.net
IP位置在不在中國。

**Comment by tommyzhaozbh** [comment]
这个视频地址我测试了一下，第一次是可以的，然后刷新一次之后连flash播放器都不加载了。检查之后确实是这链接出问题。
你是自己搭建了代理服务器么？如果是的就试一下加这个这个(地址越精细越好，范围越小服务器压力也会越小）：http://qzs.qq.com/tecentvideo_v1/script/hash/*

**Comment by kclonline** [comment]
感谢，虽然还是不能看，先看别家视频好了(泪奔

**Comment by zhuzhuor** [comment]
上面的 close 是 merge pull request 系统自动 close 的

貌似把这个 URL 代理了治疗后，问题还存在？

**Comment by zhuzhuor** [comment]
发现把代理的范围再放大一点就好了
现在弄了 `http://qzs.qq.com/tencentvideo_v1/*`
等我更新到 Chrome Web Store 上去

不过貌似腾讯视频缓冲很慢啊，我这边就算能看，要等很久才能播放

**Comment by tommyzhaozbh** [comment]
@zhuzhuor 可能是tecent的海外CDN不是很好，我在香港这边也就是等了大概十几秒左右就能播放了。

**Comment by zhuzhuor** [comment]
@tommyzhaozbh 这样啊
多谢你的信息

**Comment by kclonline** [comment]
@zhuzhuor @tommyzhaozbh 
感谢两位，电脑上的Unblock-Youku测试可以看了。
但是路由器HOST DNS仍然不行，是因为DNS还没增加吗？
是要用qaz.qq.com指向192.241.222.103
还是用qzs.qq.com/tencentvideo_v1/*指向192.241.222.103呢？
谢谢

**Comment by tommyzhaozbh** [comment]
@kclonline Unblock DNS的规则需要手动更新，由于两边的服务器不是同步的，可能需要@whuhacker 或者其他维护人员来添加规则才行。否则你即便添加了指向规则也没有用。

**Comment by whuhacker** [comment]
@kclonline @tommyzhaozbh 
DNS 已经做出对应修改，麻烦再试试

**Comment by kclonline** [comment]
@tommyzhaozbh @whuhacker 
辛苦了，试了一下还是不行正常显示(host：qaz.qq.com 192.241.222.103)。
以为是HOST的问题，有尝试单独用DNS这台伺服器也是无法读取出来。

**Comment by tommyzhaozbh** [comment]
@kclonline 地址有没写错? 是qzs.qq.com

**Comment by kclonline** [comment]
@tommyzhaozbh 
您好，刚刚试了一下，也不确定成功与否。因为发现qzs.qq.com竟然又不影响正常播放了..。
反而手机上主力的乐视，琅琊榜跟蜀山战纪不能看了，蜀山战纪不知道为什么会显示在乐视上O_o。
但是乐视貌似只有琅琊榜不能观看(热门设暗桩？)，不过不知道安卓怎么调试，只能反馈不能观看了..。

**Comment by tommyzhaozbh** [comment]
@kclonline 这样吧，你先去下载一个tPacketCapture，然后启动并截取数据，再把截取到的记录文件发上来好让我看看哪里出了问题（我不知道这个方法行不行，毕竟我没试过）。截取到的文件可以用wireshark在电脑端打开，如果你看得懂也可以试试（其实不是很难懂，界面相对友好）

**Comment by kclonline** [comment]
@tommyzhaozbh 
错误画面截图(反馈码：0037)：
http://i.imgur.com/E12vIiR.png
tPacketCapture(乐视视频单独抓包档)：https://mega.nz/#!MtISlRzD!20RKRibIcUgk8DGxuzBFGX2e8la3daY3CgT_q1H-hnI
Wireshark也不太熟，稍微看了下。
发现这两个连接位址：
1、apple.www.letv.com
2、api.mob.app.letv.com
貌似
1、反馈画面：0037
2、这次不能播放问题点
因这两个HOST都没有加入纪录，也不知道分析方向是否正确，希望有帮助解决这个问题。

**Comment by tommyzhaozbh** [comment]
@kclonline 好的，我回头看看

**Comment by tommyzhaozbh** [comment]
@kclonline 你的抓包记录我看了一下，有一条检测链接你是没有通过代理的（编号35）
![2](https://cloud.githubusercontent.com/assets/8757104/10184890/ae7db54c-6774-11e5-9247-1324d4ce648d.PNG)

![1](https://cloud.githubusercontent.com/assets/8757104/10184880/9239fd64-6774-11e5-8e65-da084c652207.PNG)

回复是这样的
![3](https://cloud.githubusercontent.com/assets/8757104/10184906/df074dea-6774-11e5-94c6-82d041784bfe.PNG)

这条链接已经被列入代理名单的了（urls.js里面第229行），理论上应该不成问题。不知道你在机子上是使用什么方法绕开检测的？

**Comment by kclonline** [comment]
@tommyzhaozbh 
https://github.com/karlcheong/unblock_youku_privoxy_rules/blob/master/basehosts
大多用路由器设置host，原因是因为直接使用DNS有些会有解析地点分流问题。
名单以往是参考 @karlcheong 上面连结的网址清单，只是貌似许久没有更新了。
不知道方便告诉哪里可以看到最新的代理名单吗？
代理失效名单，应该与使用者地区线路有所差异，有时必须代理观看，但有时候又不需要代理观看。

**Comment by tommyzhaozbh** [comment]
@kclonline 如果直接用DNS都不行的话那可能是代理服务器没有添加这条规则了。因为我不在家里，学校的wifi只能用DHCP不能改DNS，所以要回去试试。
@whuhacker DNS有没有添加这条规则：http://api.mob.app.letv.com/play*

**Comment by whuhacker** [comment]
@kclonline @tommyzhaozbh 已更新，再试试吧

**Comment by kclonline** [comment]
@tommyzhaozbh 
谢谢，知道看视频有很多方式跟不同的视频站，只要是弄给家中两佬方便看。
@whuhacker 
辛苦您了，但是变成视频无法拨放，连接api.mob.app.letv.com回传错误403(HOST与直接用DNS相同)。
想请问一下，前阵子伺服器开始被攻击就想说自行架设(而且遇到有分流的伺服器可能有解析地点的问题)，有看到人询问DNS架设文，不知道有没有后续，已有伺服器&代理设置文，但是还没看到期待的DNS文，还是说有相关类似文章可以参考学习，谢谢。

**Comment by whuhacker** [comment]
@kclonline 错误 403 估计是中国代理那边没有加入此域名，我再看看
DNS 的文档我抽空写一下

整个链条很长，其中一个环节有一点问题就会用不到
每次有更新确实很麻烦

**Comment by paradite** [comment]
我可以确定不用unblockYouku也会出现这个问题。
```
Failed to load resource: the server responded with a status of 404 (Not Found)\ http://qzs.qq.com/tencentvideo_v1/script/hash/txv.coverplay.a4deef0f.js?v=201503200&max_age=604800
```
反而是我enable了unblockYouku之后问题就解决了。应该是ISP或者学校local proxy的问题。

**Comment by yanggis** [comment]
@paradite 如果你是在NUS或者NTU的话，用这个会有问题，其实不是UnblockYouku的问题，而是学校网络的问题。不建议用公共网络来看视频。

**Comment by yanggis** [comment]
@kclonline 私信给我你的邮箱，我发DNS教程给你。

**Comment by paradite** [comment]
@yanggis 我都已经说了**不是** UnblockYouku的问题……
UnblockYouku其实可以用来unblock学校的管制。

**Comment by tommyzhaozbh** [comment]
@paradite 不用插件肯定有问题，因为这个链接会检测ip，如果发现你不在大陆就会404，走代理就没事(就如我上面说的)，enable之后没问题是因为现在插件已经添加了代理规则，这链接会走代理，因此开了插件肯定没事。
但是插件不是万能的，我这边学校的电脑就不行，因为所有电脑全部走代理(防火墙)，装了会代理冲突，网都断了。

**Comment by paradite** [comment]
@tommyzhaozbh I see. Thanks.

**Comment by cherrot** [comment]
Google到这来的，由于我用的自己的DNS，所以遇到了相同的问题导致腾讯视频无法播放，原因应该是 qzs.qq.com 的DNS配置有问题（我尽力找一下鹅厂的朋友报下bug），加Host或者让qzs.qq.com走国内通用的DNS服务器就行了。

**Comment by rpsh** [comment]
大家好，腾讯视频在海外节点解析 qzs.qq.com 出现 404 的问题解决了。各位同学可以再试试看。

P.S. 缓冲慢的同学，建议登录帐号后试试是否缓冲速度有提升

**Comment by paradite** [comment]
@rpsh Thanks.

**Comment by zhuzhuor** [comment]
@cherrot @rpsh 感谢腾讯的朋友来帮忙解决问题！
