### ISSUE TITLE
土豆某些视频显示仅限大陆地区播放

### ISSUE THREAD

**Issue by zhuzhuor** [Unblocker/Unblock-Youku#497]
用户在 google group 里面反馈的，我试了一下还真是
有问题的视频地址 http://www.tudou.com/listplay/poA03IPkaCs.html
我试了下别的动漫视频，貌似还都正常

![screen shot 2015-09-21 at 8 02 57 pm](https://cloud.githubusercontent.com/assets/928905/10010207/8a5d7f32-609c-11e5-9e23-d3127a040a67.png)

用户的反馈原帖 https://groups.google.com/forum/#!topic/unblock-youku/A_yshXaIN7o

**Comment by jasonyeo94** [comment]
精简模式没问题，发生在普通模式一些影片~running man这些节目能正常播看~

**Comment by zhuzhuor** [comment]
已经上传到 Chrome Web Store 了，请等待自动更新

**Comment by tommyzhaozbh** [comment]
@zhuzhuor 还是不行，地址错了。发现新地址了。
![1](https://cloud.githubusercontent.com/assets/8757104/10067990/6eff15b4-62d3-11e5-91d6-3aaa4f4cbeff.PNG)
![2](https://cloud.githubusercontent.com/assets/8757104/10067989/6ef84e82-62d3-11e5-9940-8016d2a1aed2.PNG)
走代理的话是这样的
![3](https://cloud.githubusercontent.com/assets/8757104/10068018/96fbc2f6-62d3-11e5-9047-0f546f5e49ee.PNG)

**Comment by tommyzhaozbh** [comment]
不对啊，好像插件是整个域名都走代理的。可能是土豆把代理服务器的ip列入黑名单了，要不得做点什么修改？

**Comment by zhuzhuor** [comment]
@tommyzhaozbh 真的写的是 `IP is forbidden` 额...

**Comment by zhuzhuor** [comment]
好像把 `v2.tudou.com` 从代理列表中去掉就好了，但是还需要多测测

**Comment by zhuzhuor** [comment]
最新的去掉 `v2.tudou.com` 的 v2.8.0.6 版刚上传到 Chrome Web Store 了
我刚才试了一些，都没问题了。如果还有问题的话欢迎再来反馈
