### ISSUE TITLE
在google group发现的问题链接

### ISSUE THREAD

**Issue by tommyzhaozbh** [Unblocker/Unblock-Youku#501]
刚才把google group里头的所有帖子统统回复了一遍，大半都是说土豆CP1006的问题，个别就是美剧。但还有两条无解：
http://www.tudou.com/albumplay/uzAbsl_Pcb8/up_dWciB8sg.html
这个我没法搞懂究竟是被下架了还是真的代理出了问题，大家帮忙测试一下……
http://www.tudou.com/programs/view/PRrWMX07JBI/
这条总是回复DP1000，检查发现视频服务器的crossdomain.xml全部故障，可能是服务器哪里出了问题……（但偶尔可以）

**Comment by tommyzhaozbh** [comment]
@zhuzhuor 另外求工具上google，回去大陆上不来gmail烦得要命……

**Comment by yanggis** [comment]
@tommyzhaozbh  告诉我你的邮箱，我发fan墙工具给你。

**Comment by tommyzhaozbh** [comment]
@yanggis tommyzhao1993@gmail.com 感谢了

**Comment by hihitoni** [comment]
@yanggis 你的dns服务器是建立在digitalocean吗？可以给个简单的的DNS服务器的教材吗？ 邮箱zhou_485@hotmail.com

**Comment by hihitoni** [comment]
@yanggis 谢谢

**Comment by yanggis** [comment]
@hihitoni 已经发邮件给你了。

**Comment by mc16888** [comment]
@yanggis DNS服务器的教材方便的话可以发给我吗？谢谢。邮箱 mc16888@outlook.com

**Comment by yanggis** [comment]
@mc16888 已经发给你了。请查收。

**Comment by mc16888** [comment]
@yanggis 收到，谢谢 ！！

**Comment by zhuzhuor** [comment]
@tommyzhaozbh 我也发了代理服务器信息给你，不确定是不是还能用，你试试看

**Comment by cch2508** [comment]
@yanggis 我也想在自己家开个DNS服务器，能给我发个教程吗？谢谢！x@jianhao.im

**Comment by tommyzhaozbh** [comment]
@yanggis 同求DNS教程，感谢了~~邮箱在上面
@zhuzhuor 还是先谢谢了，回头试试

**Comment by yanggis** [comment]
@tommyzhaozbh , @cch2508 邮件已发，请查收。

**Comment by zhuzhuor** [comment]
@tommyzhaozbh 回复你一楼的问题，关于两个 tudou 的 links
第一个视频应该是 tudou 在国内也不能播放了，浏览器整个用了代理也不行
第二个的确是播不了，看到有个奇怪的裸 IP 请求，给代理了就好了

**Comment by zhuzhuor** [comment]
最新的 v2.8.0.7 应该修复了第二个链接的问题
最新版也上传到 Chrome Web Store

**Comment by ywiris** [comment]
您好我想请问一下 为什么最近QQ音乐用proxy码都听不了了？ 希望解答一下 谢谢 是不是永久不能用了？
