### ISSUE TITLE
乐视体育（iOS版）无法unblock

### ISSUE THREAD

**Issue by hi2008** [Unblocker/Unblock-Youku#502]
乐视体育 LeSports（iOS版，版本1.0.0，更新2015年9月29日）无法unblock，使用DNS和PAC文件都不行，希望大神给看看，看直播的利器啊，乐视网络速度也快。加拿大温哥华iOS9.0.1

**Comment by mc16888** [comment]
@hi2008 用 @yanggis 提供的DNS 104.236.189.178 可以看直播，用192.241.222.103的话就不行，可能后台服务器出问题了，因为验证的URL没变还是这一个 http://live.gslb.letv.com/gslb?*，如果用PAC的话，我发现 app 会直连，完全忽视PAC的规则。

回放的话，有新的验证URL http://static.api.sports.letv.com/*vod?*

**Comment by hi2008** [comment]
@mc16888 谢谢，用104这个DNS可以看到直播，缓冲的时间很长，回放的确看不了。192那个还是不行，用ip138看还是加拿大的IP。

**Comment by tommyzhaozbh** [comment]
@whuhacker 看看2楼，处理一下DNS的问题

**Comment by zhuzhuor** [comment]
pull request 里有 `fix #issue` 这样的，merge 了之后会自动把 `#issue` close 了
