### ISSUE TITLE
bilibili ios客户端没法看新番；虾米，网易云音乐网页版上不去

### ISSUE THREAD

**Issue by JimAmuro** [Unblocker/Unblock-Youku#504]
RT.
chrome插件上不去虾米和网易云
手机IOS9 加pac看不了新番
前两天都能用的，求大神解决。。

**Comment by DONUTEATER** [comment]
同求大神解决 不能用虾米下载简直要命！还有土豆龙八夷！

**Comment by tommyzhaozbh** [comment]
虾米无解，详见#381 要用的话只能开会员……
手头上没有ios设备，这要等其他高手过来了。

**Comment by DONUTEATER** [comment]
我有会员 但是也不能下载啊

**Comment by yanggis** [comment]
@JimAmuro， @DONUTEATER， 把DNS设成104.236.189.178试试呢？不要在单位或者学校测试，这些地方有防火墙和反代理设置，最好在家用宽带上测试。

**Comment by DONUTEATER** [comment]
@yanggis 好像还是不行呢

**Comment by yanggis** [comment]
@DONUTEATER,修改DNS之后，访问www.ip138.com，显示的你现在的IP是在国内吗？如果不是在国内，就是你的网络有问题，代理没有起作用。

**Comment by DONUTEATER** [comment]
@yanggis  显示本地局域网是国内的意思？如果是 那就是在国内的

**Comment by yanggis** [comment]
那就说明没有代理成功，你可能在单位或者学校，用的公共网络，不防火墙不允许你用代理。

**Comment by JimAmuro** [comment]
@yanggis 我改DNS后可以b站看番了 这次没开PAC 但是ip显示还是在美国 而且虾米还是上不去

**Comment by tommyzhaozbh** [comment]
Ip显示国外的话证明你的代理不算成功，另外虾米无解，除非开会员或者全局国内代理，否则目前的所有方法(包括DNS、插件、pac等等)都不起作用。

**Comment by yanggis** [comment]
@JimAmuro 能看番剧说明代理有作用，IP限制是因为这几天ip138.com的ip探测有问题，可能不太准。关键还是看你能不能unblock，能unblock就说明代理起了作用。
虾米音乐确实暂时无解，呵呵。

**Comment by mc16888** [comment]
昨天發現網頁版 xiami 已經不需要全局代理

試聽的 URL
www.xiami.com/play?xxxxxxxxxxxxxxx

下載的話,需要付費. 因為我支付寶沒錢,所以只試了下載的第一步,不清楚之後有沒有其他URL也需要代理,所以pull request 只加試聽的URL

下載URL的第一步
www.xiami.com/download/pay?xxxxxxxxxxxxxxxxxx

**Comment by zhuzhuor** [comment]
@mc16888 试听指的是？是在线听全曲吗？

**Comment by mc16888** [comment]
@zhuzhuor Yes. 是在线听全曲.
