### ISSUE TITLE
为什么qq音乐近一个月来都听不了呀？

### ISSUE THREAD

**Issue by ywiris** [Unblocker/Unblock-Youku#507]
求大神指点 谢谢啦 是不是永久不能用proxy码了？

**Comment by tommyzhaozbh** [comment]
请问你使用的代理方式是?

**Comment by ywiris** [comment]
用proxy码 用iPhone听qq音乐 这个情况已经持续一个月了 我在佛州 我朋友在堪萨斯他说情况和我一样也用不了。谢谢您的回复～

发自我的 iPhone

**Comment by tommyzhaozbh** [comment]
你的意思是修改pac?我手头上没有ios设备，可能要找@zhuzhuor 去测试一下。但是最近pac问题挺多的，建议你试试建议你试试换DNS

**Comment by ywiris** [comment]
哦 是这样呀 DNS有具体的设置步骤么 ios设备也都可以用吗？ 多谢啦

发自我的 iPhone

**Comment by zhuzhuor** [comment]
@tommyzhaozbh 我最近也有点忙估计没有时间看 PAC 的这个问题，另外我 iOS 的 App Store 现在遇到个[尴尬的事情](https://discussions.apple.com/thread/7105186)，暂时不能安装新的 apps

希望有条件的人能帮我们 debug 一下 iOS 上的问题

**Comment by mc16888** [comment]
Just test it with http://pac.uku.im/pac.pac on iOS 9.0.2 iPhone 6, QQ music ver 5.6, no problem.

ps. I am in Hong Kong

**Comment by ywiris** [comment]
哦 是这样呀 好遗憾呢 希望有人可以来帮助解决一下 哪怕让所有的用户付费也好～希望大家可以支持一下

发自我的 iPhone

**Comment by Migflyway** [comment]
qq音乐可以直接买绿钻会员，亲测可用。

**Comment by ywiris** [comment]
真的可以么 我虽然没买绿钻但是之前也一直可以用 现在试听所有歌都要登陆 然后继续登陆就显示链接超时 

发自我的 iPhone

**Comment by ywiris** [comment]
是的 我试了一下 可以用 还得买什么音乐包 谢谢大家的回复了

发自我的 iPhone

**Comment by ywiris** [comment]
您好 上次我买了qq音乐会员暂时可以用了 最近用pac码怎么又登录不进去qq音乐呀？优酷也经常出现问题 pac码去年都一直很稳定 今年是什么问题呢？

发自我的 iPhone

**Comment by tommyzhaozbh** [comment]
pac服务器今年夏天受到攻击之后就一直不是很稳定，部分需要代理的链接出现拒绝连接的现象。因此最好不要使用。
建议使用unblock DNS进行代理，但这个DNS不是很稳定，偶尔间会出现服务器死机的现象。方法是在wifi设置中打开单个wifi的设置页面，在DNS一栏改为192.241.222.103，或者改为@yanggis 的104.236.189.178，这个会更加稳定一些。

**Comment by ywiris** [comment]
嗯 谢谢了 有些人啊乱攻击什么服务器呀真是的……

发自我的 iPhone

**Comment by benhong** [comment]
是是看這個 pac 
https://goo.gl/b6Jj8N

**Comment by ywiris** [comment]
您好 这个是什么呀 为什么打不开呢 显示的是个微信的图标文字是aliyun.pac？

发自我的 iPhone

**Comment by benhong** [comment]
因為我給的是google 短網址
真正的網址在這
https://sites.google.com/site/emset306/aliyun.pac?attredirects=0&d=1

其實這份pac 也是根據 Unblock-Youku 的pac 做修改的
只不過代理伺服器 是我自己的

下載回來用 notepad.exe 看看不就知道 是不是了

**Comment by ben237829624** [comment]
QQ音乐又不行了,虽然uku.im/check 返回的是true,但还是会提示我不是中国大陆.

**Comment by ywiris** [comment]
对啊一直时好时坏的 而且前两天试了下绿钻 居然付费方式是apple 账户 是美元 交了以后也没用 😭😭😭

发自我的 iPhone

**Comment by benhong** [comment]
我刚刚修正了
我的pac , http://pac.emset.xyz
测试了，是可以用的，至少我可以用辣

**Comment by ywiris** [comment]
嗯嗯 太感谢了 我之前那个pac用不了好久了。

发自我的 iPhone

**Comment by ben237829624** [comment]
谢谢。我刚买了个阿里云服务器，会试试用你的PAC按照教程尝试一下

**Comment by ben237829624** [comment]
@benhong 你好，我刚刚搭建了自己的服务器，但是为什么我的QQ音乐虽然能正常听，但并不能正常加红心，下载和分享呢？我用uku.im/check是true的. 我想请教一下这有可能是pac问题吗?谢谢

**Comment by ben237829624** [comment]
@benhong 我刚刚在Mac上测试了一下,发现可以点红心.

**Comment by benhong** [comment]
@ben237829624  你的服務器 架設是參考站內的嗎，如果是的話 那你可能還要加上
            "acc.music.qq.com" : [/^\/base\/.*\/getsession/i],
            "182.254.116.117": [/^\//i],

請自行轉換成你使用的程式格式

基本上PAC 的設定後 伺服器端也要根據pac的設定開放白名單
要不然資料轉到server 後 server 不給代理也是白搭

**Comment by ben237829624** [comment]
是的。请问一下伺服器的白名单是在哪个文件里面呢？

**Comment by benhong** [comment]
不好意思我不知道你是根據哪一份文件，架的server ，
請提供一下，讓我知道你是用哪一套軟體
這樣我才可以跟你說 要去哪邊設定

**Comment by ben237829624** [comment]
我是根据美团云的教程，用的是centos 7 squid。
谢谢

**Comment by benhong** [comment]
在server 里的
/opt/crx_url_list.txt 加上

^http:\/\/acc.music.qq.com\/base\/fcgi\-bin\/getsession.*$
^http:\/\/182.254.116.117\/.*$

**Comment by ben237829624** [comment]
谢谢！
