### ISSUE TITLE
本地加URI regex - Access Denied

### ISSUE THREAD

**Issue by sh1n0b1** [Unblocker/Unblock-Youku#510]
貌似服务器不允许本地加URI([#118](https://github.com/Unblocker/Unblock-Youku/issues/188) 和 [#254](https://github.com/Unblocker/Unblock-Youku/pull/254))

![xunlei](https://i.imgur.com/QT9ZT1u.png)

**Comment by zhuzhuor** [comment]
@sh1n0b1 已经不行了，现在的代理服务器有白名单防止 abuse
