### ISSUE TITLE
DNS还是不能用，寻求机顶盒最终解决方法。

### ISSUE THREAD

**Issue by sxiang518** [Unblocker/Unblock-Youku#511]
有安卓的盒子，系统本身不支持pac很麻烦。之前都是用dns，但现在192.241.222.103非常不稳定。另外一位仁兄提供的自创dns也不是非常稳定。尝试使用drony, 但每次失败。ios/pc端目前都没有太大问题，难道机顶盒要变砖头了？目前有几个想法。我觉得dns可以做成收费private类型的，或者开发安卓平台上的app。

**Comment by yanggis** [comment]
你这个想法不现实，DNS收费并不能保证稳定，或者说收费和稳定没有直接关系，192.241.222.103我没有测试，不知道是不是稳定，104.236.189.178这个肯定是稳定的。哪个视频看不了我可以给你解答。
Android上面单独开发APP也不现实，再开发无非也就是类似Drony或者Droidproxy，现有的这些软件都很难保证稳定，另起炉灶再搞一套一样会面临同样的问题。

**Comment by sxiang518** [comment]
@yanggis 你好，104.236.189.178刚才出现了长时间卡顿，也是一天之中偶尔会出现的情况。对了目前芒果tv的app看不了，其他都可以

**Comment by yanggis** [comment]
@sxiang518,卡顿这个真和DNS没有太大关系，DNS的作用仅仅是unblock，只有成功和不成功，成功了你就可以观看，不成功你就看不了。因为它仅仅是获得一个授权可以播放的json请求而已。卡顿多数是网络的问题。正常情况下服务器是稳定运行的，现在是每小时200人在线，压力不大。服务器会在北京时间凌晨4点钟自动维护，unblock的服务器会停1-2分钟，其他时间基本不会出现宕机的问题。
芒果TV的问题我已经解决了，可以再测试看看，如果有问题欢迎再反馈。

**Comment by benhong** [comment]
我個人是這樣做，找一台router ,並且你有能力修改，且router可以修改
可以用市面上ASUS 或小米 或DLINK 然後刷機成  DD-WRT
要不然用一台電腦開一個VM架router 也可以
我個人是使用自家做的router ,

然後將找 Privoxy 的原始碼，自己build
放到router 內運作，之後將
設定以下指令開機執行
iptables -t nat -A PREROUTING -i br0 -p tcp --dport 80 -j REDIRECT --to-port 8118
其中  br0 是wan port ,  8118 是Privoxy  開的port

這樣一來只要這台router 底下配的dhcp ip 將都會自動翻牆了

Privoxy  的confing 檔我可給你

**Comment by jsyu** [comment]
哪位大神能给个自己能架设DNS服务器的教程？公共DNS延迟有点高，想自己搞一个。

**Comment by whuhacker** [comment]
@jsyu 如果你有需求我可以帮你架设一个， Skype me

**Comment by sxiang518** [comment]
今天两个dns都不能用，东部时间10:11am。哪怕机顶盒上不需要dns看的风行乐视都看不了。

**Comment by yanggis** [comment]
@sxiang518 刚试过104.236.189.178,工作正常。你看什么视频不能看啊？我测试一下。

**Comment by sxiang518** [comment]
@yanggis 机顶盒上面pptv youku 土豆 乐视都不行。难道机顶盒不行，电脑上就ok？

**Comment by yanggis** [comment]
我用的也是机顶盒，优酷，乐视都没问题，可以正常播放。你没把你自己的电脑的DNS设置成104.236.189.178试试吗？如果电脑可以用，就是你盒子本身的问题，而不是DNS服务器的问题。

**Comment by yanggis** [comment]
国内停电，104.236.189.178 DNS服务器的解析服务可能要暂停几个小时，来电应该会自动回复，不便之处敬请谅解。

**Comment by yanggis** [comment]
已经恢复了。

**Comment by yanggis** [comment]
最近发现有人开始恶意用Unblock的DNS服务器恶意访问国内的视频和音乐网站，比如95.222.30.138（德国IP）利用代理访问搜狐视频那个IP验证的link，平均一个小时访问次数10000多次，纯粹是恶意消耗服务器资源；223.16.126.243香港IP，恶意利用代理做爬虫工具抓取QQ音乐，也是一个小时10000次以上，几乎达到服务器的相应极限了。建议在服务器上安装Squid分析工具，或者其他可以检测单个IP访问量的工具，发现一个立刻drop掉这个IP的请求包，免得无谓的消耗代理服务器的资源。

**Comment by sxiang518** [comment]
根据目前论坛的反应情况，pc/mac端的问题不大，机顶盒一直rely on DNS。我自己的机顶盒不支持root，drony用也有问题。 今天拿到手小米盒子，root后测试proxydroid.

**Comment by yanggis** [comment]
@sxiang518 麻烦测试完proxydroid给个反馈情况。

**Comment by sxiang518** [comment]
小米盒子已root， 但是使用proxydroid显示错误或不支持的pac文件，使用drony显示findurl not defiend. 是我操作问题还是机子本身的问题。

发自我的 iPhone

**Comment by yanggis** [comment]
就Android系统而言，DNS解析是最简单稳定的方法，没有之一了。proxydroid和Drony虽然能用，但是稳定性一直是一大诟病，proxydroid虽然说是支持PAC文件，事实上是不支持的，所以你设置了也没用。proxydroid的代理功能虽然稳定，但是速度慢，不能达到看视频需要的网速，所以用proxydroid不是个好办法。

**Comment by sxiang518** [comment]
安卓如果能像ios一样直接支持pac，海外机顶盒的问题就完全解决了。目前用电脑连接电视，或者smarttv看youtube都是不错的选择。

发自我的 iPhone

**Comment by zhuzhuor** [comment]
@yanggis 如果你想迁移到稳定点的服务器的话，我可以给你个美团云的 VPS

**Comment by yanggis** [comment]
@zhuzhuor，谢谢，现在服务器还算稳定，等我有需要了再联系你哈，谢谢了。
