### ISSUE TITLE
有关acfun乐视源视频的问题

### ISSUE THREAD

**Issue by tommyzhaozbh** [Unblocker/Unblock-Youku#512]
原文链接：https://groups.google.com/forum/#!topic/unblock-youku/IAhQ1Fg03UI

有人反映在acfun上面的乐视源视频没法观看，经常返回481，但本人测试却全部没有问题。不知道是乐视出了问题还是acfun出了问题……

**Comment by yanggis** [comment]
乐视视频这一段在抽风，原来VST全聚合和电视猫的聚合类软件已经把乐视视频源全部下架了。

**Comment by mc16888** [comment]
可能和这个有关
http://bc.tech-ex.com/2015/ottanalysis/67713.html

**Comment by zanderzhng** [comment]
我测试了下，日本IP无法看ACFUN的乐视源，韩国美国可以。
