### ISSUE TITLE
请教Raspberry pi2的性能能否支撑建立一个自用的Unblock-Youku服务器？

### ISSUE THREAD

**Issue by esme518** [Unblocker/Unblock-Youku#513]
现在基本上在国外生活，为了能在手机上看bilibili和网易云音乐。

我的打算是这样的
在国内扔一个Raspberry pi 2（或类似的低成本的设备）在上面假设Unblock-Youku服务器
在国外现有nas设备 设置与国内服务器连接，并建立vpn服务器

这样的话即使手机也只要连接到vpn服务器就能在不影响国外服务例如twitter等的情况下 同时享受国内的服务
现在想问的就是Raspberry pi2的性能能否支撑建立一个自用的Unblock-Youku服务器？ 或者大家有没有更好的解决方案 如果有相关的教程的话就太感谢了

**Comment by esme518** [comment]
而且由于 无论是准备放在国内的Raspberry pi 还是国外现有的nas都是私有服务器 也可以更方便的进行安全管理

**Comment by yanggis** [comment]
最关键的是你在国内要有公网IP，没有公网IP一切都不可能……

**Comment by reilee** [comment]
@esme518 自用的话性能应该足够了，问题是管理。如果国内没有帮手的话，物理层的问题只能肉身翻回墙内。相比之下还是找个靠谱的云主机方便。

**Comment by benhong** [comment]
我的经验vpn 这条路行不太通
我在阿里云 美团云 使用过vpn 一阵子
后来就完完全全不能使用了
原因不明呀

手机端我是这样做，用家里（主机在台湾唷）的router 架vpn
手机端连线vpn ，vpn 只推送 pac 档给手机，所以全部的流量都不会经过vpn
但是只能使用在ios 的作业系统上

除非你在国内有人帮你管理 Raspberry pi 要不然
某种原因挂了，可能就是你头透的时候了

建议你可以用阿里云，选青岛一个月也才27快，流量费用另计
但是我流量的费用我一个人使用，永远扣不到

阿里云有推出学生方案一个月9快钱，只不过不知道你是否符合

更便宜的方法乖乖的使用 unblock-Youku pac档

**Comment by zanderzhng** [comment]
没有公网IP可以用DDNS。

**Comment by yanggis** [comment]
@zanderzhng 有固定的公网IP，最方便；没有固定的公网IP 才需要DDNS，如果连不固定的公网IP都没有，要DDNS能干什么？就是你知道IP，那是个内网IP，你在国外也访问不了。

**Comment by karlcheong** [comment]
我的RASPBERRYPI一代 架設了一堆服務(nginx/privoxy/dnsmasq/samba/ssh/softether/shadowsocks/h@h)
性能都沒有多大問題(當然,同時使用人數很少,只有幾個人)
最大如上面所說，萬一上網modem／路由／raspberry當機了沒人管就動不了

沒有公網ip也能用vpn方式以國內的電腦做client連接到國外帶有公網ip的服務器。
然後設置國內電腦做數據轉發。

當然，這樣很麻煩。

**Comment by zhuzhuor** [comment]
@karlcheong 很长一段时间都没见到你了  :smile: 最近忙吗?
