### ISSUE TITLE
 Unblock-Youku support for safari

### ISSUE THREAD

**Issue by zhexuany** [Unblocker/Unblock-Youku#514]
I was wondering is that possible we start to support safari? I hardly know js but willing learn and figure it out.

**Comment by zhexuany** [comment]
@zhuzhuor What is your opinion?

**Comment by zanderzhng** [comment]
safari's extension api doesn't support modifying headers.

**Comment by zhuzhuor** [comment]
@zhexuany It's all based on whether we have volunteers to develop the Safari extension. I am mainly responsible for the Chrome extension (don't have spare time for others), and @whuhacker developed the Firefox extension based on the Chrome one. If you have time and are willing to learn, you are welcome to try to make one for Safari.
BTW, You can use [the PAC file](http://uku.im/proxy) as a starting point for your new project (which was exactly what the Firefox extension did at the beginning).

**Comment by whuhacker** [comment]
@zhuzhuor I checked it before and I‘m afraid PAC is hard to work with Safari, since Safari uses the system PAC setting and the extension have insufficient privilege to modify that setting.

Anyway it is limited by the API that Safari provided. Need to further reading their documentation.

**Comment by zhexuany** [comment]
I am totally wiling to learn and develop safari version.
