### ISSUE TITLE
对chrome extension界面的一些建议

### ISSUE THREAD

**Issue by tommyzhaozbh** [Unblocker/Unblock-Youku#517]
![qq](https://cloud.githubusercontent.com/assets/8757104/10780132/2cbb679a-7d75-11e5-8857-4fafccd78ebc.png)
这个是现在的插件界面，但是欠缺了一点就是FAQ的入口，结果大家一旦有问题连FAQ都不看就直接跑来Google Groups。我觉得如果让大家先看了FAQ我就不需要花那么多时间去回答一些本来就已经有答案的问题（例如“受版权限制不能播放”与“仅限中国大陆播放”），因此我建议把contact us先改为check here并导向至FAQ的页面，并且在FAQ的页面的最后才加上Google Groups的反馈地址。
另外，FAQ那里也已经很久没有更新了，因此我建议：
1. 开头新增一句“如果你在使用插件出现任何问题，请先在这里找找有没有答案”
2. FAQ的第五点把土豆网改为优酷或土豆，因为有不少网友反馈优酷也有这种现象
3. 新增一条“安装插件之后，所有影片都看不了”，曾经有网友反馈说所有视频都看不了，但关闭插件之后倒是可以了（https://groups.google.com/forum/?hl=zh-CN#!topic/unblock-youku/cmQBJEGzySc ） 里面的回答应该可以作为参考。
@zhuzhuor

**Comment by whuhacker** [comment]
最下面两句太长，直接改成 **FAQ** 和 **Contact Us** 好了

**Comment by zhuzhuor** [comment]
@tommyzhaozbh 太感谢你在 google groups 里面给大家解决问题
你的建议挺好的，我之前用 wufoo 表格的时候就是先让用户看 FAQ 再提问来着，这样能减少很多提问

我在想把主要的几个 FAQ 直接写在 groups 最上面的 header 那里（现在那里也只有一个 FAQ 的 link）

**Comment by zhuzhuor** [comment]
我工作日一般比较忙，没有什么时间来写这个
我把 wiki 的编辑权限打开了，欢迎大家来添加新的，删除旧的 FAQ http://uku.im/faq

我给你了 google group 的管理员权限，你看看你能修改 group 上面的介绍文字吗

**Comment by tommyzhaozbh** [comment]
@zhuzhuor Google Groups的权限我已经看到了，welcome message的文字我也略作修改。不过插件的代码我不是很会改，如果像我说的那样改动的话那看FAQ的人应该会多不少的。
