### ISSUE TITLE
bilibili似乎可以只需修改X-Forwarded-For与Client-IP即可实现海外观看

### ISSUE THREAD

**Issue by gaosong2101** [Unblocker/Unblock-Youku#519]
不知道我是不是火星了，火星的话就请 Close 吧。

我在使用Unblock Youku Pac的时候发现这个脚本会代理interface.bilibili.com这个网址。
然而我发现，针对bilibili，只需要修改 www.bilibili.com/video/av* 及 interface.bilibili.com/playurl* 的 Client-IP 和 X-Forwarded-For 成一个国内的 IP ，无需代理也可顺利对正版视频进行解析，而且会将视频地址解析到ws.acgvideo.com（海外服务器），速度比使用代理解析到 cn-*.acgvideo.com 的国内服务器相对来说会更快一些，而且也同时一定程度减少了Unblock Youku 的服务器压力。

一点建设性意见，以上~

**Comment by hihi427** [comment]
确实没错 看版权header就够了  但是有些老优酷源视频 如果interface 走海外服务器会解析不到视频 直接就黑电视了   而且ws速度不稳定 cc还不错基本满速   很多视频没有cc第视频地址     但最全的还是国内服务器  怎么也能找到视频  关于b站的问题欢迎到我帖子讨论http://tieba.baidu.com/p/4026132806?pn=1

**Comment by gaosong2101** [comment]
Re @hihi427 
不知道哪些优酷的视频会黑屏，我这里似乎暂时没有遇到（比如说http://www.bilibili.com/video/av693218/），进interface里面看解析到的是ws。

我这里（南澳州）主要是访问国内不稳定，有些视频通过国内服务器加载需要很长时间（尤其是视频大小250MB+的），有些则很流畅，原因不明；而用ws则没有这个问题

**Comment by hihi427** [comment]
比如我帖子里做测试用的这个视频 http://www.bilibili.com/video/av1411257/
北美 不让interface.bilibili.com/playurl*走国内代理  就是黑电视

**Comment by gaosong2101** [comment]
Re @hihi427 
+1，的确看不了
这个好像的确有些奇怪有些时候，不同地区情况有异吧；解析失败返回的结果是<result>error</result>，如果Unblock Youku能判断这个也能好些（不知能否实现）
ws这个我暂时还没遇到不好的情况，不知道它这个ws指的是什么，cc那个也不知道是什么…
总之，感谢解释啦

PS：怎么感觉此post变身求助帖了…（划掉

**Comment by gaosong2101** [comment]
再PS：但是如果海外党代理interface会有个问题，就是有些视频会很卡（估计是解析到的b站服务器的问题），若不代理interface则就没有这个问题，比如说http://www.bilibili.com/video/av3162827/

**Comment by zhuzhuor** [comment]
多谢反馈！
