### ISSUE TITLE
[Chrome] 乐视无法播放了.

### ISSUE THREAD

**Issue by Dummykid** [Unblocker/Unblock-Youku#520]
美国时间,昨天还可以看,今天看乐视就不行了,3个模式都试过,不能看.

比如这个http://www.letv.com/ptv/vplay/23938479.html
显示 很抱歉,您的网络连接出现异常,或者运营商网络服务鼓掌.

**Comment by Dummykid** [comment]
琅琊榜 也看不到了.
http://www.letv.com/ptv/vplay/23573764.html?htime=1890

**Comment by zhuzhuor** [comment]
我这里试了下也是这样，去掉代理就好了
详细情况还得再研究研究

**Comment by zhuzhuor** [comment]
LETV 的类似这样的链接
`http://api.letv.com/mms/out/video/playJson?id=23938479&platid=1&splatid=101&format=1&tkey=-1811104623&domain=www.letv.com&dvtype=1300&accessyx=1`

经过我们的代理服务器会返回 status code 213...
不用代理或者用别的代理服务器就没有问题，会正常返回 json 内容

这是 LETV 把我们代理服务器的 IP 封了吗
如果真是这样就没什么意思了，我建议我们可以把 letv 的这 url 从代理里去掉了

cc: @whuhacker @tommyzhaozbh @yanggis

**Comment by whuhacker** [comment]
我这里返回正常

```
{
    playstatus: {
        status: 0,
        stime: 1446787515
    },
    statuscode: 1003
}
```

Maybe 需要切换一个国内代理 IP……
如果去除没有影响，那应该可以去除的

**Comment by zhuzhuor** [comment]
@whuhacker 现在那服务器不是很好换 IP，除非折腾让不同的 URL 走不同的代理服务器
去除了不确定有没有问题

但是如果这次是 LETV 专门和我们作对的话就没有意思了（注意那个 status code）， 就算我们换了新的 IP 估计也会照样有问题

**Comment by whuhacker** [comment]
```
$ curl -x http://proxy.uku.im:443 "http://api.letv.com/mms/out/video/playJson?id=23938479&platid=1&splatid=101&format=1&tkey=-1811104623&domain=www.letv.com&dvtype=1300&accessyx=1"
{"playstatus":{"status":0,"stime":1446788192},"statuscode":1003}

$ curl -x https://secure.uku.im:993 "http://api.letv.com/mms/out/video/playJson?id=23938479&platid=1&splatid=101&format=1&tkey=-1811104623&domain=www.letv.com&dvtype=1300&accessyx=1"
curl: (52) Empty reply from server
```

@zhuzhuor HTTPS 代理服务配置没问题？

**Comment by yanggis** [comment]
@zhuzhuor 也不一定是你的那个IP被blocked了，观察两天看看，LETV自己的网络也经常抽风。目前104.236.189.178的DNS解析暂时没受到影响，乐视视频可以正常看。

**Comment by tommyzhaozbh** [comment]
现在我在学校，因为学校不允许用代理，所以我用转发模式。但转发模式里头是没有任何问题的。

**Comment by Dummykid** [comment]
今天又可以看了,估计乐视网站抽风了.

**Comment by zhuzhuor** [comment]
@Dummykid 多谢反馈！我试了下，的确又都能看了
那这个 issue 就先 close 了
