### ISSUE TITLE
有一个问题，chrome web store里有一个名为unblock youku pro的apps，这是你们新推出的项目吗？

### ISSUE THREAD

**Issue by O-zhang** [Unblocker/Unblock-Youku#521]
十月份由ribeku.com新推出，貌似安装后没有任何作用，而且移除还需要在chrome://apps里删除，普通用户可能找不到，感觉是有人在故意误导新用户。

**Comment by zhuzhuor** [comment]
@O-zhang 感谢你的信息
这不是我们的 app，欢迎在 Chrome Web Store 举报

1. 访问链接 https://chrome.google.com/webstore/report/kmkfhfggebhpdhbcomfhgdnophjcbfcn?hl=en-US&gl=US
2. 然后选择 Other，填写一些简单的理由例如 `It uses a similar name as the popular extension "Unblock Youku", which confuses users.`

**Comment by hihi427** [comment]
举报了

**Comment by zhuzhuor** [comment]
@hihi427 感谢！
