### ISSUE TITLE
DNS方法无法观看芒果TV

### ISSUE THREAD

**Issue by jasperzs** [Unblocker/Unblock-Youku#523]
我想麻烦问下, 我用的是海美迪芒果嗨Q M3型号的机顶盒...  这两天用了我们的DNS服务器104.236.189.178和192.241.222.103都无法观看芒果TV, 全部显示"非大陆用户无法观看"..  各位大神这该如何解决啊??

**Comment by yanggis** [comment]
其他的优酷，搜狐和腾讯视频可以看吗？芒果TV他们那个验证服务器有时候会抽风down掉，不过刚才我看了一下这会是好的，你应该可以看啊。

**Comment by jasperzs** [comment]
我的芒果tv是海美迪电视盒子自带的 然后播放爸爸去哪了综艺节目总不行 显示非大陆无法观看

Sincerely,
Jasper Zhao

**Comment by yanggis** [comment]
抱歉，没有海美迪的盒子，没法调试破解它自带的芒果TV。你可以先把你的DNS设置成8.8.8.8,然后在盒子自带的浏览器里访问http://www.ip.cn/，看看你的IP是多少，记下了告诉我。然后把你的DNS设置成104.236.189.178，打开芒果TV，找那些显示非大陆无法观看的节目，比如爸爸去哪儿，多翻几期，让它多显示“非大陆无法观看”。操作完发信息给我，然后我可以调试一下服务器就应该知道该unblock的是哪个链接了。

**Comment by yanggis** [comment]
另外，你确定芒果TV是提示的“非大陆用户无法观看”吗？爸爸去哪儿在芒果TV里是VIP节目，必须是VIP付费会员才能看，否则就是unblock了，你不是付费会员一样看不了。

**Comment by jasperzs** [comment]
你好 我刚试啦 点了一共8期爸爸去哪儿都是非大陆用户无法观看....  我的IP是99.232.83.48 ~    海美迪公司跟芒果台有合作, 所以海美迪的电视盒上的芒果TV里的所有节目都是没有VIP限制的~   我之前试过FLYVPN的免费账号的确是可以观看爸爸去哪儿的所有过往期的, 但是我现在用咱们的DNS服务器就没法观看, 所以我估摸着还是unblock的时候出错了....   希望您能帮忙修复一下 :)

**Comment by yanggis** [comment]
@jasperzs 您好，我改了一下服务器，您再试设置104.236.189.178看看能不能unblock芒果TV。

**Comment by jasperzs** [comment]
@yanggis 您好，我刚又测试了一下，还是不能unblock芒果tv。

**Comment by yanggis** [comment]
@jasperzs，您好，可以用github在线聊天功能和我联系，咱俩在线交流吧，这样的话沟通比较方便，调试会更容易。

**Comment by jasperzs** [comment]
@yanggis 您好...  我没找到github如何在线聊天啊....   能用facebook或者qq在线聊天么??  微信的话也可以啊

**Comment by yanggis** [comment]
https://gitter.im/yanggis 就能看到我了。

**Comment by yanggis** [comment]
@zhuzhuor 可以在另外一个DNS服务器上也加这一条链interface.url.hifuntv.com，这个是海美迪公司针对海美迪的盒子设置的一个IP验证，导致海美迪盒子上的芒果TV在海外被限制。

**Comment by whuhacker** [comment]
@yanggis DNS 已加。不过 forward 到国内的代理还没加（not maintained by me），所以现在还没起作用。

**Comment by jasperzs** [comment]
@zhuzhuor 谢谢您第一时间就修改了另外一个DNS服务器，不过我要向谁反应才能让forward到国内的代理也加上海美迪的ip验证服务器地址从而使得192.241.222.103也能成功unblock海美迪的芒果tv呢？

**Comment by ghui1012** [comment]
各位大神有谁能帮忙教下海外怎样unblock海美迪的芒果tv呢？

**Comment by yanggis** [comment]
你说的芒果TV是海美迪自带的软件吧？那个没有海美迪的盒子测试不了。

**Comment by jasperzs** [comment]
设置一下DNS服务器就可以了


Sincerely,


[http://i65.tinypic.com/v7591c.png]

On Sep 4, 2016, at 12:58 AM, X.K. YANG <notifications@github.com<mailto:notifications@github.com>> wrote:


你说的芒果TV是海美迪自带的软件吧？那个没有海美迪的盒子测试不了。

―
