### ISSUE TITLE
希望pac和DNS增加云视听泰捷视频

### ISSUE THREAD

**Issue by hihitoni** [Unblocker/Unblock-Youku#524]
android盒子的泰捷视频更新版本为云视听泰捷视频 希望增加UNLOCK
vv.play.aiseet.atianqi.com/getvinfo
bkvv.play.aiseet.atianqi.com/getvinfo

**Comment by yanggis** [comment]
vv.play.aiseet.atianqi.com 
bkvv.play.aiseet.atianqi.com
这两个在104.246.189.178的DNS服务器上已经添加上了，欢迎测试，有问题请及时反馈。
