### ISSUE TITLE
一个奇怪的问题

### ISSUE THREAD

**Issue by tommyzhaozbh** [Unblocker/Unblock-Youku#525]
有人反馈下面的这个连接在精简模式和转发模式会出现版权问题，但普通模式连接不上。普通模式我测试过没有问题（料想是对方的网络问题），但另外两个模式确实有问题。谁能帮忙看看？
http://www.tudou.com/albumplay/0ooe9ORrppg/fsxmVJB0AvU.html

**Comment by Migflyway** [comment]
普通模式可以看

**Comment by Migflyway** [comment]
其他模式提醒版权问题

**Comment by zhuzhuor** [comment]
土豆这个这个网页的 html 部分也通过了代理，见[源码](https://github.com/Unblocker/Unblock-Youku/blob/461c8036dcaa73347ad457c5d3addc252ed7ae99/shared/urls.js#L151)
只有普通模式才会这样，转发和精简模式因在技术上暂时做不到
回头可能能想出来新的更有效的办法来解决这个问题
