### ISSUE TITLE
Dns 和 pac 已经对bilibili失效了吗 ?

### ISSUE THREAD

**Issue by checkyi** [Unblocker/Unblock-Youku#527]
只有b站不好使。
已经持续一周了。

Android (galaxy s5)
德国

**Comment by checkyi** [comment]
尝试过的Dns 和 pac:
Dns:
- 104.236.189.178
- 192.241.222.103
pac:
-http://pac.uku.im/proxy.pac
-http://pac.uku.im/pac.pac
-http://yo.uku.im/proxy.pac
-http://dns.umbridges2014.com/proxy.pac

**Comment by freeyoung** [comment]
你说的不好使是新番仍然显示被封锁么？

**Comment by zhuzhuor** [comment]
@yanggis @whuhacker

**Comment by yanggis** [comment]
@zhuzhuor 这个现在已经改了一下DNS服务器，应该没有问题了。
@checkyi，有问题的话，欢迎再反馈。

**Comment by mc16888** [comment]
@yanggis 请问是不是要加 interface.bilibili.com，我昨天用fiddler去debug，apps 好像没连这个URL，但是用Router去抓包， apps 好像有连这个URL的ip。

**Comment by yanggis** [comment]
@mc16888 好像不是的， interface.bilibili.com这个原来就有的，原来就靠这一个链接就可以unblock了，现在有一验证是加在www.bilibili.com/。。里面了。所以我就直接www.bilibili.com这个链加到unblock里走代理了。

**Comment by yanggis** [comment]
@mc16888 你可以再详细追踪一下看看是不是这样。

**Comment by mc16888** [comment]
@yanggis 谢谢，今天晚上有时间再研究一下。

**Comment by checkyi** [comment]
@yanggis 多谢, 已经好用了 😊
