### ISSUE TITLE
优酷已经封Unblock-youku了?

### ISSUE THREAD

**Issue by Dummykid** [Unblocker/Unblock-Youku#530]
今天发现优酷封IP手段越来越厉害了.
比如这个片子:
http://www.youku.com/show_page/id_z652e012c3e1b11e4b432.html?from=y1.12-96
猛龙特囧.
我用google chrome连接,显示只能播放预告片.
然后我用stealth VPN连接到国内服务器,就显示可以播放正片电影,而不是显示播放预告片.
我同时也测试了一下其他的片子,很多都这样.如果不连接到国内服务器,我都是显示播放预告片.
但是vpn连接到国内服务器后,就显示可以播放正版片源.
是不是youku已经把unblock youku给封杀了?
要这么下去,以后letv,iqiyi都可以把unblock youku给封了啊.

**Comment by yanggis** [comment]
这个很早就发现了，你把www.youku.com/show_page这条链加到代理里面就好了。

**Comment by Dummykid** [comment]
unblock youku怎么加这个连接?
我的vpn代理加不了啊,只是一个付费软件.不能自己修改,

**Comment by zhuzhuor** [comment]
@yanggis 是说需要把 html 页面也整个经过代理吗? /show_page 还在别的地方用到吗？
现在我们用了别人捐赠的一个代理服务器，服务器带宽还有些剩余。如果可行的话，欢迎提交个 pull request，我们可以试试代理这 /show_page

**Comment by yanggis** [comment]
@zhuzhuor，是代理这个/show_page的link,其实我测试了一下，直接代理www.youku.com就可以了。因为代理服务器有自动缓存机制，尽管www.youku.com这个网页的内容很大，但是大家请求的内容都是几乎是一样的，所以真正需要代理实时youku请求的东西并不错，90%都是重复调用缓存的。所以你要偷懒的话，就直接代理www.youku.com这个link就可以了。

**Comment by zhuzhuor** [comment]
感觉这问题还挺严重的，刚试了几个了优酷的视频，连链接都打不开
等服务器稳定了，可以考虑试试代理下 html 页面

**Comment by zmwangx** [comment]
> 感觉这问题还挺严重的，刚试了几个了优酷的视频，连链接都打不开

Yeah this is really bad. For some pages (say http://v.youku.com/v_show/id_XMTQ0MjMxNzgwOA==.html?from=y1.7-2) the body tags opens with `var accessStatus = false;`, followed by a self-executing anonymous function that does a bunch of crap then this:

```js
if(accessStatus == false && href.indexOf('?x') === -1 && href.indexOf('&x') === -1){
	window.location.href = "http://localhost/index/y404/";
}
```

I tried to write an extension to override this but apparently I don't even have time to inject anything... (Is it possible to somehow execute `const accessStatus = true` before `<body>` is even parsed? I don't know, but everything I tried failed.)

**Comment by zhuzhuor** [comment]
@zmwangx Thanks for the finding!
Could you try always redirecting the url to append a `?x` or `&x` to avoid the href change?

**Comment by zhuzhuor** [comment]
@zmwangx 
Appending a `#?x` works. For example, `http://v.youku.com/v_show/id_XMTQ0MzQ1NTkwNA==.html#?x`.
But the page I tried was still blank (the flash player wouldn't show up).

> ![screen shot 2016-01-12 at 9 06 14 pm](https://cloud.githubusercontent.com/assets/928905/12285590/94d12428-b970-11e5-8515-53e5144ff414.png)

**Comment by whuhacker** [comment]
Privoxy's content filter function works perfectly in this situation.

**Comment by zmwangx** [comment]
> But the page I tried was still blank (the flash player wouldn't show up).

Yep, I can confirm. Actually, if you look the [HTML returned](https://gist.github.com/anonymous/b8d684ec5c0411a76a3a) for a blocked video, it doesn't even contain the videoID; where as a non-blocked one will contain a blob like

```js
<script type="text/javascript">
var youku_video_page = 1;	var page_v5 = 1;var removePlayerSideControl = 1;
var player_thx = 1; 
var singerid = '0';
var videoId = '360684115';
var videoId2= 'XMTQ0MjczNjQ2MA==';
var version="/v1.0.1124";
var imgServer = 'http://static.youku.com';
var UC_FOLLOW_HOST = "i.youku.com";
var video_owner = '819720317';
var tags="%E8%A7%82%E5%A4%8D%E5%98%9F%E5%98%9F|";
var showid="303110";
var showid_en="04ed35e2988a11e5be16";
var showtype="正片";
var cp="authorized";
var stage="7";
var playmode="3";
var videoSeconds = Math.round(1953.00);
...
<script>
```

No wonder the player won't load.

**Comment by yzliao** [comment]
刚刚试了几个视频，都可以打开

**Comment by dushi792** [comment]
@yzliao 我试了下貌似还是有问题，主要就是正版新番都打不开

**Comment by xkk** [comment]
现在我开youku 很多都直接404
普通模式下
比如这个
http://v.youku.com/v_show/id_XOTI1MzM4Mzg0.html?from=y1.3-movie-index2-1105-10229.90991-90823.2-1

**Comment by yanggis** [comment]
@xkk  用104的DNS看好像没问题哦。

**Comment by zhuzhuor** [comment]
已经把 youku 的 html 页面加在代理列表里了，等新版的更新吧，看看服务器的效果

**Comment by zmwangx** [comment]
:+1: Updated to 2.9.0.3. Works now.

**Comment by zhuzhuor** [comment]
@zmwangx 多谢反馈！
