### ISSUE TITLE
代理服务器又遭到 DDoS 攻击

### ISSUE THREAD

**Issue by zhuzhuor** [Unblocker/Unblock-Youku#534]
最新的服务器状态可以从 http://status.uku.im/ 查看

我们的主服务器有 DDoS 防护，情况能好一点，但是也陆续有点短时间的 offline
PAC 的服务器比较弱，可能 offline 的时间会长一些

> ![screen shot 2015-12-05 at 2 45 15 am](https://cloud.githubusercontent.com/assets/928905/11607434/0d789c4c-9afb-11e5-88db-4969158750bc.png)

其实几天就有一次小的 DDoS 攻击，可能是他们用来测试测试？

> ![screen shot 2015-12-05 at 2 45 39 am](https://cloud.githubusercontent.com/assets/928905/11607435/0d8b6516-9afb-11e5-9a68-ca0623d426e6.png)

**Comment by gaosong2101** [comment]
加油……

**Comment by tommyzhaozbh** [comment]
两台主服务器都没有太大问题，毕竟现在的抗攻击能力增强了不少。而pac服务器也有cloudfare的保护，恢复过来应该也是时间问题，不过我检查了一下pac文件还是可以正常下载的。
PS：能设置IP地区限制么？

**Comment by Migflyway** [comment]
http://bbs.feng.com/read-htm-tid-9899079.html

今天读到的一个帖子，老大们去看看。 呵呵了

**Comment by fiveinches** [comment]
请问ios的pac是一直没法使用么

**Comment by yanggis** [comment]
@tommyzhaozbh,服务器上可以设置地域限制的，网上有那个中国IP数据库，把来自中国大陆的IP都屏蔽掉就OK了。

**Comment by hafa2012** [comment]
pac的服务器一直被攻击吗？怎么破?
