### ISSUE TITLE
对腾讯视频无效

### ISSUE THREAD

**Issue by qwwwpp** [Unblocker/Unblock-Youku#535]
这几天突然就对腾讯视频无效了

**Comment by tommyzhaozbh** [comment]
昨天我还试过有效呢。请提供视频链接

**Comment by qwwwpp** [comment]
http://v.qq.com/cover/3/3aul3xfpcu7i17d.html?vid=i0019sbvyo6

**Comment by tommyzhaozbh** [comment]
毫无问题可言……你按F12点击network然后刷新一次页面，把有问题的（红色的那些）都截图过来（要点击查看详情）
![qq](https://cloud.githubusercontent.com/assets/8757104/11620376/40b8f450-9ced-11e5-8dda-28878bab6853.png)

**Comment by qwwwpp** [comment]
我这次随便打开了一个视频，同样不行：http://v.qq.com/cover/b/bf3m4hscytxj1ty.html?vid=a0019lhrwd5
这是所有有问题的
![2015-12-07 10 04 29](https://cloud.githubusercontent.com/assets/11554486/11630159/24626a48-9cca-11e5-87f3-2cc37d0f7524.png)
Preview 都一样：
![2015-12-07 10 04 49](https://cloud.githubusercontent.com/assets/11554486/11630158/24620f1c-9cca-11e5-85a9-011084c52f42.png)
Header 有四种：
![2015-12-07 10 05 10](https://cloud.githubusercontent.com/assets/11554486/11630157/24617c96-9cca-11e5-9d1b-d0bc35a59ecc.png)
![2015-12-07 10 07 39](https://cloud.githubusercontent.com/assets/11554486/11630288/bdbe4194-9cca-11e5-963d-b5310ffb721f.png)
![2015-12-07 10 07 22](https://cloud.githubusercontent.com/assets/11554486/11630221/6564b19a-9cca-11e5-8581-ba2236345ac8.png)
![2015-12-07 10 07 31](https://cloud.githubusercontent.com/assets/11554486/11630220/655e406c-9cca-11e5-9880-012294c84289.png)

**Comment by tommyzhaozbh** [comment]
一片红的我还是第一次见呢……连http错误代码都没有返回的话那有可能DNS解析出问题了。换一个DNS试试。

**Comment by zhuzhuor** [comment]
@qwwwpp 你这问题还存在吗？

我这刚试了没有问题了
![screen shot 2016-01-08 at 11 09 55 pm](https://cloud.githubusercontent.com/assets/928905/12214971/044315a8-b65d-11e5-8b12-72c10716806f.png)
