### ISSUE TITLE
有人能帮忙测试一下？

### ISSUE THREAD

**Issue by tommyzhaozbh** [Unblocker/Unblock-Youku#536]
关于QQ音乐ios的，之前我测试过在pac模式下部分歌曲如果不开通会员的话连试听都不行（正常收费下载的歌曲试听是不用收费的，但这里还包括一些不收费的歌曲）。但是在安卓使用没有问题。我手头没有ios设备，有没有人测试一下？最好要测试一下那些收费的歌曲……

**Comment by oliverhuhan** [comment]
iOS 表示现在是会员部分歌都不能听了，即使是在 pac 模式下，转 apple music 吧，唉唉...

**Comment by mc16888** [comment]
Just test it with with my own pac server using QQ music ios app ver 5.8 on my iphone 6, they change the request url from http://acc.music.qq.com/base/fcgi-bin/getsession to use real ip address like this http://220.249.243.70/base/fcgi-bin/getsession, but that ip address will change from time to time, so far I have seen following ips
220.249.243.70
103.7.31.186
14.18.245.250

So if you have your own pac/proxy server, try add this to your pac file and proxy white list see you can unblock

Pac file
    any: [/^[^/]*\/base\/fcgi-bin\/getsession/i],

Proxy whitelist
    ^http:\/\/[^/]*\/base\/fcgi-bin\/getsession.*$

**Comment by tommyzhaozbh** [comment]
@mc16888 Great. So can you send a pull request to change the pac file and the while list?

**Comment by mc16888** [comment]
@tommyzhaozbh pull request submitted.

**Comment by tommyzhaozbh** [comment]
@yanggis Same problem occurred in qq music android 5.8. Please fix it.

**Comment by yanggis** [comment]
@tommyzhaozbh, Noted. However, the new verification is ip-based; I currently have no good idea to solve it using DNS unblocking.

**Comment by zhuzhuor** [comment]
为了安全 + 服务器不被 abuse，之前这个 URL 规则被删了 https://github.com/Unblocker/Unblock-Youku/commit/ba4137e5a073cf991a32e5e0e09c1dac27d1f9e9
最好还是给域名或者 IP 地址白名单吧

@mc16888 Have you seen any other IPs? Maybe we can put these IPs into the URL list for now.

**Comment by mc16888** [comment]
@zhuzhuor 試一下把已下8個IP加入白名單看行不行. 這8個IP是用 www.17ce.com 去解析 acc.music.qq.com 得出來的.

220.249.243.70
117.185.116.152
101.227.139.217
59.37.96.220 	
140.207.69.99 	
103.7.31.186 	
103.7.30.89 	
182.254.34.151

**Comment by zhuzhuor** [comment]
@mc16888 多谢！

@tommyzhaozbh 正在准备添加这些 IP 进来

**Comment by zhuzhuor** [comment]
有人后来还测试过这个吗？现在可以正常使用了吗

**Comment by tommyzhaozbh** [comment]
这个测试过，已经解决

**Comment by zhuzhuor** [comment]
@tommyzhaozbh 多谢！这个 issue 就 close 了
