### ISSUE TITLE
DNSmasq更新问题

### ISSUE THREAD

**Issue by Hza100** [Unblocker/Unblock-Youku#538]
可以维护一下这个dnsmasq文件吗？https://github.com/karlcheong/unblock_youku_privoxy_rules/blob/master/basehosts
貌似已经好久好久未更新了。。 这种方式用在路由器上真的很方便，希望有大神可以把以上文件更新一下，把目前所支持的网址都列出来。

不胜感谢！！

**Comment by tommyzhaozbh** [comment]
其实不看那个也可以的…在这边的源码里面，shared/urls.js就是需要代理的地址。格式按照ip+domain 就可以了。

**Comment by Hza100** [comment]
@tommyzhaozbh 好的谢谢。。请问那个文件里的所有网址都要添加吗？如果要全面里面那些灰色的ip地址也需要加上？所有地址都是对应104.236.189.178这个服务器的？

**Comment by tommyzhaozbh** [comment]
不用全部添加，只需要添加你自己需要的就可以了，毕竟你不是所有的网站都用得上…104的那个服务器貌似代理的地址要多一点，因为我发现192.241那个对视频客户端不起作用
