### ISSUE TITLE
unblock youku 和哔哩哔哩助手产生冲突

### ISSUE THREAD

**Issue by oliverhuhan** [Unblocker/Unblock-Youku#539]
虽然没有问题不影响使用，但是哔哩哔哩助手那边说是 unblock youku 这边可以做适当调整使两者兼容（https://github.com/zacyu/bilibili-helper/issues/63），两个这么好的插件大家都不希望你们在 chrome 里面产生冲突，unblock 这边可否适当增加以下兼容性更新？

**Comment by yoonhakcher** [comment]
![pfghf](https://cloud.githubusercontent.com/assets/10570103/11767327/1ab938be-a1ed-11e5-9b3c-3adf6f36e87b.PNG)

**Comment by tommyzhaozbh** [comment]
这个问题两边的作者讨论过，但最终不了了之……

**Comment by ThriftShopper** [comment]
![screenshot_2015-12-15-00-59-46](https://cloud.githubusercontent.com/assets/16282413/11787554/415fb3dc-a2c7-11e5-886b-b5c4b73abd7d.png)

您好，原本我用Android平板经Drony看bilibili没问题。但是最近都连不上，连http://ipservice.163.com/isFromMainland
却跑出上图的错误讯息，请问我是设定错误吗？
还是pac伺服器仍有问题？

**Comment by zhuzhuor** [comment]
@oliverhuhan @yoonhakcher 之前讨论的内容在这里 https://github.com/Unblocker/Unblock-Youku/pull/505 最后感觉也没得到一个 conclusion
