### ISSUE TITLE
你们的【酷我】能用吗？

### ISSUE THREAD

**Issue by Cyrus-Wong** [Unblocker/Unblock-Youku#540]
我的前两天还能用，今天发现不能了。尝试更换去unblock dns，在这边的open 和 closed 的帖子找到了两三个unblock dns，尝试观看qq视频，能看，但是酷我还是一样不能。请大神帮帮忙~

**Comment by tommyzhaozbh** [comment]
我们这边暂时没有添加酷我客户端的……
