### ISSUE TITLE
DNS和Proxy對 ios QQ音樂的問題

### ISSUE THREAD

**Issue by kevinsio** [Unblocker/Unblock-Youku#541]
Proxy依然是無法使用, DNS是192.241.222.103無法使用, 104.236.189.178那個對樂視有效, 用ip138.com查看IP也是中國, 但QQ音樂就是用不了
客户端是iPhone 6, 地點是澳門

請問為甚麼會這樣?

**Comment by tommyzhaozbh** [comment]
QQ音乐的检测方式发生改变，稍后需要更改代理规则。
