### ISSUE TITLE
DNS出问题了么？

### ISSUE THREAD

**Issue by tommyzhaozbh** [Unblocker/Unblock-Youku#544]
今天想看片，电脑打开爱奇艺客户端打不开视频，经常报错。截取连接数据发现@yanggis 的DNS没有正常回复get请求。测试过QQ音乐电脑版连音乐馆都没法正常显示。难道服务器被炸了？
![qq](https://cloud.githubusercontent.com/assets/8757104/11843235/6d2299b2-a443-11e5-94de-80388087f348.png)

**Comment by yanggis** [comment]
@tommyzhaozbh，嗯，我也发现有点问题，在排查ing

**Comment by yanggis** [comment]
现在应该可以了。

**Comment by tommyzhaozbh** [comment]
还是不行，服务器依旧没有回应，没有任何http回应……

**Comment by Xiangshen-Meng** [comment]
貌似好几天了，求大神看看

**Comment by yanggis** [comment]
@tommyzhaozbh, @Xiangshen-Meng 现在还不可以吗？我这边测试没问题呀。

**Comment by yanggis** [comment]
@tommyzhaozbh,测试一下你那边可以不可以。

**Comment by tommyzhaozbh** [comment]
现在可以了

**Comment by Xiangshen-Meng** [comment]
我是在mac设置的dns server。
https://gyazo.com/41e3d5d495ce37629ebf7cef21719adc
现在访问网易音乐还是有问题。
https://gyazo.com/98b550d78562c4b20c918b34681ced40
是不是我的设置有问题啊，请教:sweat_smile:

**Comment by tommyzhaozbh** [comment]
@Xiangshen-Meng 额，你用192这个DNS……这个DNS是有点问题，得叫人修复才行。@yanggis 负责的DNS是104.236.189.178，换一个试试。另外网易云音乐目前无论是DNS还是插件都无法解决问题的，要找解决方法看#488 (文章很长，往后面看）
PS：github可以直接传图的……

**Comment by Xiangshen-Meng** [comment]
@tommyzhaozbh @yanggis 太感谢了！！！104.236.189.178这个OK，我用的网易音乐mac app，设置了dns就OK了。太感谢了！！
顺便请教下，可用DNS现在有列表什么的吗？
下次我试试传图:smile:

**Comment by tommyzhaozbh** [comment]
@Xiangshen-Meng 就只有这两个可用
@yanggis 但现在有个问题，就是爱奇艺客户端会没得在客户端播视频也不能下载，之前是可以的。现在播放都会跳转到网页版……

**Comment by Hza100** [comment]
@yanggis 可以把所有104.236.189.178支持的网址做一个dnsmasq列表出来吗？方便路由器使用。。感谢！

**Comment by li0001** [comment]
原来是192这个dns有问题啊，用了好久192这个dns希望能早日修好

**Comment by yanggis** [comment]
@Hza100, 抱歉，我没有用dnsmasq，不知道该怎么做dnsmasq列表，我用的Bind9……

**Comment by yanggis** [comment]
@tommyzhaozbh 你说的爱奇艺不能在客户端播放吗，我刚才测试了一下可以啊。

**Comment by yanggis** [comment]
@tommyzhaozbh你那里有没有安装CIBN搜狐视频呢，能用VPN或者代理之类的软件测试一下看看可以正常运行吗？如果可以的话准备也Unblock一下这个软件的。如果稳定性很差的话，就不准备添加这个软件的支持了。我这边用代理和VPNCIBN搜狐视频这个软件都不能正常运行，怀疑是软件本身有问题。

**Comment by tommyzhaozbh** [comment]
@yanggis 忘记说这是安卓客户端了……爱奇艺有一条链接需要经过代理的，否则的话点击任何一个连接都会跳转到网页播放。正常来说“立即观看”按钮隔壁应该还有个下载按钮的，但现在没了……
![845451527579417329](https://cloud.githubusercontent.com/assets/8757104/11896998/88c93fd4-a5c6-11e5-9f30-f8962d472b9a.jpg)
抓包之后发现这条连接会检查：
![1](https://cloud.githubusercontent.com/assets/8757104/11897040/fab9d798-a5c6-11e5-8599-4a774cfe2d47.png)
我测试了一下，如果使用代理，在回复中的click_event不会跳转至网页，否则的话回复会有一句“为您跳转至网站播放”。
另外这里还有个file是关于下载问题的（我发现如果不经过代理的话就会出现无法下载的问题），但是我没看出端倪来，不知道是哪个用来检查下载的……

**Comment by yanggis** [comment]
@tommyzhaozbh iface.iqiyi.com这个已经在代理里面了啊。

**Comment by tommyzhaozbh** [comment]
@yanggis 额……没事了。原来是我路由器重置了之后手机忘了重新设置了……

**Comment by lvduo** [comment]
我在host 列表里加了这个
104.236.189.178 music.163.com ##云音乐可以用了

**Comment by Hza100** [comment]
@yanggis 只是希望可以把104.235.189.178支持的所有网址都列出来。。 这样通过dnsmasq 就不要需把104用作primary dns来解析所有网站了。。
