### ISSUE TITLE
请问firefox安卓版新使用方法

### ISSUE THREAD

**Issue by peterd1601** [Unblocker/Unblock-Youku#549]
之前是参考网路上的方式: 
利用找到“network.proxy.autoconfig_url”，填入http://yo.uku.im/proxy.pac
找“network.proxy.type”，數值改為2
但最近发现无法看爱奇艺了…请问有新的设定方法吗…? 谢谢

**Comment by yanggis** [comment]
Android的就修改DNS吧，相对容易方便点。

**Comment by peterd1601** [comment]
感谢您的回答~想请问有具体的教程可供参考吗(会不会影响原先使用呢?)…不好意思自己对这方面不太熟悉…之前就是一直照那個网路方法进行操作的…恳请指点(>_<)

**Comment by yanggis** [comment]
按这个教程修改DNS bbs.25pp.com/thread-143987-1-1.html
教程里是修改为8.8.8.8或者8.8.4.4的，你把DNS设置成104.236.189.178，另外一个空着就好了，国内的视频应该就可以看了。办公场合不允许使用代理的地方这个方法无效。

**Comment by peterd1601** [comment]
了解, 感谢您我再试试看, 但请问每次看完有需要回复初始设定吗? 还是不去更动也不会有所影响呢~?

**Comment by yanggis** [comment]
设置完了就不用理它了。

**Comment by peterd1601** [comment]
了解~感謝您的协助^^
