### ISSUE TITLE
请问android电视盒如何使用unblock youku?

### ISSUE THREAD

**Issue by whmsysu** [Unblocker/Unblock-Youku#550]
入手了一个android 电视盒子，请问一下现在可以用unblock youku吗？具体教程在哪里？请各位高手指教。

**Comment by yanggis** [comment]
按这个教程修改DNS，看这个帖子 bbs.25pp.com/thread-143987-1-1.html
教程里是修改为8.8.8.8或者8.8.4.4的，你把DNS设置成104.236.189.178，另外一个空着就好了，国内的视频应该就可以看了。办公场合不允许使用代理的地方这个方法无效。

**Comment by whmsysu** [comment]
可以了，多谢了。
