### ISSUE TITLE
 虾米音乐网 一直无法成功

### ISSUE THREAD

**Issue by likueimo** [Unblocker/Unblock-Youku#551]
不好意思打扰
虾米音乐网
www.xiami.com
一直无法成功连上
有什么替代方案吗
谢谢大家！

**Comment by tommyzhaozbh** [comment]
很抱歉，由于虾米特殊的检测方式，除了vpn外就没有替代方案了，唯一的方法就是开通会员。

**Comment by likueimo** [comment]
好的 谢谢你们
提供一下我手机上方法
把网路关掉打开虾米的app
再打开网路就可以听歌了
虽然只限手机
但勉强可用
谢谢你们
