### ISSUE TITLE
初来乍到，请问大神，怎么看爱奇艺优酷。

### ISSUE THREAD

**Issue by naxiaomei** [Unblocker/Unblock-Youku#552]
之前只需要在wifi感叹号 然后 自动 黏贴 http://yo.uku.im/proxy.pac 这个就可以了。请问现在应该怎么改？什么都考不了…跪求…告诉怎么做。麻烦。谢谢。

**Comment by naxiaomei** [comment]
忘记说了，是用苹果手机或者ipad。

**Comment by cyblocker** [comment]
http://youku.im/proxy.pac

少两个点，试试看？

**Comment by zhuzhuor** [comment]
最新的地址是  `http://pac.uku.im/pac.pac`
