### ISSUE TITLE
关于教程“在美团云架设自己的 Unblock Youku 代理服务器”

### ISSUE THREAD

**Issue by hafa2012** [Unblocker/Unblock-Youku#554]
版主好！
只想把这个服务器给自己用，而不想公布，要怎么设置？
另外请问如何得到指向自己unblock服务器pac的url？

**Comment by tommyzhaozbh** [comment]
其实如果你不对外公布IP的话谁都不知道你有这么一个服务器……当然如果你说IP限制的话这兴许有，但这个我不懂，要其他人来答。
而至于pac的使用，可以看看#453 回帖中间的部分有提到。

**Comment by wtjfree** [comment]
你如果公开ip.谁又会知道呢?设置在wiki里面有的.我也准备搞一个.就内部成员使用.

**Comment by zhuzhuor** [comment]
@hafa2012 
这比较尴尬，PAC 代理的模式不支持用户验证
Squid 白名单弄好的话应该问题不大
如果访问者的 IP 比较固定的话，可以用 iptables 来限制只允许特定的 IP 来访问

**Comment by hafa2012** [comment]
版主和热心会员们，我按照教程如法炮制了一个美团云的服务器，
请问如何检查自己服务器状态？用什么命令？
谢谢
