### ISSUE TITLE
大神啊，好奇你的盈利模式是怎样的？

### ISSUE THREAD

**Issue by liukangau** [Unblocker/Unblock-Youku#555]
每天这么的流量，你还不收费。
为什么呢？

**Comment by tommyzhaozbh** [comment]
这个你不用担心，首先我们的vps不是按流量计算的，而是按带宽计算的(如果按流量计算的话一旦被攻击那恐怕要破产了)。再者，由于有好心人的帮助，我们有一台100M的服务器~

**Comment by zhuzhuor** [comment]
@liukangau 现在是完全不盈利
代码都是开源的。后台的服务器有热心网友捐赠的一台，还有我自己购买的几个小的
