### ISSUE TITLE
Pac server好像已经罢工一个月以上了！

### ISSUE THREAD

**Issue by hafa2012** [Unblocker/Unblock-Youku#556]
Pac server好像已经罢工一个月以上了
![2015-12-31_145316](https://cloud.githubusercontent.com/assets/5762924/12060961/507c7238-afce-11e5-828c-3e6cf2a82ded.png)

大神出来解决一下吧！

还有192.241.222.103这个server也年久失修，sohu都无法解锁了！

**Comment by tommyzhaozbh** [comment]
Pac不要紧，有cloudfare的话你永远都能用得到。不信你用浏览器打开是可以的~
至于192的DNS，这恐怕得负责人上来才行~

**Comment by hafa2012** [comment]
就是说pac proxy server现在工作正常，是吗？

什么是cloudfare？和pac proxy server什么关系.

thanks

**Comment by yanggis** [comment]
192.241.222.103这个服务器应该是国内的代理工作不正常了，导致无法解锁，现在暂时只能用104.236.189.178做DNS。

**Comment by tommyzhaozbh** [comment]
Pac服务器有可能真的出问题了(因为之前被炸过又没修复)。但是有cloudfare的话，即便服务器瘫痪了你还是能正常下载使用pac。
Cloudfare是一个国外的网络防护品牌，其部署在全球的服务器可以帮用户抵挡包括DDOS在内的各种网络攻击。即便服务器因被攻击而瘫痪，他的CDN可以替代原服务器的功能(有点类似电脑备份)。你现在访问pac其实是访问CDN而不是原服务器。

**Comment by zhuzhuor** [comment]
重新弄了个 PAC 的服务器，从美团云迁出来了

**Comment by hafa2012** [comment]
地址没变？

**Comment by zhuzhuor** [comment]
还是直接用 `http://pac.uku.im/pac.pac` 就可以了
