### ISSUE TITLE
谁能帮忙测试一下腾讯直播

### ISSUE THREAD

**Issue by tommyzhaozbh** [Unblocker/Unblock-Youku#557]
在Google Groups里面有很多用户都反映腾讯的体育直播出了问题，但因为我经常不在直播时段上线，没法进行测试。谁能帮忙看看？

**Comment by mc16888** [comment]
剛剛試了一下, NBA 直播, 沒問題. 
![qqnba](https://cloud.githubusercontent.com/assets/6530873/12072784/73bc9e34-b12d-11e5-8b7a-dd13f5fafd2b.png)

PS, 我在香港.

**Comment by JasonC1177** [comment]
我在美国，从25号开始就不能看了。

**Comment by JasonC1177** [comment]
如果多刷新几次的话，偶尔会成功，但是特别卡。

**Comment by JasonC1177** [comment]
![image](https://cloud.githubusercontent.com/assets/16512850/12072830/d0aeaee8-b0c4-11e5-9ea0-2e490d87ab93.png)

**Comment by JasonC1177** [comment]
error1:

![image](https://cloud.githubusercontent.com/assets/16512850/12072836/2037555a-b0c5-11e5-8279-779144a716fd.png)

**Comment by JasonC1177** [comment]
2:
![image](https://cloud.githubusercontent.com/assets/16512850/12072837/2e38e2d6-b0c5-11e5-98fe-446ed94d9783.png)

**Comment by JasonC1177** [comment]
3: 
![image](https://cloud.githubusercontent.com/assets/16512850/12072839/39f3ff3e-b0c5-11e5-93ff-45778f440fd5.png)

**Comment by JasonC1177** [comment]
4:
![image](https://cloud.githubusercontent.com/assets/16512850/12072841/61d9f53a-b0c5-11e5-9488-d8b8e2c05f74.png)

**Comment by JasonC1177** [comment]
刷新后出现的新error:

![image](https://cloud.githubusercontent.com/assets/16512850/12072842/c37c0ad0-b0c5-11e5-9818-0adfee9e0937.png)

**Comment by yanggis** [comment]
用IPad或者IPhone，把DNS设置成104.236.189.178试试看看能不能看，要是不够流畅就选择标清模式。

**Comment by JasonC1177** [comment]
@yanggis 
ipad确实是可以看的,但是需要用腾讯视频app. 现在是pc端看不了。

**Comment by yanggis** [comment]
哦，估计要等开发人员更新一下PC端的插件才行……

**Comment by JasonC1177** [comment]
@yanggis 
多谢了，至少我可以先在pad上看。

**Comment by JasonC1177** [comment]
@yanggis 
我把我pc的dns设置成你提供的，现在可以用正常模式看蓝光直播了，并不会卡。

**Comment by yanggis** [comment]
OK，Good！
