### ISSUE TITLE
能帮忙看看这个, 云视听企鹅, 腾讯的点播是否可以unlock呀

### ISSUE THREAD

**Issue by wtjfree** [Unblocker/Unblock-Youku#558]
我发现这个腾讯的视频直接获取了我的外网ip,然后电视剧都不能播放的.我设置了104的那个dns. 也没用.

直接提示错误(101,80) 基本就是版权的问题.

播放综艺类没问题.

**Comment by yanggis** [comment]
你用的是Android还是IPad或者IPhone呢？我刚才试了IPad和Android盒子上都没有问题。设置DNS之后输入ip138.com看看你的IP是不是国内的，如果不是就说明你设置有问题，代理没有起作用。

**Comment by yanggis** [comment]
设置后最好重新启动一下系统，清空一下DNS缓存。

**Comment by wtjfree** [comment]
我用的是android box 米月传看不了呀.

**Comment by wtjfree** [comment]
已经重启好几次了.需要路由器也重启吗?

**Comment by yanggis** [comment]
你在盒子的浏览器里打开ip138.com，看看显示的你的IP是多少，然后贴上来。

**Comment by wtjfree** [comment]
ip138.com显示吉林延边. 我们有贴地址.没用.但是在云视听里面,有个版本信息.就会直接出现我的实际ip

**Comment by wtjfree** [comment]
我相信DNS是好用的.但是貌似需要多加一行?

**Comment by wtjfree** [comment]
我重启一下所有的设备包含电视盒子,路由器.然后回来报到一下.ip地址之类.

**Comment by yanggis** [comment]
云视听.企鹅 这个软件软件。1.6版本是100%可以用的，设置DNS之后就可以播放芈月传，我刚才还在看第63集。

**Comment by wtjfree** [comment]
感谢yanggis, 重启路由器后.故障排除.
还请问下.如果自己按照美团教程设置的unlock youku.是否是和您的dns一样的效果呀? 如教程设置的服务器可以称作DNS吗?

**Comment by yanggis** [comment]
肯定不一样呀，这个盒子上的软件比较杂，需要破解的链接经常变，如果你不跟踪更新的话，过一段有些软件就会失效不能unblock了，所以自己搭建的话维护起来比较麻烦。

**Comment by wtjfree** [comment]
说实话不希望您的dns也如同192一样的后果.所以想自己搭建. 还请不吝赐教. 我简单想法是维护一个网址列表吧.

**Comment by wtjfree** [comment]
当然DNS是安卓的救星了(ipad上都用的是pac).都非常简单易用.但是DNS缺点是,这似乎影响了商业软件的噱头财路.所以才有自己搭建的想法.我觉得如果有网络上每个国家都有3-5个这样的dns我相信这个技术壁垒必然不攻自破了.

**Comment by wtjfree** [comment]
请问是否有搭建DNS的教程呀.

**Comment by yanggis** [comment]
这个不用担心，104.236.189.178这个服务器现在有很好的防DDOS攻击的策略，也有预防恶意攻击代理服务器的策略，所以基本不会down掉的。自己搭建比较麻烦，搭建一个简易的话稳定性比较差，搭建一个成熟稳定的很麻烦，我没时间写这个教程，因为很多是我用shell script写的脚本维护的。教程写的话，就会被那些奸商复制过去，所以觉得很不平衡……

**Comment by yanggis** [comment]
所以只想免费提供给大家使用，当然愿意不愿意用全凭自己选择了……

**Comment by wtjfree** [comment]
其实大部分还是因为不知道这DNS概念所以就奔向了付费软件. 只有我这样的折腾党.和学生党才有兴趣搞.^_^. yanggis的精神可加呀.希望有机会能帮上忙.

**Comment by yanggis** [comment]
嗯啊，一起折腾啊，我也是折腾党……

**Comment by wtjfree** [comment]
我是瞎折腾.回头有时间自己先学着搭建个DNS先.总感觉美团那个不是个DNS.所以一直迟迟没动手.^_^. 需要让这个技术平民化.当然脚本不要公开了.倒是安全策略可以各抒己见了,脚本还是要靠自己摸索了(这个属于高大上了).至于DDOS,我的想法是服务器多了.他们这些搞的就无趣了.

**Comment by yanggis** [comment]
嗯，你可以自己在美团云上搭建一个试试，DDOS可能很快就会把你的DNS服务器攻击得down掉了。
