### ISSUE TITLE
关于qq音乐的问题

### ISSUE THREAD

**Issue by asuka0819** [Unblocker/Unblock-Youku#559]
坐标日本
之前用google开网页版还能试听然后扒音频的，但是现在完全没反应了，不知怎么回事
至于手机的，添加了pac之后也是显示错误
客户端有一段时间可以正常使用，但是不知怎么又废了
不知道各位大神有没有什么简明易懂的办法
小的实在是白痴啊TAT
谢谢！

**Comment by tommyzhaozbh** [comment]
QQ音乐的话应该是没大问题的，网页的请按照wiki里面(诊断专用)那篇文章提供的方法进行嗅探并上传。pac的话由于规则有变(ios客户端的规则变了)，而且据说是会变的裸ip，所以暂时无法解决。
PC客户端如不想折腾请使用dns(104.236.189.178)，这个方法对手机可用。
Ps:根据本人之前的多次测试，发现QQ音乐网页版偶尔会无法获取音频源地址，刷新几次即可。

**Comment by asuka0819** [comment]
谢谢！已经弄好了！

**Comment by tommyzhaozbh** [comment]
ios的话真的一时半刻解决不来，除非pac的规则更新（但目前pac的主要负责人不在，恐怕一时半刻都搞不定）。
腾讯在这次ios版更新之后把所有的检测连接都换成了裸露ip的地址，而不是像之前那样用域名的，更恶心的是这些ip都是会变的，dns没法加规则。（详见#536 )所以即便换了DNS也是没用的。

**Comment by asuka0819** [comment]
所以现在是所以的pac都不能用吗？
换了下pac用163测试都是显示false

**Comment by tommyzhaozbh** [comment]
Pac理论上是可以的，因为只要设备能够获取pac文件就能执行代理规则。但目前pac服务器down了，现在是一直靠cloudfare的CDN去顶替的，不知道设备会不会不认CDN而无法获取代理文件了…那pac就暂时别用吧

**Comment by klib9739** [comment]
還好Android的部分目前還是可以正常使用的
