### ISSUE TITLE
搜狐视频美国的CDN加速器是不挂掉了？

### ISSUE THREAD

**Issue by yanggis** [Unblocker/Unblock-Youku#560]
谁在北美地区啊，是不是搜狐视频美国的CDN加速器挂掉了啊？最近发现搜狐视频只要一连美国的CDN服务器就基本没响应，视频也看不了……。

**Comment by klib9739** [comment]
@yanggis 可否協助將m.xiami.com加入代理裡面
Android版客戶端似乎只要加入這個就能使用

**Comment by tommyzhaozbh** [comment]
搜狐的北美CDN本来就有点问题，很多人都反馈说在北美地区都出现连线失败的……换一个CDN会不会好点?抑或是再加一个代理规则绕开北美的服务器?

**Comment by yanggis** [comment]
现在搜狐视频在香港和新加坡的CDN工作正常，但是负责分配CDN的是http://220.181.61.*的北京的服务器，它会根据你的IP给你分配离你最近的服务器，但是如果你是在海外，不在北美地区，你大概有30%的概率会被分配是北美的服务器，一旦分配上就基本是视频卡上，如果是在北美地区，基本是80%以上都是分配的北美的服务器，就什么也播不了。如果你用PAC文件，就加入一个连接把http://220.181.61.*这个走国内代理，就会分配国内的电信服务器，就可以看视频了。其他没有更好的办法。这个是基于IP的，也没法用DNS破解。

**Comment by MonkeyLeeT** [comment]
@yanggis hosts文件内强行map tv.sohu.com到北京的cdn地址（具体ip可以ping出来）也可以。在美国比较容易被分配到的是fhk.a.sohu.com这个连不到的cdn（是的香港的也屏蔽海外了），如果分配到fbjuni.a.sohu.com这个cdn就能读取成功。

可否分享下220.181.61.*的pac规则？我改了下似乎不是很有效，可能是语法上不太正确。不过更奇怪的是我挂着国内代理也会被分配到海外cdn，太诡异了。

**Comment by yanggis** [comment]
@MonkeyLeeT tv.sohu.com本来解析出来的地址就是北京的，如果你想不解析，可以把这个IP添加到hosts里面 101.227.172.11 tv.sohu.com (上海电信) 140.207.205.39 tv.sohu.com (上海联通的)，；你要挂着国内代理分配的还是海外CDN，就是你把220.181.61.*走pac，估计也没什么用吧？

**Comment by MonkeyLeeT** [comment]
感谢回复。

直接map主站可以读取出网页，但是缺失大量的css/js/图片。因为这些资源从不同的cdn域名拿东西（比如i0.itc.cn和css.tv.itc.cn），而且这些域名的解析后的cname其实还是到和主站同一个cdn地址（fhk.a.sohu.com，fbjuni.a.sohu.com，还有贴出来的两个对应的cdn域名）。

http://ping.chinaz.com/，从这个ping tv.sohu.com的结果来看，哪怕是国内地址也会有机会撞上hk的那个175开头的cdn，没有一个isp可以幸免。。。除非可以在ip层面把请求都跳转，不然看来暂时只能手动map掉每一个地址了。

**Comment by yanggis** [comment]
@MonkeyLeeT 嗯，是的，搜狐视频这个做的特别混乱。
