### ISSUE TITLE
请问自己搭DNS Server的话也可以达到unblock youku的效果吗？

### ISSUE THREAD

**Issue by twilightgod** [Unblocker/Unblock-Youku#561]
小白刚看了几篇文章，国内网站是通过一个包判断ip来识别，只要自己搭DNS，让访问特定url的请求转到114.114.114.114解析就行了吗？

**Comment by yanggis** [comment]
显然不是啊，按你想法，你就不需要搭建DNS，直接把你家所有的设备DNS都设置成114.114.114.114，直接去114服务器请求数据多好啊，就不需要自己建然后再转发了嘛。

**Comment by tommyzhaozbh** [comment]
当然没这么简单。114的那个服务器只是DNS而已，不是代理服务器。也就是说，它只负责把域名翻译成ip地址并把你引导至网站的服务器上，但不能作为跳板去欺骗服务器。这里你需要的是一个代理服务器而不是DNS。更何况，判断是是否在大陆是网站服务器根据ip数据库去判断的，跟DNS一点关系都没有。把这些地址导向一个DNS有什么用呢?

**Comment by zhuzhuor** [comment]
@yanggis 有机会写个搭建 DNS 的教程吗，估计很多人都会感兴趣的
