### ISSUE TITLE
服务器好像被攻击了……

### ISSUE THREAD

**Issue by tommyzhaozbh** [Unblocker/Unblock-Youku#562]
![qq](https://cloud.githubusercontent.com/assets/8757104/12145323/88829e60-b4c8-11e5-991a-b06bdfe8e8c3.png)

![qq](https://cloud.githubusercontent.com/assets/8757104/12145348/9dea9bc2-b4c8-11e5-9b08-518f7711e972.png)
这是两个代理服务器的状态，Z1服务器（https的服务器）好像被持续攻击了。现在反馈平台大量用户报告无法使用，看来不开玩笑啊……所有网站全部报错。

**Comment by yanggis** [comment]
不能做攻击监测吗？监测到攻击立刻把IP给ban掉呢？我的DNS服务器就是自动检测，监测到攻击立刻ban掉整个IP段。

**Comment by hafa2012** [comment]
看了pingdom的监控，好像有个pac server H1还能用。哪个大神告诉我这个server的域名地址？

**Comment by tommyzhaozbh** [comment]
@yanggis 理论上应该行，不过看样子我觉得最好把大陆的地址都屏蔽才行。
虽然我不知道他在不在，不过还是得叫唤一下@zhuzhuor

**Comment by tommyzhaozbh** [comment]
@hafa2012 还是一样，都是pac开头的

**Comment by hafa2012** [comment]
pac开头的什么呀？真不知道

**Comment by tommyzhaozbh** [comment]
@hafa2012 http://pac.uku.im/proxy.pac

**Comment by hafa2012** [comment]
@tommyzhaozbh
谢谢，那之前的是这个嘛？
http://yo.uku.im/proxy.pac

**Comment by tommyzhaozbh** [comment]
两个其实是一样的

**Comment by yanggis** [comment]
@tommyzhaozbh zhuzhuor最近是不是很忙啊，很久没见他上来了。

**Comment by tommyzhaozbh** [comment]
@yanggis 好像是，现在还有两个pull request卡着还没去审批呢。Google Groups已经炸开了。

**Comment by zhuzhuor** [comment]
@zhuzhuor 最近的确挺忙的，假期 + 项目要 release 了 + 开会
这攻击我前两天就注意到了，昨天刚给 PAC 新弄了个服务器

@yanggis 就像之前一样，这 DDoS 的流量还没到我们的服务器就被运营商给掐了，我们的防火墙起不到作用

等我这两天多开几个服务器吧
有人想捐赠服务器 / 提供维护工作也可以找我

@tommyzhaozbh 非常感谢你最近的工作！

**Comment by tommyzhaozbh** [comment]
@zhuzhuor 不用谢。现在主要是Z1服务器问题比较大，看来100M的服务器也未必能够顶得住这流量攻击呢……那台服务器有没有做防护？
