### ISSUE TITLE
请问能够直接在代理插件中设置代理吗

### ISSUE THREAD

**Issue by fyears** [Unblocker/Unblock-Youku#563]
我想**不**使用 unblock youku 插件，而使用类似于 Switchy 之类的插件，直接设置类似于

```
ipservice.163.com  proxy
```

这样设置可以吗？
其中，proxy 的地址应该填写什么？

**Comment by zhuzhuor** [comment]
参看 http://uku.im/modes 最下面的部分

**Comment by fyears** [comment]
呃，其实，我的本意并不是说要解决两个插件的冲突。

我的本意是，因为现在 pac 文件并不好用，想通过第三方代理 app 在 ios 和 android 上设置从而达到解锁的目的。

**Comment by whuhacker** [comment]
@fyears 现在 PAC 的代理服务器被攻击，你可以换成你自己的服务器
直接下载 PAC 文件，编辑修改最后的 `_proxy_str="PROXY proxy.uku.im:443; DIRECT;"` 部分，将 `proxy.uku.im:443` 改为你自己的服务器 IP 和 端口。
再在客户端引用修改后的 PAC 文件即可

**Comment by zhuzhuor** [comment]
@fyears 啊，抱歉看错了

刚好 @xin-zhang 刚交了个新的 pull request 给扩展程序自设代理的功能 https://github.com/Unblocker/Unblock-Youku/pull/566
初看起来不错，等我今天好好试试然后 update 给用户吧

**Comment by zhuzhuor** [comment]
最新版的扩展程序已经上传到 Chrome Web Store 了，稍微等等 Web Store 给 Chrome 用户的自动更新
欢迎试用给普通模式设置代理服务器的功能，如果有问题欢迎再来反馈

![screen shot 2016-01-10 at 2 15 13 pm](https://cloud.githubusercontent.com/assets/928905/12224426/ffc85288-b7a4-11e5-999b-657abf3ebb9b.png)
