### ISSUE TITLE
iOS端bilibili新番显示无片源

### ISSUE THREAD

**Issue by Genius-Hui** [Unblocker/Unblock-Youku#564]
仅限这季新番，在打开番剧专题页的时候显示没有片源，但是输av号还是可以看
坐标加拿大 不知道其他地方是不是也有这个问题

**Comment by zhuzhuor** [comment]
能提供几个地址吗，方便 contributor 用同样的视频来测试

**Comment by Genius-Hui** [comment]
对不起忘记说是ios手机端 网页目前一切正常

**Comment by zhuzhuor** [comment]
bilibili 的 iOS app 貌似只有中国的 app store 里面才有？

**Comment by Genius-Hui** [comment]
似乎是的

**Comment by lamlam77777** [comment]
還是倒不是跟android端一樣的問題嗎

**Comment by Genius-Hui** [comment]
嗯我刚刚试了一下，现在正常了，谢谢。

**Comment by xkk** [comment]
@zhuzhuor 
我目前也碰到了这个问题
http://www.bilibili.com/bangumi/i/3128/
比如说这个
我ios下app打开后看不到片源
用104的dns能看到3集
