### ISSUE TITLE
bilibili安卓端出現b站當季新番無法播放

### ISSUE THREAD

**Issue by kit90099** [Unblocker/Unblock-Youku#565]
我按進去顯示“無”
http://imgur.com/KoLR0mr

**Comment by kit90099** [comment]
我用過Pac文件，dns都不成功 後來用VPN就顯示有視頻了

**Comment by kit90099** [comment]
上季的能放 今季的放不了
http://imgur.com/IfcHidQ

**Comment by yanggis** [comment]
@kit90099，你DNS用的是104的那个服务器吗？

**Comment by kit90099** [comment]
是的

**Comment by kit90099** [comment]
不過我後來發現b站只是在番劇的頁面封了 但用輸av號的方法還可以看

**Comment by yanggis** [comment]
@kit90099，如果是用的104的DNS，肯定是你那边的问题，极速老师这个第一集用104的DNS在国外肯定可以看的。我刚刚看过。

**Comment by kit90099** [comment]
是番剧的页面显示“无”
但直接用av号看的话倒是能看的

**Comment by yanggis** [comment]
网页版，电脑上直接打开就可以看啊。

**Comment by kit90099** [comment]
安卓版不行 刚看了一下其他issue的 好像ios也有这问题

**Comment by yanggis** [comment]
等我看一下，一会更新。

**Comment by kit90099** [comment]
http://imgur.com/bWsLQ6b
http://imgur.com/c0cpVz5
这是用dns和VPN的分别

**Comment by yanggis** [comment]
现在应该可以了，设置104那个DNS，然后重启一下手机应该就可以看了。

**Comment by kit90099** [comment]
成功了 谢谢你

**Comment by yanggis** [comment]
不过有时候缓冲超级慢……B站的服务器太少了……
