### ISSUE TITLE
Keep having same error on sohu

### ISSUE THREAD

**Issue by Smurfett** [Unblocker/Unblock-Youku#568]
Hi,

I keep having this issue for few days when I tried to watch video on Sohu.
![sohu](https://cloud.githubusercontent.com/assets/16661593/12256861/070c61e0-b93c-11e5-8664-4fc782681b05.jpg)

Occasionally when I change the operation mode of Unblock youku and refresh the page, the video will start playing again. But these two days, it doesn't work. Please help.
![unblockuku](https://cloud.githubusercontent.com/assets/16661593/12256913/8c02f602-b93c-11e5-8552-9b4a7238fb4f.jpg)

Thank you!

**Comment by zhuzhuor** [comment]
Our proxy servers are under DDoS attacks.
See https://github.com/Unblocker/Unblock-Youku/issues/562 and http://status.uku.im

**Comment by Smurfett** [comment]
Hi,

Thanks for the fast reply and the assistance. Hope to hear good news and updates from you real soon. 加油！
