### ISSUE TITLE
关于ios pac问题

### ISSUE THREAD

**Issue by fiveinches** [Unblocker/Unblock-Youku#569]
刚刚有看了一下服务器的status，pac server M1是正常的，但是我手机上的pac依旧无法使用，是怎么回事？是pac输入的内容有变化么？

**Comment by tommyzhaozbh** [comment]
应该是 pac.uku.im/proxy.pac 另外由于这个文件只是规则文件而已，它还是会把你指向另一个代理服务器。如果代理服务器被炸那同样不可用。

**Comment by xkk** [comment]
昨天也碰到了 用pac.uku.im/proxy.pac 乐视ios app不能看
提示的不是海外用户 而是视频无法播放
转用dns 104可以使用 偶尔出现视频不能播放 刷新一下就行了
