### ISSUE TITLE
愛奇藝台灣專區問題

### ISSUE THREAD

**Issue by klib9739** [Unblocker/Unblock-Youku#571]
愛奇藝目前增設台灣專區
發現有些問題
如果不掛unblock下面這些視頻可以正常觀看
但如果掛了unblock就會顯示版權問題
想請問目前除了觀看這些視頻時手動關閉代理
還有其他解決方法嗎?

必娶女人
http://www.iqiyi.com/v_19rrkpqai8.html

我的30定律
http://www.iqiyi.com/v_19rrkgnlro.html

**Comment by whuhacker** [comment]
@klib9739 感謝反饋
我這邊試過，確實非台灣地區是看不了的。我會在 unblock rules 裡面加上這個例外

**Comment by zhuzhuor** [comment]
@whuhacker 台湾地区的视频的  URL 有什么特别吗，还是只是给这两个视频弄白名单？

**Comment by whuhacker** [comment]
@zhuzhuor 我發現沒那麼簡單，不是白名單能解決的

愛奇藝使用了同一個 API 來檢驗 IP
某個影片只能大陸播放，則該 API 在看到大陸 IP 時會返回數據，非大陸 IP 沒有影片信息
某個影片只能台灣播放，則該 API 在看到台灣 IP 時會返回數據，非台灣 IP 沒有影片信息

so sad :(

**Comment by zhuzhuor** [comment]
@whuhacker 好吧，那除了搞个台湾的服务器做代理，估计没什么办法了?

**Comment by whuhacker** [comment]
@zhuzhuor 是的，而且還要解決什麼時候走台灣代理，什麼時候走大陸代理
光從 URL pattern 上來看，很難辦。因為最後面一大串參數不同而已

```
http://cache.video.qiyi.com/vms?key=fvip&src=1702633101b340d8917a69cf8a4b8c7c&tvId=417191900&vid=1d25ef6b8e328c43294d42a436759890&vinfo=1&tm=3716&enc=bb726cd79324ee0f9f722522c68c2ab5&qyid=2ea50187f6b4932adb2691c3dd085c12&puid=&authKey=e5d2213dcf1f7e5d68c54d915c71e9c6&um=0&pf=b6c13e26323c537d&thdk=&thdt=&rs=1&k_tag=1&tn=0.7724088476970792
```

以上要走台灣代理才行

```
http://cache.video.qiyi.com/vms?key=fvip&src=1702633101b340d8917a69cf8a4b8c7c&tvId=423958800&vid=1c9c453faa7acb575d454d6f6dc89915&vinfo=1&tm=5405&enc=77344facd2eae2b975dafc43f704ff63&qyid=2ea50187f6b4932adb2691c3dd085c12&puid=&authKey=9cdfe6aedb689748bf03c9e029f7578f&um=0&pf=b6c13e26323c537d&thdk=&thdt=&rs=1&k_tag=1&tn=0.5244347574189305
```

以上要走大陸代理才行

**Comment by klib9739** [comment]
所以若是透過設定DNS就無解吧?

@zhuzhuor @whuhacker

**Comment by zhuzhuor** [comment]
@klib9739 暂时应该没啥好办法
在 Chrome 扩展里，可以改成 Lite 模式，相当于是关闭了

DNS 就只能改成非 Unblock DNS 来看了
