### ISSUE TITLE
[非官方] Android的unblock软件，欢迎测试

### ISSUE THREAD

**Issue by yanggis** [Unblocker/Unblock-Youku#572]
大家好，我最近新写了一个专门针对Android平台的unblock软件，叫Chinatunnel，在Android设备上看中国视频时候启动这个软件，它就会自动拦截需要unblock链接进行破解，视频就可以直接看了。同时它也支持定制IP，为那些有自己代理服务器的人提供方便。软件需要root权限，Android必须root才能正常运行。欢迎大家下载测试，有问题在这里反馈，我会再做改进。
具体使用方法。
1.安装之后第一次运行请先点击update whitelist按钮，更新软件配置文件，大概需要2分钟。然后点unblock China那个开关开始运行，然后按home键保证软件后台运行就可以了。
2.系统默认是用的我自己的服务器，如果你有更好更快的服务器，可以在服务器设置里配置自己的服务器，然后点运行，这样软件会自动把需要破解的链接导向你的服务器。然后在你的服务器上看有没有导过来的链接就知道了。
3.whitelist需要经常更新，一般一周更新一次就OK，这样破解才会经常行之有效。
使用这个软件主要优点在于，软件可以破解在http//218.12.13.534/geoip （比如QQ音乐之类的，这个还没加进去）的这种不走DNS解析的破解；同时可以定制要链接的视频服务器，绕开那些将死或者速度慢的服务器（比如搜狐视频北美的CND基本都挂掉了）。再就是它可以在任何场合使用，不会像DNS破解在学校或者单位网络中无法使用。
欢迎下载测试，或者提供新的unblock的link，和我一起完善这个软件，直接把需要unblock的IP或者link发给我，我就会加上去。你在设备上点update whitelist就可以正常运行了。
软件下载链接：
yunpan.cn/crZIfwGYXJzBU （提取码：47fb）

**Comment by klib9739** [comment]
@yanggis 
whtielist是不是少了a.play.api.3g.youku.com
proxy.pac裡面有

**Comment by yanggis** [comment]
嗯，我已经添加上了。

**Comment by yanggis** [comment]
现在还在调整服务器，服务器有点不稳定。

**Comment by klib9739** [comment]
@yanggis 
更新之後有了感謝yanggis
另外想問為什麼有些規則在proxy.pac裡面有在whiltelist裡面沒有
例如hot.vrs.letv.com等
本以為兩者是同步的

**Comment by yanggis** [comment]
ex. hot.vrs.letv.com这个乐视基本已经不用了，早就删掉了。

**Comment by klib9739** [comment]
了解
所以目前是以whitelist裡的內容為主
只是proxy.pac裡面有部分內容還未刪除?

**Comment by yanggis** [comment]
嗯，我是根据大家访问DNS的统计，发现有些链接是死链接，已经基本不用用了才删掉的。proxy.pac的规则我不太清楚，也可能不同的平台验证有点不一样吧？我这个主要是android为主。

**Comment by zhuzhuor** [comment]
这个`它就会自动拦截需要unblock链接进行破解，视频就可以直接看了` 具体指的是？还是用的代理的原理，还是有别的 unblock 的办法？

**Comment by alexking99** [comment]
用不了 提示
 failed to start proxy.sh (error: only position independent executables(pie) are supported

**Comment by yanggis** [comment]
这个是一年为Android L的新的可执行程序必须要PIE支持，才允许运行，但是这个新的二进制文件我还没有编译后，后面编译好了之后会替换掉旧的就可以了。

**Comment by yanggis** [comment]
@zhuzhuor，是用的代理，类似Droidproxy。

**Comment by alexking99** [comment]
@yanggis 希望尽快弄好 想试用   另外希望可以退出了还能用开机能自动运行   能自动更新名单

**Comment by yanggis** [comment]
那个Android模式需要替换你自己手机上的一个系统文件linker，你自己可以在这里下载，
http://alseambusher.github.io/linker
下载以后，用RE把元首手机里的/system/bin/linker文件重命名，然后把下载的这个复制进去/system/bin/下，然后修改权限为755，就可以了。
如果你不会的操作，可以看这个教程的第二步，上面有截图：
http://lifepluslinux.blogspot.sg/2015/01/installing-python-on-android-50.html
然后再运行ChinaTunnel就可以运行了。

**Comment by yanggis** [comment]
更新Google Play应用商店下载链接：
https://play.google.com/store/apps/details?id=com.yanggis.chinatunnel

**Comment by xkk** [comment]
有没有办法弄个给电视盒子用的

**Comment by yanggis** [comment]
@xkk 这个可以在电视盒子上安装啊。

**Comment by xkk** [comment]
@yanggis 太客气了 就持续关注吧 期待大作

想着自己学习一下研究一下
自己也弄一个 不但能翻墙还可以屏蔽一些广告
不过知识面太窄 很多东西看的都不是太明白

**Comment by yanggis** [comment]
Android的解锁软件修复了一个重要Bug，现在网易云音乐和QQ音乐应该可以用了。请及时更新。
下载地址：
https://yunpan.cn/crcfgfg2gwrcQ （提取码：7c11）

**Comment by BeefyGitHub** [comment]
我用的是Fire Stick，不知道怎么root。是不是就不能用这个啊？

**Comment by yanggis** [comment]
@BeefyGitHub 必须要root才可以用，具体Fire Stick怎么root你可以看这个帖子，
http://forum.xda-developers.com/fire-tv/general/firetv-stick-ftvs-root-firmware-updates-t2957509

**Comment by zhuzhuor** [comment]
因为这个不是真正的 issue，就先 close 了

**Comment by s3969** [comment]
启动后，点ON，反映略慢，升级白名单速度也略慢，但是确实能翻进CHINA

**Comment by yanggis** [comment]
@s3969 感谢反馈，手机上用选择省电模式(lite)会启动很快，whitelist十天半个月更新一次就OK了。
@s3969 图标仅仅是一个示意，和政治无关，别误读哈:).
