### ISSUE TITLE
unblockyouku被unblockcn劫持了吗？

### ISSUE THREAD

**Issue by O-zhang** [Unblocker/Unblock-Youku#573]
https://github.com/typcn/bilibili-mac-client/issues/195

**Comment by whuhacker** [comment]
这货做法太恶心了

**Comment by zhuzhuor** [comment]
@O-zhang 多谢提醒，我猜是用户安装了 UnblockCN 之后就留了个全局的 PAC 或者 DNS 设置

感觉挺恶心的，之前到处发软文说 Unblock Youku 改名成 UnblockCN
这几次的针对 Unblock Youku 服务器的 DDoS 攻击，我个人猜测也和 UnblockCN 脱不了干系

**Comment by xkk** [comment]
太恶心了 之前也是因为网易音乐差点就装上了
