### ISSUE TITLE
作者，想请问能在OPENWRT路由器里面直接使用这个吗？

### ISSUE THREAD

**Issue by calvinslim** [Unblocker/Unblock-Youku#574]
因为自己有在卖路由器，最近很多香港的朋友老是问这个，也有那边的电子商家找我，说让我研究这个，需要几千台的订单。用户他们不喜欢装插件，不喜欢麻烦。我就想把这个内置到路由器里面，就可以解决到所有问题了？？？ 那么服务器是不是要跟代理一样承担巨大的带宽？ 还是只需要承担一点转发的功能？ 求作者解答， 实现该功能，本人愿意有偿合作！我本来是想着通过SS服务器来解决问题，但带宽实在吃不消！ 我的联系邮箱是 2862376464@qq.com ，好不容易搜到真正的作者， 在那边被一个坑爹UNBLOCKCN软件忽悠了我很久。 作者无论如何求一个答复就好。

**Comment by yanggis** [comment]
这个用OpenWRT当然可以，但是估计需要定制一个脚本才行，你需要编译OpenWRT的时候把这个脚本编译进去，并能自动升级配置文件，应该就没问题了。

**Comment by calvinslim** [comment]
服务器端是否就弄成DNS服务器代理就可以解决？

**Comment by yanggis** [comment]
DNS服务器只能解决70%的视频问题，已知道现在DNS没法解决的有搜狐视频，网易云音乐，QQ音乐等。

**Comment by zhuzhuor** [comment]
@calvinslim 我是 Unblock Youku 项目的作者
根据你想代理的网站了，大部分的不是很多，有些会比较麻烦
另外能说说 UnblockCN 怎么忽悠你的吗

你想私下聊的话可以在在 http://zhuzhu.org 或者 http://gitter.im/zhuzhuor 找到我

**Comment by yinfei219** [comment]
@yanggis 请教如何才能往openwrt里面加入unblockyouku的功能

**Comment by yanggis** [comment]
@yinfei219 你直接在OpenWRT里面局域网里的DNS设置为45和158的两个服务器，手机和电脑向OpenWRT申请IP的时候，让OpenWRT连同DNS一起广播给手机和电脑就行了。其他基本不需要配置。

**Comment by yinfei219** [comment]
@yanggis OK，谢谢啦，不过这几个服务器速度我这里都不快，如果都换成这几个dns了，下载速度太慢了
