### ISSUE TITLE
爱奇艺提示浏览器兼容问题

### ISSUE THREAD

**Issue by zhuzhuor** [Unblocker/Unblock-Youku#575]
用户反馈 https://groups.google.com/forum/#!topic/unblock-youku/Q1L2O5jdNg0
我试了下的确是这样

视频范例 http://www.iqiyi.com/v_19rrnx0m58.html

![screen shot 2016-01-23 at 3 54 56 pm](https://cloud.githubusercontent.com/assets/928905/12533593/ad67a7ce-c1e9-11e5-8a98-f6e50b7e7510.png)

**Comment by zhuzhuor** [comment]
新加了一条 iqiyi 的链接进代理，貌似现在没问题了
可以等等 Chrome 扩展的更新试试

@tommyzhaozbh

**Comment by yyyyyi** [comment]
@zhuzhuor 那请问现在插件是否已经能正常工作了呢?

**Comment by zhuzhuor** [comment]
@yyyyyi 多谢反馈，我上次试是好了，现在试却还有问题，我们再测试测试。再次感谢反馈

**Comment by zhuzhuor** [comment]
@tommyzhaozbh 我这测试偶尔可以播放、偶尔不行
你之前提到爱奇艺的海外分配的 CDN 有问题？能具体说说吗?

**Comment by tommyzhaozbh** [comment]
当时那个是因为服务器的 crossdomain 无法获取导致视频无法播放所以才换的。但现在的话不晓得哪里有问题，所以最好做一次嗅探看看那个连接有问题。

**Comment by FreeTymeKiyan** [comment]
现在还是不能看

**Comment by zhuzhuor** [comment]
@FreeTymeKiyan 多谢反馈

我在最新版[新加了个爱奇艺的 URL](https://github.com/Unblocker/Unblock-Youku/commit/5150d02c7fa49b8b9505bfe1daedf876a9b8eb64)，不知道管不管用，我们可以再试试
爱奇艺这个测试的时候也是偶尔才有问题，所以不好 debug

**Comment by zhuzhuor** [comment]
想起来这里还有个 open issue 是关于 iqiyi 的
我在 #612 叙述了一些最近的分析结果，这个 issue 就关闭了
如果你们有新的发现和见解欢迎去 #612 讨论，谢谢
