### ISSUE TITLE
关于新的翻墙回国

### ISSUE THREAD

**Issue by Migflyway** [Unblocker/Unblock-Youku#576]
国人采用 shadowsocks 翻墙出来，现在有很多成熟的技术，科学翻墙，自动分流等等。是否可以相同方式再翻墙回国。当然需要一台国内服务器。

**Comment by zhuzhuor** [comment]
新的是指？ 
Shadowsocks 是为了伪装流量不被检测出来，我们只需要普通的代理软件就可以了
