### ISSUE TITLE
iOS下 bilibili 某些新番获取不到集数

### ISSUE THREAD

**Issue by xkk** [Unblocker/Unblock-Youku#577]
iOS下 bilibili 某些新番获取不到集数 使用的是 http://yo.uku.im/proxy.pac
例如
http://www.bilibili.com/bangumi/i/3128/
和
http://www.bilibili.com/bangumi/i/3101/
分集数的位置是空的

**Comment by xkk** [comment]
使用的是http://yo.uku.im/proxy.pac

**Comment by zhuzhuor** [comment]
你试试 `http://pac.uku.im/pac.pac` 看看这个管用不？
之前那个域名总被人看错成 youku.im 于是就改成 pac.uku.im 了

**Comment by xkk** [comment]
集数可以看到了 但是点击播放会提示 获取视频内容失败

**Comment by asuka0819** [comment]
同样出现3l的问题，看我们这一家都无法打开视频了

**Comment by zhuzhuor** [comment]
是这两天突然出现的问题吗? 都是在 iOS app 上？

**Comment by xkk** [comment]
之前用bilibili比较少 最近用的多了才发现 不是很清楚之前是否也存在
我的都是在ios上
ipad的客户端 player里面显示获取内容失败
iphone的客户端 player左下角显示 获取视频地址完毕-分析视频地址失败

**Comment by BridmanWing** [comment]
我幾條pac都試過了，youku能看，就是bilibili不能

**Comment by hpzf89** [comment]
确实有这个问题，测试地址为日本，相同wifi网络环境下PC端chrome下运行正常，IOS端失败，尝试过手动设置几个免费代理，依旧不行。※我记得在4g网络下测试过一次，似乎是成功的，有点不太记得了，需要再次确认下。

**Comment by mc16888** [comment]
之前試過, bilibili ios app 播放的時候會無視 PAC 的規則, 直連這個需要代理的url 
http://interface.bilibili.com/playurl?*, 這個問題暫時只能用DNS的方法解決.

**Comment by kit90099** [comment]
試試搜尋up主:bilibili番劇找要的番

**Comment by asuka0819** [comment]
@mc16888  这个具体要怎么操作了

**Comment by mc16888** [comment]
@asuka0819 你把WIFI的DNS ip 改成 104.236.189.178 就可以了.

**Comment by asuka0819** [comment]
@mc16888 修改之后可以看集数，但是进去视频显示分析视频地址失败。

**Comment by mc16888** [comment]
@asuka0819 我剛試了一下,沒問題.
