### ISSUE TITLE
关于教程“在美团云架设自己的 Unblock Youku 代理服务器”。。。

### ISSUE THREAD

**Issue by hafa2012** [Unblocker/Unblock-Youku#578]
版主和热心会员们，我按照教程如法炮建了一个美团云的服务器，
请问如何检查自己服务器状态？用什么命令？
怎么查看是否正常运行？
谢谢

**Comment by xkk** [comment]
试试访问
http://ipservice.163.com/isFromMainland
如果返回true应该就是行了吧

**Comment by zhuzhuor** [comment]
你可以在 Chrome Extension 里设置下代理服务器试试
https://git.io/vupNr

**Comment by hafa2012** [comment]
谢谢～～～工作正常啊

**Comment by KanVivii** [comment]
想问一下自建服务器的教程在哪里呀

**Comment by zhuzhuor** [comment]
@KanVivii 见这里 https://git.io/vzmmZ
