### ISSUE TITLE
美团云弄的自己的unblock服务器出问题了

### ISSUE THREAD

**Issue by hafa2012** [Unblocker/Unblock-Youku#579]
为什么用putty连不上？timeout
有谁遇到相同的问题吗？
怎么解决呢？
谢谢

**Comment by zhuzhuor** [comment]
在美团云重启下？看看后台服务器状态？

**Comment by hafa2012** [comment]
都正常呀

**Comment by zhuzhuor** [comment]
你之前 putty 连接成功过吗
看看 ip 和端口填的对吗

另外你在美团那页面右键，有个美团的 web 终端可以连接服务器，你可以试试

**Comment by hafa2012** [comment]
ip肯定没错了，端口是默认的22
美团云web终端可以登录，但操作很不方便

**Comment by zhuzhuor** [comment]
Web 能登录，putty 却不行，有两个可能：服务器防火墙弄错了把 22 端口封了，或者 putty 的信息有问题？要是实在都不对就有点奇怪，你可以联系下美团云客服

**Comment by hafa2012** [comment]
解决了。。。谢谢zhuzhuor

**Comment by zhuzhuor** [comment]
比较好奇最终是什么问题?

**Comment by hafa2012** [comment]
我也很奇怪，之前设置好的8888和22端口，现在只剩下8888端口，，
自己会变？加上去就好了

**Comment by hafa2012** [comment]
@zhuzhuor 
我从新设置服务器了，发现一个问题不知道有没有影响
就是运行pip install requests的时候，提示:
![2016-02-01_114031](https://cloud.githubusercontent.com/assets/5762924/12706412/a349acd8-c8d8-11e5-8d28-aaa3b31c88c6.png)

**Comment by zhuzhuor** [comment]
这说明没有安装好

你试试依次运行下面两个命令
```
pip install --upgrade pip --trusted-host pypi.douban.com
pip install requests --trusted-host pypi.douban.com
```

**Comment by hafa2012** [comment]
![2](https://cloud.githubusercontent.com/assets/5762924/12706789/6b787d8c-c8df-11e5-8cf4-d9eced45b481.png)
这样就ok了？

**Comment by zhuzhuor** [comment]
:+1: 应该是 OK 了

**Comment by hafa2012** [comment]
@zhuzhuor 多谢！：）））
