### ISSUE TITLE
DNS 服务器遭到 DDoS

### ISSUE THREAD

**Issue by zhuzhuor** [Unblocker/Unblock-Youku#582]
![screen shot 2016-02-03 at 8 39 25 am](https://cloud.githubusercontent.com/assets/928905/12789221/c2652dde-ca51-11e5-8071-7eeb3b6c53b5.png)

**Comment by reilee** [comment]
今天发现Chrome提示
![2016-02-04 13 50 27](https://cloud.githubusercontent.com/assets/1324044/12806117/6e3880f8-cb46-11e5-99c6-664391d1bc82.png)
不知道是否有关系

**Comment by zhuzhuor** [comment]
多谢反馈，今天针对这个 DNS 服务器的 DDoS 攻击现在已经停止了

关于  Chrome 插件升级的这个提示，这是因为给第一次安装或者升级 Unblock Youku 的用户自动打开我们的 求助+澄清谣言+捐款 页面（这个页面只会自动弹出来一次）
更多的信息可以看看我重开的一个 issue https://github.com/Unblocker/Unblock-Youku/issues/583
