### ISSUE TITLE
Chrome 扩展升级提示需要 new permissions 的原因

### ISSUE THREAD

**Issue by zhuzhuor** [Unblocker/Unblock-Youku#583]
这次升级会提示需要更多权限是因为，给第一次安装或者升级 Unblock Youku 的用户自动打开我们的 [求助+澄清谣言+捐款](https://www.uku.im/index_zhs.html) 页面（这个页面每个用户只会自动打开这一次，之后不会再自动打开）

另外，提示 `Read and change all your data on the website you visit` 是因为 Unblock Youku 正常工作所需的代理权限，这个是之前的旧版本就一直有的权限，不是这次新加的。我们的扩展程序一直都是开源的，大家都可以检查源码安全。并且我们有很[精细的网站列表](https://github.com/Unblocker/Unblock-Youku/blob/master/shared/urls.js)来做安全控制。我们一直把用户的安全当做最重要的事情

给大家造成困扰，真的是不好意思
欢迎大家都能支持我们，一起走出现在的困境

**Comment by zhuzhuor** [comment]
一些提示的范例图

> ![screen shot 2016-02-03 at 8 46 22 pm](https://cloud.githubusercontent.com/assets/928905/12807394/c6e530f8-cac3-11e5-92a6-e20869af114e.png)

>  ![6e3880f8-cb46-11e5-99c6-664391d1bc82](https://cloud.githubusercontent.com/assets/928905/12807396/cc82cc8c-cac3-11e5-9e79-b652351f5322.png)

**Comment by LivingInPortal** [comment]
I just donated my only 50 rmb for unblock youku, although I'm just a senior high school kid.
Very appreciate the Unblock Youku!
I'm willing to donate again if I can.
虽然还是高中二小孩 还是依然捐了仅剩的50rmb
感谢Unblock Youku的无私捐献!
有钱的话还会捐的

**Comment by xkk** [comment]
想问下 现在的支付宝是unblock youku的专用捐款账号吗?
是不是所有打到这个账户的钱都会用作unblock youku

**Comment by zhuzhuor** [comment]
@LivingInPortal 非常感谢你的帮助！如果喜欢写程序写软件的话欢迎加入我们！

@xkk 支付宝是我国内一个朋友的帐号。是的，都会投入到 Unblock Youku 相关的工作上的

**Comment by tliu57** [comment]
捐了几刀以尽绵薄之力。。
另外对这个项目很感兴趣，刚刚checkout 代码下来，以后下班时间可以看看。想问一下有什么介绍代码的相关文档吗？（除了readme与FAQ)

**Comment by zhuzhuor** [comment]
@tliu57 非常感谢！欢迎欢迎！

代码还没有特别好的文档，我争取最近有空了写个上手开发的 tutorial
但是好在代码其实不多，看文件名就能猜到是功能，另外 `chrome/` `server/` 和 `shared` 分别代表 Chrome 扩展、转发模式的服务器、Chrome扩展和服务器共享的代码。

另外 Chrome extension 的官方开发教程可以看看 https://developer.chrome.com/extensions

**Comment by tliu57** [comment]
That's very helpful!
Thanks

**Comment by dida92** [comment]
**English translation of Unlock Youku's announcement regarding the "Read and Change all the data ..."**

The pop-up for this new version is a result of enabling first time user or whoever upgrade Unblock Youku to open the page Help + Clarification on Rumors + Donation. And users will only be prompted this webpage once.

In addition, what's on the reminder/popo-up " Read and Change all your data on the website you visit" is proxy needed for running Unblock Youku regularly. It's been there the entire time, and in the old version, not something newly added. Our extension has been open all the time, the safety of which can be checked by everyone. On top of this, we also present a clear and detailed list of websites for security control. We have always taken the safety of users as the highest priority.

Apologies for the confusion caused. We hope for continuous support from you all to get through our current hard times.



The pop-up for this new version is a result of enabling first time user or whoever upgrade Unblock Youku to open the page Help + Clarification on Rumors + Donation. And users will only be prompted this webpage once.

In addition, what's on the reminder/popo-up " Read and Change all your data on the website you visit" is proxy needed for running Unblock Youku regularly. It's been there the entire time, and in the old version, not something newly added. Our extension has been open all the time, the safety of which can be checked by everyone. On top of this, we also present a clear and detailed list of websites for security control. We have always taken the safety of users as the highest priority.

Apologies for the confusion caused. We hope for continuous support from you all to get through our current hard times.

这次升级会提示需要更多权限是因为，给第一次安装或者升级 Unblock Youku 的用户自动打开我们的 求助+澄清谣言+捐款 页面（这个页面每个用户只会自动打开这一次，之后不会再自动打开）

另外，提示 Read and change all your data on the website you visit 是因为 Unblock Youku 正常工作所需的代理权限，这个是之前的旧版本就一直有的权限，不是这次新加的。我们的扩展程序一直都是开源的，大家都可以检查源码安全。并且我们有很精细的网站列表来做安全控制。我们一直把用户的安全当做最重要的事情

给大家造成困扰，真的是不好意思
欢迎大家都能支持我们，一起走出现在的困境

**Comment by zhuzhuor** [comment]
@dida92 Thank you so much for the translation!
