### ISSUE TITLE
自己的squid服务器如何更新regex or pac?

### ISSUE THREAD

**Issue by joeylu** [Unblocker/Unblock-Youku#585]
首先太感谢unblock youku的工作，一定会支持到底

最近参考美团云squid的教程，成功架设了自己的dns服务器，运作正常，但有以下几个问题

通过curl -o /opt/crx_url_list.txt http://pac.uku.im/regex添加的视频list，和proxy.pac，如果想新增一些url，是否就直接写上去就行？两个文件里的url需要保持一致吗？

如果我不介意让squid解析我所有的dns，大致该如何设置，具体我会自己去google（我的想法是让家人的几个电视盒子都直连该服务器，所以解析所有dns应该会更方便吧？）

再次谢谢你们的hard work

**Comment by yanggis** [comment]
如果你仅仅是用Android设备，我建议你直接安装这个软件，就可以自动解锁，
https://play.google.com/store/apps/details?id=com.yanggis.chinatunnel
不需要自己搭建服务器。搭建服务器是很容易，但是维护非常麻烦，尤其是DNS服务器，一个DDOS攻击就可以让你的服务器down机一两天。你应该看到Unblock youku的开发人员经常会发布DDOS导致Unblock youku的服务器临时性故障的问题。
再就是现在很多基于IP的验证，DNS的方法是解锁不了的，比如QQ音乐之类的。所以DNS方法不太推荐。

**Comment by zhuzhuor** [comment]
@joeylu 美团云的教程的第四步就是设置自动更新 url 列表，你可以试试 https://git.io/vzmmZ

@yanggis 如果有 tech-savvy 的用户想学习，我们何乐而不为呢。个人用的非公开的 squid 服务器不会招致 DDoS 的

**Comment by joeylu** [comment]
谢谢大家的意见
1:确实，如果是private server的话，DDOS攻击的可能性很小1
2:我知道教程里第四步就是自动更新，但我想问有没有简单的教程自己制作url list，比方说，某个不在unblock youku官方list的网站，我想私自添加进去的话，该怎么做
3:其实我有好几台服务器想分享给大家，可用的IP段有将近10+ C Class，但鉴于怕被攻击的原因，不太敢捐给大家用，请问有什么好建议吗？

**Comment by zhuzhuor** [comment]
@joeylu 自己的列表只需要下载并修改 http://pac.uku.im/regex 这里的，然后上传到一个固定的网站上就行了。如果懂一点 JavaScript，推荐可以试试在 Heroku 上跑我们的服务器端程序，之后只需要修改 shared/urls.js 里面的代码然后再 push 到 Heroku 上就行了

非常欢迎给我们捐服务器 :+1: 
关于这个我们私下聊吧，你可以给我发邮件 http://zhuzhu.org 或者实时消息 https://gitter.im/zhuzhuor
