### ISSUE TITLE
乐视体育直播看不了

### ISSUE THREAD

**Issue by zmingxie** [Unblocker/Unblock-Youku#590]
Here is an example from this morning's EPL game: http://sports.letv.com/match/27552003.html#live/1020160202105734

On the other hand, video replay works fine: http://sports.letv.com/video/24584695.html#24584695

I'm in Toronto, Canada. Does anyone else see a similar issue? Thanks!

**Comment by zhuzhuor** [comment]
我刚才试了试正在现场直播的球赛还可以看
这些直播的地址都比较多变，我们得及时更新或者找个更方便的解决办法才行

http://sports.letv.com/match/111034003.html#live/1020160203012214
> ![screen shot 2016-02-06 at 11 38 57 am](https://cloud.githubusercontent.com/assets/928905/12868916/886a905c-ccc6-11e5-8b36-df37220c4d8e.png)

**Comment by zmingxie** [comment]
@zhuzhuor 能不能简单写一下遇到这种情况应该怎么去investigate? 我今早用web inspector稍微看了一下，发现有一个cross-domain 503 error，但不知道应该怎麽再去调试。谢谢！

**Comment by zmingxie** [comment]
新年快乐！

今天早上想看曼联对切尔西，但还是看不了 :disappointed: 

http://sports.letv.com/match/27549003.html#live/1020160203024403

![image](https://cloud.githubusercontent.com/assets/1136583/12873396/cc7cb194-cd89-11e5-9db6-3385a495d64d.png)

**Comment by yanggis** [comment]
在你的代理里面添把以下地址的ur添加到代理就可以正常看了，
"36.110.222.105",//letv
    "36.110.222.119",//letv
    "36.110.222.146",//letv
    "36.110.222.156", //letv
    "123.125.89.6",//letve
    "123.125.89.101",//letv
    "123.125.89.102",//letv
    "123.125.89.103",//letv
    "123.125.89.157",//letv
    "123.125.89.159",//letv
    "123.126.32.134",//letv
    "123.59.122.75",//letv
    "123.59.122.76",//letv
    "123.59.122.77",//letv
    "123.59.122.104",//letv
    "111.206.208.36",//letv
    "111.206.208.37",//letv
    "111.206.208.38", //letv
    "111.206.208.61",//letv
    "111.206.208.62",//letv
    "111.206.208.163",//letv
    "111.206.208.164",//letv
    "111.206.208.166",//letv
    "111.206.211.145",//letv
    "111.206.211.146",//letv
    "111.206.211.147",//letv
    "111.206.211.148",//letv
    "111.206.211.129",//letv
    "111.206.211.130",//letv
    "111.206.211.131",//letv
    "220.181.153.113",//letv
    "14.152.77.32", //letv
    "14.152.77.26", //letv
    "14.152.77.25", //letv
    "14.152.77.22", //letv
    "183.232.229.22",//letv
    "183.232.229.21",//letv
    "183.232.229.25",//letv
    "183.232.229.32",//letv
    "115.182.200.51",//letv
    "115.182.200.50", //letv
    "115.182.200.54", //letv
    "115.182.200.53", //letv
    "115.182.200.52", //letv
    "115.182.63.51", //letv
    "115.182.63.93", //letv

或者你直接在Android设备上安装Chinatunnel.apk，也可以直接解锁。
如果遇到提示版权限制，刷新一下就OK了。

**Comment by zhuzhuor** [comment]
@yanggis 哇塞，你这些 ip 是怎么找到的?

**Comment by zmingxie** [comment]
@yanggis 大神太厉害了，这个果然好使！ :+1: 

@zhuzhuor 感谢你这么快就把patch merged进去!

Closing this issue now
