### ISSUE TITLE
[通知] 有两台服务器又遭到 DDoS 攻击

### ISSUE THREAD

**Issue by zhuzhuor** [Unblocker/Unblock-Youku#591]
刚刚开始又有两台服务器开始遭到 DDoS 攻击
估计是我们开始正面宣传还击，惹恼了一些人吧 :smile: 

应该**不影响扩展程序的整体运行**，等我抽空再增加几台服务器来增加抵抗力
祝大家都开开心心地过个好年，不用为这些烦心事操心

> ![screen shot 2016-02-06 at 11 15 55 am](https://cloud.githubusercontent.com/assets/928905/12868862/4e0c9f5a-ccc5-11e5-8a41-513cda6ab5da.png)
> ![screen shot 2016-02-06 at 11 16 03 am](https://cloud.githubusercontent.com/assets/928905/12868864/516f3f72-ccc5-11e5-9215-143608fdbcdd.png)
> ![screen shot 2016-02-06 at 11 27 09 am](https://cloud.githubusercontent.com/assets/928905/12868865/51828be0-ccc5-11e5-8c2a-ab2f361d73be.png)

**Comment by CoshUS** [comment]
某些人服务器已经死了

**Comment by zhuzhuor** [comment]
就攻击了那么一会，现在已经没有了，这个 issue 就 close 了。（估计之后还会有反扑吧。）
