### ISSUE TITLE
新浪体育直播无法观看

### ISSUE THREAD

**Issue by chenzhekl** [Unblocker/Unblock-Youku#594]
网址： http://video.sina.com.cn/l/pl/sportstv/1702589.html

提示“抱歉，仅限中国境内观看”

**Comment by chenzhekl** [comment]
猜测与这个请求有关：

http://dispatcher.video.sina.com.cn/?resourceid=1798&resourcetype=live&check_forbidden=true&platform=web&appname=flash&appversion=v7.01.2016.02.01.01.lps&sessionid=1702589_1832239212_1455018530630_1358_8092

**Comment by zhuzhuor** [comment]
@chenzhekl 真的是你说的那个 URL，我加上就好了。好奇你是怎么测试的，我平时找 URL 还需要一些经验和技巧。欢迎以后多帮忙 :+1:
