### ISSUE TITLE
Android上bilibili客户端版权视频无法播放

### ISSUE THREAD

**Issue by chenzhekl** [Unblocker/Unblock-Youku#598]
使用Android上的bilibili客户端，基本所有B站购买版权的正版新番都无法播放，提示：

“解析视频地址…［失败］”

类似 @xkk 在 #577 提到的问题，不过分集信息可以获取，只是播放时出现问题。

之后用chrome直接打开bilibili网页测试了一下，同样提示：“非常抱歉，该内容不支持您所在的地区”

---

测试环境：

* 地点：日本
* Android：5.1.1
* PAC：http://pac.uku.im/pac.pac
    * 设置方法：通过系统自己的WiFi设置面板修改
    * uku.im/check测试结果：true
* bilibili客户端：4.11.5
* 测试动画：苍之彼方的四重奏（ http://www.bilibili.com/bangumi/i/3106/ ）

**Comment by yanggis** [comment]
Android系统对PAC文件支持很有限，你有没有尝试安装一下Android系统上的unblock工具试试呢？
https://play.google.com/store/apps/details?id=com.yanggis.chinatunnel

Note for Android L (5.0 & 5.1) :
If you got this error: failed to start proxy (error: only position independent executables(pie) are supported.
You can bypass the new PIE security check to fix it.
What you can do: 
0) download the new linker file from here (http://forum.xda-developers.com/google-nexus-5/development/fix-bypassing-pie-security-check-t2797731);
1) copy the new linker file to external storage (while backing up the original one, very important!!!);
2) reboot to recovery;
3) copy the new linker over the original one in /system/bin;
4) fix permissions (chmod 755 linker) and group ownership (chgrp shell linker);
5) reboot.

You can also fix it based on adb command:
0) download the new linker file from here (http://forum.xda-developers.com/google-nexus-5/development/fix-bypassing-pie-security-check-t2797731), put the new linker file into the same folder as your adb tools;
1) execute these commands:
adb shell
mount -o remount,rw /system
mv /system/bin/linker /system/bin/linker.old
push linker /system/bin/linker
chmod 0755 /system/bin/linker
mount -o remount,ro /system
2) reboot.

**Comment by chenzhekl** [comment]
@yanggis 

这次的问题和Android对PAC的支持应该没有太大关系。Chrome里用uku.im/check测试，PAC是生效了的，那么在Chrome里打开bilibili理应没问题，问题是也提示版权受限。

**Comment by yanggis** [comment]
那就不清楚了，不过据我所知，最近PAC文件应该没有什么改动啊。

**Comment by p1580** [comment]
剛試用了一下 pac是可以執行的！！ 看了您給的苍之彼方的四重奏

**Comment by chenzhekl** [comment]
@p1580 请问您是如何设置的，我在android和iOS上测试都得到同样的结果。

**Comment by p1580** [comment]
@chenzhekl android的Drony設置 pac 就可以使了...

**Comment by chenzhekl** [comment]
@p1580 用Drony确实就行了，好神奇…实际原因没有测过，估计是 #577 @mc16888 说的那样，bilibili会绕过PAC设置。而Drony创建了一个全局VPN，这样谁都没法绕出来。姑且算是解决了，close掉这个issue。
