### ISSUE TITLE
检查 Node.js v5 的测试 fail 的问题

### ISSUE THREAD

**Issue by zhuzhuor** [Unblocker/Unblock-Youku#602]
不知道最近这 test 为啥总 fail，而且总是 Node.js v5 fail，可能是在 v5 上我们的代码有点不兼容问题
https://travis-ci.org/Unblocker/Unblock-Youku/builds/110576892

**Comment by zhuzhuor** [comment]
我在我的本地电脑上不能 reproduce，先把 node v5 从 travis 的测试里删掉了
如果有人能 reproduce，我们看看这到底是什么问题

**Comment by Gisonrg** [comment]
刚正在看这个，加了print debug message然后自己搭了travis跑了一下，发现有的时候会报错
[```http://127.0.0.1:8888/crossdomain.xml: Connection refused```](https://travis-ci.org/Gisonrg/Unblock-Youku/jobs/110879273#L322)

然后又发现基本上failed的build 都是在开始跑第一个test开始之后才显示```Worker xxx is now connected to 0.0.0.0:8888```。怀疑是不是开始跑test了但是server还没有set up好的问题。

所以给```run_all_tests()```多加了3秒sleep好像就可以了。。。见[travis build](https://travis-ci.org/Gisonrg/Unblock-Youku/jobs/110881022)

**Comment by zhuzhuor** [comment]
@Gisonrg 这... 难道是 travis-ci 上的服务器压力太大，服务器启动速度慢么
你觉得有啥万全的解决办法吗，比如测试 127.0.0.1:8888 的 status，直至 open 了再开始测试吗？当然还得有个时间限制比如 10 秒之类的

**Comment by Gisonrg** [comment]
@zhuzhuor 
可以在`run-all-tests.py`里写一个`wait_server_open()`function来不断地connect到127.0.0.1:8888的socket，来检测服务器是否启动好了, 用一个10-20秒的timeout，如果socket可以访问了return true,说明可以连接了（不出意外地话15秒之内应该可以连接上）
`start_server()`之后call这个`wait_server_open()`，确认server已经running了再继续接下来的`run_all_tests()`
这是我觉得现在可行的一个方法(稳定性未知), 不知道有没有更好的解决方法
[travis sample run](https://travis-ci.org/Gisonrg/Unblock-Youku/builds/111149518)

**Comment by zmingxie** [comment]
@zhuzhuor 好奇问一下，为什么你把这里的header comment了？ https://github.com/Unblocker/Unblock-Youku/blob/master/test/test-crossdomain-xml.js#L11

我在本机用 PhantomJS 2.1.1 发现 `console.log(page.content)` return this:
```
[ub.uku.js] 127.0.0.1: GET /crossdomain.xml
<?xml version="1.0" encoding="UTF-8"?><cross-domain-policy><allow-access-from domain="*"/></cross-domain-policy>
test-crossdomain-xml.js passed.
```

Uncomment the header fixes the failure for me

**Comment by zhuzhuor** [comment]
@zmingxie 多谢帮忙！
我不记得了，但是现在用的 phantomjs 1.9 的测试没问题，就说明对旧版本的 phantomjs 那行其实是没有在 page.content 里？
不过看我一楼的 link，貌似出问题的 build 也是用的 phantomjs 1.9，所以说明不是你说的这个问题

**Comment by Gisonrg** [comment]
@zmingxie 
Travis 上头用的是PhantomJS 1.9.8，而且log出来是不带xml tag的（可能跟PhantomJS 1.9.8的版本有关？），所以貌似注释掉在travis上才是对的（我自己电脑上的2.1.1和你一样的结果）
所以failuare我觉得还是跟connection有关

**Comment by zmingxie** [comment]
@zhuzhuor and @Gisonrg 你们说的对，这个的确跟PhantomJS版本没有关系。我自己刚在TravisCI试了一下，force PhantomJS to 2.1.1还是解决不了这个问题：https://travis-ci.org/zmingxie/Unblock-Youku/builds/111928036#L337

另一方面，如果我re-enable 之前的163 test，整个test run就没问题了：https://travis-ci.org/zmingxie/Unblock-Youku/builds/111927462#L321 这个跟之前 @Gisonrg 说的也敏合
