### ISSUE TITLE
有人反馈说腾讯体育的直播不是很稳定

### ISSUE THREAD

**Issue by zhuzhuor** [Unblocker/Unblock-Youku#603]
比如这个网址 http://kbs.sports.qq.com/#nba
我试了几个直播的链接，但是都还没开始直播，只能到时间再试
先记录下来

**Comment by yanggis** [comment]
昨天晚上德甲直播就是很卡，刚才NBA直播也是不稳定，超级慢，好像是腾讯海外的CDN服务器有问题了。我用乐视体育看其他的体育赛事就挺顺畅的。

**Comment by zhuzhuor** [comment]
@yanggis 多谢你的信息，就是说可以看但是很卡很慢是吗？

**Comment by yanggis** [comment]
是的，能看，很卡。

**Comment by zhuzhuor** [comment]
@yanggis 你这也是体育粉丝 :+1: ?

**Comment by yanggis** [comment]
@zhuzhuor，我看西甲和英超……
