### ISSUE TITLE
芒果 TV 不能观看

### ISSUE THREAD

**Issue by zhuzhuor** [Unblocker/Unblock-Youku#604]
用户在 Google Group 里面提的 https://groups.google.com/forum/#!topic/unblock-youku/sf61Cjuj4YY
我试了一下的确是这样，例如 http://www.mgtv.com/v/2/158219/f/2988456.html

> ![screen shot 2016-02-22 at 10 32 31 pm](https://cloud.githubusercontent.com/assets/928905/13243522/52aab456-d9b4-11e5-9230-20ea13e7d89a.png)

**Comment by zhuzhuor** [comment]
已经在最新版修复，正在 push 给 chrome web store

**Comment by mc16888** [comment]
@zhuzhuor iOS 芒果TV apps 最新版還要加這一個URL
http://mobile.api.hunantv.com/v5/video/getSource?

另外 微播裡 mc16888 不是我.

**Comment by zhuzhuor** [comment]
@mc16888 多谢！欢迎直接提交 pull request

你有微博帐号吗？或者有别的名字方便称呼你吗

**Comment by mc16888** [comment]
@zhuzhuor 沒有, 用mc16888 就可以了.
