### ISSUE TITLE
修改极路由的自定义hosts插件未能翻墙看优酷等

### ISSUE THREAD

**Issue by fimmugit** [Unblocker/Unblock-Youku#605]
我用的是极路由(有线与cable modem直连)，其提供了自定义hosts插件，可以设置如下：
192.241.222.103    a.play.api.3g.youku.com
192.241.222.103    access.tv.sohu.com
192.241.222.103    api.3g.tudou.com
..............

但重启后，经IE测试ipservice.163.com/isFromMainland，为false. 电视盒(芒果嗨Q5)播放美剧显示有版权限制。但用chrome+unblock uku则为true，可用搜狐播美剧。请问我是否有什么地方做的不对？

**Comment by whuhacker** [comment]
@fimmugit 在电脑命令行下运行 `dig ipservice.163.com` 看结果是不是你设置的 `192.241.222.103` ？

**Comment by yanggis** [comment]
DNS好像搜狐视频看不了，QQ音乐用不了，乐视体育直播也看不了，

android设备要是有root权限，就直接安装这个软件
https://play.google.com/store/apps/details?id=com.yanggis.chinatunnel
保持它后台运行，基本什么视频都可以看了。

**Comment by fimmugit** [comment]
谢谢回复！@whuhacker nslookup ipservice.163.com 我查过了，没问题。@yanggis 我google了root的办法，也尝试过root这个芒果嗨盒子，但听说海美迪封死了root的可能，没有成功。

我在另外的华为盒子上，试了试搜狐的一个美剧视频，可以放（说明此办法可行？），但优酷的还是说版权问题。不知优酷是怎样判断我的盒子是国内还是国外？除了IP还有header? 你们有没有有关优酷视频的链接？也许我的设置中少了些东西。

**Comment by fimmugit** [comment]
我刚试过，搜狐的美剧在芒果嗨上用破解版搜狐app也能看。奇怪的是，优酷的同一部片在优酷破解版看不了，但在魔力app上（注意，是优酷源）可以放。

**Comment by Migflyway** [comment]
好像是算出播放地址的问题。我曾经用硕鼠获取了一个优酷的视频播放地址 m3u8格式，下载下来后直接就可以用播放软件播放。不知道是不是这方面的问题，

**Comment by fimmugit** [comment]
另外，修改DNS的办法似乎对B站(bilibili.com)，1905.com， 爱奇艺等不灵，盒子上看不到B站的视频，IE上也load不了，但chrome+unblock uku则可以看，请教一下，unblock uku是如何解决B站视频播放的问题的？

@Migflyway 播放地址是一种可能性，此外，会不会优酷app本身有侦测客户端IP的功能并将IP转发给服务器来判别？

**Comment by Migflyway** [comment]
我的极路由是装ss。自己在国内有台服务器。 
你可以试试装 ss 翻墙。翻回国内，可以自定义域名。

**Comment by Migflyway** [comment]
@fimmugit ，我一般用vts，其他的没用过。感觉vts速度还行。

**Comment by fimmugit** [comment]
@Migflyway， 您是指SSH? 国内弄个服务器比较麻烦，我觉得可能不值得折腾。现在自己也装了好几个其他app，其实也没那么多时间看视频，主要是有时打开一些视频看不了而觉得不爽。

似乎不同的视频提供商有不同的方法检测国外的用户。修改DNS可能只是一种方法，目前也不想刷openwrt来实现自动转。不过我真想知道unblock uku实现解锁B站等的工作原理，再决定下一步该如何干。

**Comment by fimmugit** [comment]
@whuhacker 昨天检查还好好的，今天不一样了：
nslookup ipservice.163.com返回
Server:  resolver1.dyndnsinternetguide.com
Address:  216.146.35.35

Non-authoritative answer:
Name:    ipservice.163.com
Address:  223.252.199.5

**Comment by yanggis** [comment]
把你的盒子的DNS设置成104.236.189.178试试。

**Comment by heyggu** [comment]
@yanggis 你好，有ipv6的DNS吗？

**Comment by yanggis** [comment]
有，但是IPV6的DNS估计不行吧？需要相应的代理配合才行……要不然只有DNS什么用也没有……。

**Comment by fimmugit** [comment]
@yanggis 按照您给的IP, 更改了路由的自定义hosts中的DNS, 原来不能看的B站等似乎都可以了，但用优酷app直接看的话，还必须将盒子wifi的DNS也改为104.236.189.178才行。估计优酷app本身也有验证？

另外，我ping不通192.241.222.103， 但ping104.236.189.178没问题。希望此服务器能稳定吧！

在此，再次感谢@yanggis 和其他朋友的帮助！

**Comment by yanggis** [comment]
ping通和ping不通是服务器响应不响应你的ping包而已，和服务器能不能使用时两码事，anyway, 能用就好了，104.236.189.178现在用的人太多，压力比较大，也有点扛不住了……。

**Comment by heyggu** [comment]
@yanggis 恩，我这儿是教育网ipv6环境

**Comment by Migflyway** [comment]
@yanggis 我这里有服务器，可以捐一个。美国的可以不？

**Comment by yanggis** [comment]
@Migflyway,谢谢，美国的也行，等我这一段忙完，可以和你一起合作搭建一个新的服务器。

**Comment by zhuzhuor** [comment]
@yanggis 你想也帮忙维护 192.241.222.103 的服务器一下吗
因为我对 DNS 这套系统不怎么懂，最开始一直由 @karlcheong 全权负责，之后又交给 @whuhacker 维护
你这么活跃和热心，可以帮忙和 @whuhacker 一起搞搞这个 DNS？感觉你的  DNS 更新要快一些

**Comment by Migflyway** [comment]
@whuhacker 好的，你到时联系我就好。

**Comment by whuhacker** [comment]
@Migflyway 你在 Gitter 上吗？

**Comment by Migflyway** [comment]
@whuhacker at 错了。sorry

**Comment by Migflyway** [comment]
@yanggis 你有空了，联系我就好。

**Comment by yanggis** [comment]
@zhuzhuor,可以啊，反正就是两个DNS配置文件copy一下保持一致就好了。

**Comment by yanggis** [comment]
@Migflyway，非常感谢。

**Comment by zhuzhuor** [comment]
@yanggis 好，多谢。我跟 @whuhacker 找找服务器的登录方式吧

**Comment by yanggis** [comment]
@zhuzhuor，好的，到时候我登陆上去把我的配置文件copy上去应该就OK了。

**Comment by zhuzhuor** [comment]
@yanggis 你有什么私下的联系方式吗，用户名密码好给你。或者我们上 gitter?

**Comment by yanggis** [comment]
好的，你gitter上留言给我，我应该就能看到了，有问题我再回复你。

**Comment by zhuzhuor** [comment]
@yanggis 已发

**Comment by yanggis** [comment]
@zhuzhuor,看到了，谢谢，我周末准备把DNS弄一下。

**Comment by Migflyway** [comment]
@yanggis   什么配置的服务器可以？还有流量。

**Comment by yanggis** [comment]
@Migflyway，配置要求不高，一个树莓派足以，流量一个月100G就足够了。

**Comment by Migflyway** [comment]
@yanggis ,什么系统你比较偏向呢？我开通好，发给你。

**Comment by yanggis** [comment]
@Migflyway 谢谢，Ubuntu就可以了。

**Comment by Migflyway** [comment]
@yanggis 已发，两台哈。

**Comment by yanggis** [comment]
@Migflyway,谢谢， 已经收到了。我正两天在忙一个数据分析，弄完马上开始配置。

**Comment by fimmugit** [comment]
我有一个问题不明白，想请教一下：
我设置了路由的自定义hosts指向104.236.189.178（针对以下每种情况都一样），
使用情景1）用电脑chrome/猎豹浏览器看优酷美剧时正版播放连接是不会出来的，打开unblock uku就可以了；
使用情景2）用电视盒有线直接连路由，DNS也手动设置成104.236.189.178，这时，可以看搜狐美剧，但看不了优酷或腾讯美剧；
使用情景2）用电视盒无线连路由，DNS也手动设置成104.236.189.178， 这时可以看搜狐，腾讯和优酷美剧。

是什么原因造成这些差别？

**Comment by yanggis** [comment]
1.种情形，很显然问题出在你的hosts文件里定义不完整，比如搜狐美剧需要一个link是hot.vrs.sohu.com，如果你没加入这个link,搜狐美剧在1情况下，就看不了，优酷也是一样的。
2.种情况稍有不同，因为有线网在android上属于后来开发商加进去的，没有测试过，但是估计是这个有线网软件有问题或者IPV6造成的，因为没有对IPV6的link进行unblock,如果用优酷视频使用了IPV6验证，那显然就通不过，就播放不了。但是这个我没测试，不确定。
最后一种情况显然就是一般的Android设备的办法，基本上都可以看搜狐，腾讯和优酷视频，因为这个方法没有使用你路由器的hosts，所以即便是你路由器hosts定义不完整，也可以播放，但是应该不能看乐视体育，不能用QQ音乐等依赖IP验证的视频网站。如果想最终解决这2个问题就只能安装chinatunnel.apk。Goolge play里可以搜索安装。

**Comment by fimmugit** [comment]
谢谢！我再体会一下。

**Comment by fimmugit** [comment]
@yanggis 关于第一情形，我发现我一台PC上手动改了DNS，我把它换回自动获取，无线连上路由，就能上优酷，无需unlock uku，因为路由已修改hosts DNS。ipservice.163.com/isFromMainland检查为true。也就是说我的设置已被认为是国内IP。

用电视盒子无线连接路由，ipservice.163.com/isFromMainland检查为true。也就是说我的设置已被认为是国内IP。此时看搜狐没问题，用其他apk看腾讯，优酷源的视频也能看，但用腾讯的企鹅apk或优酷的CBIN-优酷apk看视频仍然显示有版权问题，必须要更改wifi的DNS才能看。这是否说腾讯的企鹅apk或优酷的CBIN-优酷apk可能存在与PC端不同的IP检查机制？譬如这些apk可能绕过了路由中的设置而将盒子本地的海外IP发送给其服务器？

此外，假设路由已设置代理DNS， 盒子与路由通过wifi或网线连接有区别吗？

**Comment by fimmugit** [comment]
Ok, 终于找到原因，原来是PC上设置的DNS作怪，改为自动获取后，其他不变，现在盒子有线无线都能接收了。可能是原来的DNS被强制为其他地区的IP,所以没有通过IP检验。

**Comment by yanggis** [comment]
@Migflyway, 45.32.72.192那个DNS服务器我配置好了，你可以测试一下。但是108的IP的那个好像一直处于down机状态，连不上啊。

**Comment by Migflyway** [comment]
@yanggis ,我重新弄一个。我刚连了下，也连不上。

**Comment by Migflyway** [comment]
@yanggis 好了哈。你试试。

**Comment by yanggis** [comment]
@Migflyway，刚才试了可以登录，我这两天会把这个也弄一下。

**Comment by zhuzhuor** [comment]
@yanggis @Migflyway 有人有空可以整理下我们现在一共有的 DNS 服务器吗，另外写个简单的各平台的设置办法？
可以写成 github wiki，然后以后可以指引用户去设置。现在的设置还有 IP 都分散在好几个 issues 里

**Comment by Migflyway** [comment]
@zhuzhuor , 两台服务器还有一台没有弄完。弄完我整理哈。

**Comment by yanggis** [comment]
@Migflyway,明后天我就可以弄完，这两天我在测试一个代理软件，明后天应该就可以把2个服务器都弄好了。

**Comment by Migflyway** [comment]
@yanggis 好的，了解。

**Comment by luohancfd** [comment]
有个768mb 月流量1t的vultr vps，用来放自己的博客（基本没流量），愿意提供资源做dns服务器，有域名，就是不知配置够不够。。

**Comment by yanggis** [comment]
@luohancfd，非常感谢，现在DNS的问题比较缺的是国内的服务器，因为DNS其实是国外VPS和国内代理协同工作的，仅仅依靠国外一个VPS是没法完成unblock的。@Migflyway前几天刚好心提供了两台国外的VPS，这两天在配置。现在DNS应该基本够了。再有需求的话，再麻烦您哈。

**Comment by gulizi** [comment]
@karlcheong @zhuzhuor 
karlcheong 的unblock youku privoxy rules怎么找不到了？

**Comment by fimmugit** [comment]
我的hosts指向104.236.189.178， 今天查ipservice.163.com/isFromMainland, 返回为false， 视乎失效了。 大家有问题吗？

**Comment by yanggis** [comment]
用新的DNS服务器
https://github.com/Unblocker/Unblock-Youku/issues/618
先测试下哪个速度快，再设置一个适合你的DNS。

**Comment by fimmugit** [comment]
@yanggis 谢谢！试用了几个服务器，都不行。浏览器用插件查ipservice.163.com/isFromMainland, 返回为true，访问优酷没问题，但不能播放网易云音乐。插件用的是哪个服务器？

**Comment by yanggis** [comment]
网易云音乐的问题你要看这个https://github.com/Unblocker/Unblock-Youku/issues/488

**Comment by fimmugit** [comment]
明白。我想问问unblock youku是否用了其他服务器？谢谢！ 

    On Monday, March 14, 2016 8:01 PM, X.K. YANG <notifications@github.com> wrote:
 

 网易云音乐的问题你要看这个#488—

**Comment by yanggis** [comment]
@fimmugit  你说的用其他的服务器是什么意思呀？

**Comment by fimmugit** [comment]
@yanggis 我设置和测试了104，和45服务器，都不行， 但unblock uku却可以，所以我才问是否unblock uku所用的服务器有所不同？

**Comment by fimmugit** [comment]
今天早些时候测试158有问题，现在貌似好了。

**Comment by fimmugit** [comment]
高兴过早，158还是不行。点的是过去点过的两部美片，可能cached了的原因，出来可以播放，但点击优酷其他电影就不行了。

**Comment by yanggis** [comment]
先看看这个
https://github.com/Unblocker/Unblock-Youku/issues/618#issuecomment-196618500

**Comment by fimmugit** [comment]
今早测试， 45恢复， 坐标美东。

**Comment by fimmugit** [comment]
请问有什么方便的方法测试哪个服务器能用？我现在是一个一个的在hosts文件里试用，然后再运行http://ipservice.163.com/isFromMainland看看返回值，这样的效率不高。

**Comment by yanggis** [comment]
😓！这个不需要一个一个去试啊，直接用那三个DNS就行了！只要不被攻击，三个服务器都是24小时在线的。

**Comment by fimmugit** [comment]
@yanggis 请问104， 192是否作废了？我准备root我的盒子，装ChinaTunnel， 希望能解决稳定性问题。

**Comment by yanggis** [comment]
@fimmugit 104， 192彻底作废了。稳定性DNS和ChinaTunnel都差不多，就是ChinaTunnel是客户端软件，可控制的东西更多一些，比如DNS上看不了搜狐视频，听不了的QQ音乐等用ChinaTunnel都可以解决。

**Comment by yanggis** [comment]
@fimmugit 盒子的root操作在taobao上找卖家帮你弄一下就OK。

**Comment by fimmugit** [comment]
@yanggis 谢谢你们的辛勤劳动！！！

**Comment by fimmugit** [comment]
@yanggis 极路由自定义hosts加上三个服务器指向，盒子已经root过了，China Tunnel也装上，一般情况下，使用正常。

使用心得：进入China Tunnel设置后，如按遥控返回键，会关闭Tunnel， 我用返回首页即可。单用路由Hosts+腾讯视频app(检查确认为国内IP），还有版权问题，打开Tunnel就好，可能是app本身还有IP检查。

**Comment by yanggis** [comment]
@fimmugit, ChinaTunnel的使用方法是，第一次使用要选上开机自动启动，然后更新whitelist，开启Chinatunnel以后，直接按Home键回到主界面，就不用管它了。
以后盒子启动的时候ChinaTunnel会自动启动，启动的时候自动更新whitelist。也就是说你就彻底不用管它了。
当然你要几个月盒子都不关机，就要自己打开chinatunnel更新一下whitelist。
DNS只能解锁一部分视频网站，对于基于IP的验证DNS解锁是无能为力的，所以有些视频用DNS后看不了也是正常的。
