### ISSUE TITLE
iOS 的http代理被自动关闭

### ISSUE THREAD

**Issue by asuka0819** [Unblocker/Unblock-Youku#606]
不知道有没有人和我一个问题，不管DNS修改还是http代理修改，退出界面回去还是回到原来的界面，网络还原好多次都不行，不知道是什么情况。我的是iOS 9.2.1

**Comment by Migflyway** [comment]
是不是你无线网络的问题。

**Comment by zmingxie** [comment]
I don't think this is related to Unblock-Youku. Do you have any VPN clients installed on your iPhone/iPad?

**Comment by tywtyw2002** [comment]
IOS 网络有一些bug，你尝试一下重置下i设备的网络设置。

**Comment by asuka0819** [comment]
@tywtyw2002 试过还原很多次了都没办法
