### ISSUE TITLE
新手入门求解答

### ISSUE THREAD

**Issue by KanVivii** [Unblocker/Unblock-Youku#608]
感谢大大创造了这个无敌的插件 造福了大家 谢谢拉

用Unblock Youku好久了 可是最近突然对这个插件的工作原理感兴趣

在wiki里看到了一些教程但是都是centos的完全不会
对这些并没有基础

所以想问问Unblock Youku的工作原理是什么 
还有就是有没有可能性用windows平台来继续开发

**Comment by jazzyMix** [comment]
我也是刚刚过来学习一个的，对这个项目表示感谢

**Comment by tommyzhaozbh** [comment]
绝大部分的网站都有一些专门用来检测地址的链接，一般这些链接比较固定不会随意改。而这插件的原理就是:通过修改 http header ，欺骗服务器使其误以为用户来自大陆，或者是代理一些需要检测地址的链接使服务器返回来自大陆的结果。这个插件的运作，不仅要有用户端的插件，还要有国内的代理服务器(一般是一个squid 服务器)。

**Comment by zhuzhuor** [comment]
@KanVivii @jazzyMix 多谢你们感兴趣！有机会请多参与我们的开源项目

基本上就像 @tommyzhaozbh 所说的，用技术手段解决一些网站/网络的限制
可以是修改 HTTP header，也可以是用代理服务器

在什么电脑平台上都可以开发
需要会一点 JavaScript，不用会太多。不会的话推荐这本书 http://www.amazon.com/JavaScript-Good-Parts-Douglas-Crockford/dp/0596517742
然后有 Chrome 的官方 dev guide https://developer.chrome.com/extensions/getstarted
我最近在写个 contributing guide，也会对我们的项目架构简单介绍下

**Comment by KanVivii** [comment]
@zhuzhuor @tommyzhaozbh 感谢大大的帮忙拉  
开始慢慢学习

**Comment by KanVivii** [comment]
@tommyzhaozbh  @zhuzhuor 哦对了 我还想大家加一波微信 弄个微信群 交流起来方便多了

**Comment by KanVivii** [comment]
哦对了 你们的国内服务器都是哪个公司的 美团阿里云这些都要备案诶

**Comment by KanVivii** [comment]
大神们加波微信吧 531414872 不知道大家喜不喜欢一起弄个微信群

**Comment by zhuzhuor** [comment]
@KanVivii 美团云非 80/443 端口应该是不用备案，阿里云非 80/443 端口用 TLS 应该不用备案。当然，如果你有备案的条件的话推荐备案一个吧，能省去不少麻烦

多谢你创建微信群，但是希望这些技术知识和问题能够公开地交流，方便更多的新人来学习和参考

**Comment by KanVivii** [comment]
@zhuzhuor 我昨天买的腾讯云试了一下 不需要备案 而且80 443接口也都可以用

**Comment by KanVivii** [comment]
谢谢各位大大 这跟我就关啦

**Comment by zhuzhuor** [comment]
@KanVivii 多谢你的这个信息！

我没有用过腾讯云，有空的话你能帮忙写个腾讯云的购买和设置流程吗？

**Comment by KanVivii** [comment]
小弟不才 我也是个新手 不过我慢慢研究 开始写流程

**Comment by KanVivii** [comment]
![image](https://cloud.githubusercontent.com/assets/15619803/13682234/ec4135b4-e6ce-11e5-8076-8d40399ca925.png)
想问一下在最后运行cronteb之后的最后一步该怎么做 不知道在哪里添加最后那个内容

**Comment by yanggis** [comment]
你在命令行里输入 crontab -e，然后会进到计划任务crontab编辑界面，
里面会有很多#开头的comments，在这些comments之后添加 1 1 * * * python /opt/update.py就好了。

**Comment by KanVivii** [comment]
@yanggis 对centos这种系统不是太懂 如果移植到windows需要从哪里入手

**Comment by yanggis** [comment]
@KanVivii 移植到windows基本没可能哦。因为很多软件windows都没有。

**Comment by KanVivii** [comment]
![image](https://cloud.githubusercontent.com/assets/15619803/13719129/593b7a6c-e7bf-11e5-8acd-c184b36a6f7b.jpeg)
那俩软件windows貌似是没有 但是我搜到一些这种替代的 不知道可不可以用差不多的原理 @yanggis

**Comment by yanggis** [comment]
这个我没用过不知道，但是我建议你用Linux,Windows当服务器，真不是一个好办法，长期运行，光稳定性就是一个大问题。到最后你还要换到Linux上，还不如一步到位呢。

**Comment by KanVivii** [comment]
@yanggis ![1](https://cloud.githubusercontent.com/assets/15619803/13833402/85e25a4e-ec20-11e5-9075-613b4dcaf41f.png)
不知道下一步是什么 在哪里添加1 1 * * * python /opt/update.py这个

**Comment by yanggis** [comment]
@KanVivii  就在那个绿色的光标那里添加就可以了。

**Comment by zhuzhuor** [comment]
@yanggis 他应该是想问编辑器怎么用，默认的应该是 VIM

@KanVivii 点击 `i` 进入编辑模式可以写东西，写完了点击`ESC`退出编辑模式，然后按顺序输入`:wq` 回车保存退出

**Comment by zhuzhuor** [comment]
我把 wiki 里的教程改了，强制用 nano 作为编辑器，这样新手应该好弄些
