### ISSUE TITLE
乐视体育直播缓冲一会就无速度

### ISSUE THREAD

**Issue by leening3436** [Unblocker/Unblock-Youku#609]
使用unblock youku观看其他网站均没问题，只有乐视体育直播，打开时缓冲很快，看个一分钟左右就没速度了，很卡，怎么解决呢？

**Comment by leening3436** [comment]
补充一下，同样的网络环境，ipad上面就很流畅，使用chinatunnel在安卓手机解锁看乐视体育直播也很流畅

**Comment by zhuzhuor** [comment]
@leening3436 多谢反馈！我们试试看 

@yanggis @tommyzhaozbh 手机上看乐视体育和电脑上的服务器地址区别很大吗

**Comment by yanggis** [comment]
应该是用的不一样的服务器吧，Chinatunnel是用的北京的联通的IP，所以感觉会好点。

**Comment by prettypig2006** [comment]
的確...用unblock youku收看樂視体育直播會一直遇到緩衝或是掉線問題, 
若使用Dnsmasq + privoxy 用於安卓手机, PC連上樂視体育直播網站以及机頂盒進入樂視網直播收看 或是 ChinaTunnel 用於安卓手机看樂視視頻体育直播都可以很流暢的...

順帶一提, 由於實驗測試心裡的作祟下, 買了一台樂視盒子NEW C1S 運營商版(海外版), 在相同Dnsmasq + privoxy 架構下, 進入樂視盒子內建的"Letv樂視網TV版"去收看直播會出現版權問題而無法收看!!!
但我有在樂視盒子上額外安裝"電視家瀏覽器"APK, 從它進入樂視網直播是沒問題的.
看來, 利用不同的窗口進入使用的是不相同的服務器.

**Comment by yanggis** [comment]
@prettypig2006 直播的问题的确有点复杂，不过如果乐视不流畅的话，建议你试试腾讯体育，虽然没有詹俊那样的英超解说名嘴，不过他们提供的英超，德甲，欧冠和NBA直播节目还是挺多的。

**Comment by prettypig2006** [comment]
好的, 謝謝您的建議~~偶爾也有使用腾讯体育

提供另一測試下的補充說明~
由於習慣常常使用"電視家"APK來收看体育頻道,   在@yanggis的協助開發下使用ChinaTunnel來收看電視家裡頭的任一体育頻道(該体育頻道是連接至Letv的)是可以解鎖正常的, 
而高爾夫大滿貫/美巡賽/歐巡賽三個頻道本身是沒有海外IP限制直接可收看!

但若是使用DNSmasq +  privoxy架構還是沒法接收上述需解鎖的体育(從電視家, 該頻道是連接至Letv的), 會一直停留在緩衝中...

![screenshot_2016-03-24-14-47-01](https://cloud.githubusercontent.com/assets/17976341/14011822/7bf20914-f1dc-11e5-8b73-3518299a2f16.png)

![screenshot_2016-03-24-14-47-51](https://cloud.githubusercontent.com/assets/17976341/14011843/9069e506-f1dc-11e5-89aa-5facb573b967.png)

![screenshot_2016-03-24-15-42-57](https://cloud.githubusercontent.com/assets/17976341/14011855/ab5a279a-f1dc-11e5-939c-131ac9e79516.png)

![screenshot_2016-03-24-14-47-01](https://cloud.githubusercontent.com/assets/17976341/14011856/b18ed21e-f1dc-11e5-831a-432adb83b9e0.png)

**Comment by yanggis** [comment]
@prettypig2006, 乐视的视频源里面有基于IP的验证，这个就绕过了DNS解锁，这是反制DNS解锁的一个有效手段，所以DNS解锁就没办法了。
ChinaTunnel是对所有需要解锁的link不管是就基于domain的还是基于IP的，在没有发送出你的android设备之前都进行了拦截，强迫他们走代理，所以才会有效。

**Comment by prettypig2006** [comment]
@yanggis 理解了, 謝謝你對於Unblock Youku網路規則架構的解析, 也讓我更瞭解並加深了此設計概念...

既然DNSmasq + privoxy還是會遭遇到無法解鎖問題下, 決定不再糾結....
就把我已ROOT的海美迪机頂盒以及樂視盒子NEW C1S安裝上你開發的程式ChinaTunnel, 一勞永逸地解決部份頻道無法收看問題, 使能暢遊於体育視頻了!


BTW, 為了表達個人內心對於Unblock Youku的支持, 不吝嗇地造福海外同胞們...
昨日盡了一點微薄力量的小額捐款以協助Server運行, 期望你們能持續維持下去, 是小而堅實的Unblock Youku.

謝謝~

**Comment by yanggis** [comment]
@prettypig2006 :+1: 感谢对unblock-youku的支持。

**Comment by zhuzhuor** [comment]
@prettypig2006 非常感谢你的支持！
