### ISSUE TITLE
Donation link returns 404

### ISSUE THREAD

**Issue by JiYangE** [Unblocker/Unblock-Youku#610]
https://www.uku.im/donate_zhs.html

<img width="712" alt="screen shot 2016-02-28 at 3 05 36 pm" src="https://cloud.githubusercontent.com/assets/14886380/13382224/78b81388-de2c-11e5-8334-b315a2cd72bf.png">

**Comment by zhuzhuor** [comment]
@JiYangE 多谢，你这是从  CONTRIBUTING.md 文件里发现的吗？我弄了个 typo，应该是 https://www.uku.im/index_zhs.html 也不是 donate_zhs.html

**Comment by JiYangE** [comment]
嗯是 CONTRIBUTING.md 别的地方没有发现

**Comment by zhuzhuor** [comment]
@JiYangE 非常感谢帮忙！
