### ISSUE TITLE
爱奇艺播放不稳定

### ISSUE THREAD

**Issue by zhuzhuor** [Unblocker/Unblock-Youku#612]
看到有用户在微博上反馈，说爱奇艺今天不是很稳定
我试了下的确这样，例如这个视频 http://www.iqiyi.com/v_19rronkqyo.html
会出现播放失败，然后刷新一下就好了

另外最近有感觉国内一些网站突然特别很慢，看晚上有人说最近的大陆的国际出口又出什么问题了
有人有感觉类似的问题吗？

**Comment by klib9739** [comment]
台灣IP無unblock直接觀看這視頻
很順暢
但愛奇藝在台灣應該是有CDN還是什麼之類的
視頻實際指向的IP都是ISP業者自家的IP

然後台灣連大陸本來就不是很穩
所以第2個問題無法測試

**Comment by zhuzhuor** [comment]
今天又测试了爱奇艺的这个视频 http://www.iqiyi.com/v_19rronib6w.html

仔细观察发现，首先会去类似

```
http://data.video.qiyi.com/videos/v0/20150714/5b/7f/... 
```

的网址获取数据服务器的信息

> ![screen shot 2016-03-02 at 10 13 18 pm](https://cloud.githubusercontent.com/assets/928905/13486284/4f02cf7a-e0c4-11e5-98f2-a470270e96ef.png)

但是获得的 IP 地址例如
```
http://111.206.23.147/videos/v0/20150714/5b/7f/57f17562bb39f3e765fce23b7811b5c6.f4v...
```
经常打不开，说 Not Allowed

是爱奇艺的 CDN 有什么权限控制的问题吗？

**Comment by zhuzhuor** [comment]
今天有很多人反馈，比如这个视频  http://www.iqiyi.com/v_19rrkxmiss.html
我自己试了试也是这样的

使用扩展程序的代理时会出现
> ![screen shot 2016-03-03 at 8 58 50 pm](https://cloud.githubusercontent.com/assets/928905/13518956/e6c3cdc8-e187-11e5-962e-60e5a1e4e9fb.png)

在北美地区，不使用代理就会出现
> ![screen shot 2016-03-03 at 8 56 56 pm](https://cloud.githubusercontent.com/assets/928905/13519016/42bc5956-e188-11e5-9e42-3da9e9ce0bed.png)

但是香港地区不用代理就可以直接播放

而且这问题出现得比较随机，有时有错误有时没有

**Comment by KanVivii** [comment]
对对对就是这样 但是使劲刷新几遍之后有的就能正常播放

**Comment by laozhangyu** [comment]
希望能赶紧解决。特意注册了来坐等消息

**Comment by EddieSong92** [comment]
这两天爱奇异的视频都看不了，不管怎么刷新都一样、本人在英国、专门注册来等待解决

**Comment by cheroooo** [comment]
我就连刷新也没有用LOL 希望creator可以尽快改善！辛苦你啦

**Comment by KanVivii** [comment]
我今天刷新也不行了 我要是能懂这个项目就好了 就可以研究一小下了

**Comment by yanggis** [comment]
把你的DNS设置成104.236.189.178试试呢？

**Comment by inter310** [comment]
请问，这个问题现在解决了吗？

**Comment by zhuzhuor** [comment]
@inter310 好像不会出现恶意插件的提示了

但是我刚才试了个视频貌似偶尔显示有版权问题
@yanggis @tommyzhaozbh 是有新的 URL 了吗

**Comment by yanggis** [comment]
@zhuzhuor,没发现新的URL。

**Comment by zhuzhuor** [comment]
@yanggis 我找到了个新的 IP，先加进去试试看。你要是回头看到新的 URL 也跟我说一声吧，多谢了

**Comment by Kara-ism** [comment]
@zhuzhuor 我测试了下，台湾这里还是会提示恶意插件。

**Comment by zhuzhuor** [comment]
@Kara-ism 你能点开 Unblock Youku 的图标看看版本号吗
类似这样的
> ![screen shot 2016-03-20 at 10 11 59 am](https://cloud.githubusercontent.com/assets/928905/13905690/3c461d2e-ee84-11e5-9351-fac193981e80.png)

**Comment by Kara-ism** [comment]
@zhuzhuor 你好，确认是更新至3.0.1.3且刷新缓存、COOKIE後出现的提示
刚刚也重新操作一次还是返回这样的提示
设置为转发模式且Unblock Youku有正确载入

> ip addr: 220.*.*.*
config.js:276 storage_monitor is set
header.js:90 extra_header_modifier is set
redirect.js:112 http_redirector is set
redirect.js:71 to test the redirection server: www.yōukù.com/proxy
config.js:154 initialized the settings for the mode: redirect
redirect.js:121 default_redirect_server seems to be working fine: www.yōukù.com/proxy

以下是从Console获取到的错误log：

> original url: http://cache.video.qiyi.com/jp/sdlst/6/203332601/?callback=window.Q.__callbacks__.cbuzto9l
redirect.js:61 redirect url: http://www.yōukù.com/proxy/http/cache.video.qiyi.com/jp/sdlst/6/203332601/?callback=window.Q.__callbacks__.cbuzto9l
redirect.js:25 original url: http://cache.video.qiyi.com/jp/vi/461579300/19a919f19c895f8ddd72ab9020920e25/?status=1&locale=zh_tw&callback=window.Q.__callbacks__.cb5t6aq8
redirect.js:61 redirect url: http://www.yōukù.com/proxy/http/cache.video.qiyi.com/jp/vi/461579300/19a919f19c895f8ddd72ab9020920e25/?status=1&locale=zh_tw&callback=window.Q.__callbacks__.cb5t6aq8
redirect.js:25 original url: http://cache.video.qiyi.com/jp/pc/461579300/?src=760859ef3a0046e0932d0381e641cbb6&callback=window.Q.__callbacks__.cbqxmrc8
redirect.js:61 redirect url: http://www.yōukù.com/proxy/http/cache.video.qiyi.com/jp/pc/461579300/?src=760859ef3a0046e0932d0381e641cbb6&callback=window.Q.__callbacks__.cbqxmrc8
redirect.js:25 original url: http://cache.video.qiyi.com/crossdomain.xml
redirect.js:27 directly pass
redirect.js:25 original url: http://cache.video.qiyi.com/vms?key=fvip&src=1702633101b340d8917a69cf8a4b8c…c13e26323c537d&thdk=&thdt=&rs=1&k_tag=1&tn=0.7171172117814422&locale=zh_tw
redirect.js:61 redirect url: http://www.yōukù.com/proxy/http/cache.video.qiyi.com/vms?key=fvip&src=1702633101b340d8917a69cf8a4b8c7c&tvId=461579300&vid=19a919f19c895f8ddd72ab9020920e25&vinfo=1&tm=561&enc=35db01b2537d03b526e087662b6f5279&qyid=8e57c637c3fd95b53da2dbfb02d904d1&puid=&authKey=f20f126a8d6f4ecbcb532054788536f6&um=0&pf=b6c13e26323c537d&thdk=&thdt=&rs=1&k_tag=1&tn=0.7171172117814422&locale=zh_tw
redirect.js:25 original url: http://cache.video.qiyi.com/jp/sdvlst/latest?key=sdvlist&categoryId=6&sourc…201602&tvYear=201603&locale=zh_tw&callback=window.Q.__callbacks__.cbzibcln
redirect.js:61 redirect url: http://www.yōukù.com/proxy/http/cache.video.qiyi.com/jp/sdvlst/latest?key=sdvlist&categoryId=6&sourceId=203332601&tvYear=201512&tvYear=201601&tvYear=201602&tvYear=201603&locale=zh_tw&callback=window.Q.__callbacks__.cbzibcln
redirect.js:25 original url: http://cache.video.qiyi.com/jp/pc/461579300,459074400,456759600,454373600,4…=760859ef3a0046e0932d0381e641cbb6&callback=window.Q.__callbacks__.cbonaotg
redirect.js:61 redirect url: http://www.yōukù.com/proxy/http/cache.video.qiyi.com/jp/pc/461579300,459074400,456759600,454373600,451899000,449802700,449132700,446663000,444155200,441775200,439350100,436791800,434393400,431956100,429346800,426595200/?src=760859ef3a0046e0932d0381e641cbb6&callback=window.Q.__callbacks__.cbonaotg

**Comment by zhuzhuor** [comment]
@Kara-ism 你试试普通模式，转发模式好像的确还是用的旧的服务器

**Comment by Kara-ism** [comment]
@zhuzhuor 你好，普通模式能够播放视频但是刷新几次页面後还是有机率提示恶意插件不能正常播放。
请问下转发模式也能够修改服务器位址麽？因为我同时使用其他的代理插件…谢谢！

**Comment by zhuzhuor** [comment]
@Kara-ism 官方的转发服务器还没改过来
你要是有资源可以尝试自己架设一个转发模式的服务器，Chrome extension 里的设置办法可以看 https://uku.im/custom

**Comment by zhuzhuor** [comment]
@Kara-ism 转发模式的服务器应该也正常了

**Comment by cheroooo** [comment]
抱歉一直没有check email 这个问题以及修复了,谢谢你。

**Comment by zhuzhuor** [comment]
@cheroooo 多谢你的再次反馈！

**Comment by cheroooo** [comment]
不用谢,因为你的努力,才让我们这些在海外的华人才能看得上国内的视频,我应该谢谢你才是。:)加油💪

**Comment by cheroooo** [comment]
你好，最近爱奇艺的播放又不稳定了，怎么破QAQ

2016-04-10 19:06 GMT-04:00 Cherry ZHU <cherry.zhu5.26@gmail.com>:

> 不用谢,因为你的努力,才让我们这些在海外的华人才能看得上国内的视频,我应该谢谢你才是。:)加油💪

**Comment by zhuzhuor** [comment]
请见 https://github.com/Unblocker/Unblock-Youku/issues/638
