### ISSUE TITLE
LETV 提示只允许大陆地区播放

### ISSUE THREAD

**Issue by zhuzhuor** [Unblocker/Unblock-Youku#615]
有用户在 Google Group 里反馈，试了下的确是这样
另外貌似 LETV 换了域名，成为 le.com 了

http://www.le.com/ptv/vplay/24414342.html

![screen shot 2016-03-02 at 7 40 32 pm](https://cloud.githubusercontent.com/assets/928905/13484036/e8600022-e0ae-11e5-9a04-0b4a9e835e59.png)

**Comment by whuhacker** [comment]
貌似我这边测没问题，挂了美国 VPN 还是能播……

**Comment by zhuzhuor** [comment]
我更新了一个 URL 看看情况，我这边测试是可以用了。看看之后还有没有别的问题
还有就是如果开了去除广告的 adblock 类的插件，LETV 貌似就不能正常播放了

另外我发现精简模式也可以解决 LETV 的问题了

**Comment by babypeony** [comment]
我三个模式都试过了，全都不能放

**Comment by zhuzhuor** [comment]
@babypeony 最新版 Chrome extension 刚上传到 Chrome Web Store，需要再等等才能自动更新

**Comment by zhuzhuor** [comment]
Chrome extension 现在是 pending review 的状态 
![screen shot 2016-03-02 at 9 28 21 pm](https://cloud.githubusercontent.com/assets/928905/13485541/c193e954-e0bd-11e5-9d51-1d29cd90b3bf.png)

**Comment by babypeony** [comment]
太牛了！等！

**Comment by babypeony** [comment]
另外我这里不只是letv有问题，奇异也看不了，是同一个问题吗？

**Comment by zhuzhuor** [comment]
@babypeony 你访问 https://uku.im/check 看看结果是不是 true，如果是 true 就说明扩展程序在工作

关于iqiyi 最近一直不稳定，问题出现的随机，我们也在寻找解决办法 https://github.com/Unblocker/Unblock-Youku/issues/612

**Comment by babypeony** [comment]
@zhuzhuor 多谢，修改了mode，就打开了（iqiyi）

**Comment by zhuzhuor** [comment]
这个问题看起来是修复了。如果有人还有问题欢迎再来 reopen
