### ISSUE TITLE
有服务器又遭到 DDoS 攻击了 

### ISSUE THREAD

**Issue by zhuzhuor** [Unblocker/Unblock-Youku#616]
对整体的服务应该影响不大

不过 statuscake 为啥还显示服务器在线呢 https://status.uku.im
statuscake 这 monitor service 感觉质量不如之前我们用的 pingdom

> ![screen shot 2016-03-04 at 8 14 59 am](https://cloud.githubusercontent.com/assets/928905/13532624/5699b0be-e1e1-11e5-8720-ee26886c50f7.png)
![screen shot 2016-03-04 at 8 15 13 am](https://cloud.githubusercontent.com/assets/928905/13532632/5e705cca-e1e1-11e5-9a20-b96ce10bec8a.png)
![screen shot 2016-03-04 at 8 15 20 am](https://cloud.githubusercontent.com/assets/928905/13532634/5fc2524a-e1e1-11e5-948c-69bd2b0f37b2.png)

**Comment by KanVivii** [comment]
好想知道那个服务器的状态检查界面是怎么做的

**Comment by zhuzhuor** [comment]
@KanVivii 这是用的 statuscake 的服务

**Comment by zhuzhuor** [comment]
今天被 DDoS 了一整天

> ![screen shot 2016-03-08 at 12 09 44 am](https://cloud.githubusercontent.com/assets/928905/13595678/32e514f4-e4c2-11e5-90e3-ae60476bc3be.png)

**Comment by ethanyoung** [comment]
是同时在美团云和阿里云上都有服务端吗？

**Comment by asuka0819** [comment]
dns也被攻击了……

**Comment by yanggis** [comment]
Hi there,

Our system has automatically detected an inbound DDoS against your droplet named yanggis-VPS with the following IP Address: 104.236.189.178

As a precautionary measure, we have temporarily disabled network traffic to your droplet to protect our network and other customers. Once the attack subsides, networking will be automatically reestablished to your droplet. The networking restriction is in place for three hours and then removed.

Please note that we take this measure only as a last resort when other filtering, routing, and network configuration changes have not been effective in routing around the DDoS attack.

Please let us know if there are any questions, we're happy to help.

Thank you,
DigitalOcean Support

**Comment by asuka0819** [comment]
@yanggis 果然是被攻击了吗？

**Comment by yanggis** [comment]
嗯，是的。这次攻击很猛烈，DigitalOcean关闭了很多服务器。3小时候会解禁，等吧……

**Comment by tommyzhaozbh** [comment]
@yanggis 有事找你，私聊

**Comment by yanggis** [comment]
好的。

**Comment by yanggis** [comment]
slack上说吧。

**Comment by asuka0819** [comment]
@yanggis  辛苦了，但愿这次能没事吧，反正我们也不急

**Comment by yanggis** [comment]
@asuka0819,应该没事，3个小时，DigitalOcean解禁了就好了，服务器刚才我Web登陆了看看没问题。

**Comment by asuka0819** [comment]
@yanggis 这次的攻击是只针对dns吗

**Comment by yanggis** [comment]
不是针对DNS，是针对整个unblock-Youku用的所有服务器。

**Comment by yanggis** [comment]
这两天持续攻击，只有新的DNS服务器158.69.209.100有硬件防火墙可以防的住，现在暂时没事。104的服务器现在还处于down机状态。

**Comment by sunyiyun2001** [comment]
@yanggis 有个问题问你，私聊

**Comment by yanggis** [comment]
@sunyiyun2001，这周末特别忙，刚刚上线，您有什么我需要帮忙的，我们用https://gitter.im/yanggis联系我吧。你可以注册，注册之后，用这个链接就可以给我发私信了。

**Comment by esme518** [comment]
让服务器拒绝中国IP段的访问 会不会对防止攻击有一定帮助？

**Comment by yanggis** [comment]
@esme518，谢谢提醒，以前是这么做的，但是这次攻击的IP全部来自海外，其中一个是购买的阿里云在北美的服务器，这次针对unbock-youku的服务器的，是蓄谋已久的，丧心病狂的攻击……。

**Comment by baryon** [comment]
158也挂掉了吧？
会不会有用户不懂的设置，将所有的DNS解析都发过去了？
