### ISSUE TITLE
DNS解锁导致个别网站无法访问

### ISSUE THREAD

**Issue by esme518** [Unblocker/Unblock-Youku#617]
使用104.236.189.178这个DNS的话 会导致个别网站无法访问 例如:战旗直播(http://www.zhanqi.tv/)
本人身在日本 而使用192.241.222.103 就没有遇到这个问题

**Comment by yanggis** [comment]
这个其实是zhanqi.tv的DNS广播有点问题，我刚才调整了一下，现在应该可以了。你看还有其他解析不了的吗？

**Comment by esme518** [comment]
辛苦了 暂时没有发现 等发现的时候再报告了

**Comment by onlyesterday** [comment]
DNS 104.236.189.178 好像不能用了，我在美国

**Comment by yanggis** [comment]
Hi there,

Our system has automatically detected an inbound DDoS against your droplet named yanggis-VPS with the following IP Address: 104.236.189.178

As a precautionary measure, we have temporarily disabled network traffic to your droplet to protect our network and other customers. Once the attack subsides, networking will be automatically reestablished to your droplet. The networking restriction is in place for three hours and then removed.

Please note that we take this measure only as a last resort when other filtering, routing, and network configuration changes have not been effective in routing around the DDoS attack.

Please let us know if there are any questions, we're happy to help.

Thank you,
DigitalOcean Support

**Comment by onlyesterday** [comment]
辛苦了，非常感谢

**Comment by esme518** [comment]
遇到被攻击这种情况就很郁闷了...尤其是在把DNS利用dnsmasq设为局域网所有设备的dns之后...所以还是非常希望能公开一下自己搭建dns的教程 这样的情况下只要在国内家里扔一个树莓派就OK了

**Comment by KanVivii** [comment]
@esme518 强烈支持写个教程 稍微详细点新手入门 wiki里的美团云的后面部分还是有点不懂

**Comment by lzfxxx** [comment]
@yanggis 你好，用 104 DNS https://movie.douban.com 的网页显示有点问题

**Comment by yanggis** [comment]
@lzfxxx,我刚才看了一下，网页显示的问题是因为这个网页加载的时候需要到img3.doubanio.com这个服务器去请求图片和描述数据，但是这个服务器有时候会响应比较慢，或者不响应，所以就会导致有些内容显示不全。你过会尝试重新刷一下看看能不能显示？这个经常会这样吗？

**Comment by lzfxxx** [comment]
@yanggis 是的每次都会这样，刷新没用，我已经改了你新发的 158 DNS，也是同样

**Comment by yanggis** [comment]
嗯，我刚才更新了一下服务器，现在应该没问题了。

**Comment by lzfxxx** [comment]
@yanggis 好了，非常感谢！

**Comment by esme518** [comment]
@yanggis 使用dns的情况下 iOS bilibili客户端 推荐页面无法加载 看视频倒是正常 android客户端的话 新番专题 打开会出现无法获取集数的情况 同样看视频没有问题

**Comment by yanggis** [comment]
@esme518,能说一下您在哪个国家吗？现在158的服务器有些地区访问网页有点慢，视频播放速度不受影响。推荐页面刚才我看了，可以加载，点了推荐番剧之后，等一会就加载进来了。

**Comment by esme518** [comment]
@yanggis 我在日本 截图如下 https://imgur.com/8zuq9Tc 
在bilibili长时间关闭（可能是缓存清空了）的时候打开推荐页面 就会长时间无法刷新然后显示此页面
dns连接应该是没有问题的 因为此时通过番剧等其它页面打开版权视频是可以正常解锁播放的（有时会出现第一次无法解锁 或长时间无法打开视频 再试一次也就OK了）

**Comment by esme518** [comment]
@yanggis 基本可以确认是dns问题 因为在换用普通dns之后 推荐页面刷新就立马正常了 当然此时打开新番页面就显示不支持您所在地区了 连集数都无法获取 所以说刚才与dns的连接是正常的 就是推荐页面不知道中了什么邪...

**Comment by yanggis** [comment]
@esme518 你应该是用的最新版的bilibili IPad客户端才出现这个问题，换回老版本就好了，你可以从这里下载 bilibili IPad客户端4.1.1版的。然后把IPad连到电脑上用PP助手安装上，就可以正常unblock了。老版本的下载地址：
http://pan.baidu.com/share/link?shareid=2231231494&uk=3072953359&fid=173859493487081

**Comment by esme518** [comment]
@yanggis 我用的是iOS手机版 自动更新的 也没有必要特意换回旧版 因为除这个页面以外 观看视频还是正常的 算是一个无伤大雅的bug 我只是很好奇产生这个问题的原因

**Comment by yanggis** [comment]
@esme518 原因很简单，Bilibili在新的客户端里增加了非http的验证，导致仅仅依靠http代理的解锁方法失效了。所以在新客户端上你就是全部http链接都走代理，仍然无法解锁，只能用vpn，让非http的通信也走vpn才能解锁成功。

**Comment by asuka0819** [comment]
@yanggis 音悦台那边主页可以进去但是不知道为什么总是显示服务器繁忙……

**Comment by yanggis** [comment]
@asuka0819 音悦台现在应该没问题了。

**Comment by asuka0819** [comment]
@yanggis Thanks!

**Comment by baidu-safe** [comment]
@yanggis 你好，https://movie.douban.com 的网页显示仍然有问题

**Comment by yanggis** [comment]
@baidu-safe 我刚才试了一下没问题啊，显示正常啊。您有截图吗？上传我看一下是什么情况。
