### ISSUE TITLE
增加小米盒子支持

### ISSUE THREAD

**Issue by jason51122** [Unblocker/Unblock-Youku#619]
DNS一直都不支持小米盒子的GITV和爱奇艺 希望能增这个功能 谢谢

您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）: 158.69.209.100

请具体描述您遇到的问题（例如有问题的视频网址）：小米盒子上的GITV和爱奇艺支持

您所处的国家或地区：美国

**Comment by yanggis** [comment]
小米盒子不支持，主要是因为开发人员基本都不用小米盒子，没有测试环境，没法确定小米盒子具体Unblock的link是哪些。如果你特别需要Unblock小米盒子，可以单独私信给我。

**Comment by jason51122** [comment]
不知道怎么私信啊 请问android上有类似Fiddler的东西吗 我可以把url抓下来 谢谢

**Comment by yanggis** [comment]
你先到https://gitter.im/登陆，然后跳转到https://gitter.im/yanggis，就可以给我发信息了。

**Comment by zhuzhuor** [comment]
@yanggis 这问题后来解决了吗？

**Comment by yanggis** [comment]
@zhuzhuor 这个先不要关闭，那人还没联系我调试。

**Comment by AgentKWang** [comment]
@yanggis， 准备先连上openwrt抓包的，结果openwrt出了点问题 一直在调试。明天还弄不好就换个方案，用小米root挂代理再试试看。

**Comment by jason51122** [comment]
@AgentKWang 请问一下能不能在小米盒子上安装奇异果(爱奇艺的tv客户端 http://app.iqiyi.com/tv/player/) 试一下用dns能不能看有版权限制的视频呢(比如名侦探柯南) 我这里不能看 不知道是不是只有我有问题 谢谢

**Comment by yanggis** [comment]
谁现在用电视盒子设置了DNS，在电视盒子上装个爱奇艺的tv客户端，看看里面动漫里的<名侦探柯南>能不能播放。
帮@jason51122 测试一下。

**Comment by hihitoni** [comment]
@yanggis 沙发·管家中下载的爱奇艺tv客户端 dns测试了一下 可以看 但速度慢（欧洲）

**Comment by yanggis** [comment]
@hihitoni, 谢谢。
如果选择标清模式可以流畅播放吗？沙发管家的设置里面有个网络监测，你看看爱奇艺播放的时候，当前网络能达到多少？
如果会卡的话，你换下一集，看看网速有没有改变？欧洲那边有时候会有点卡，退出播放，或者换下一集再换回来应该就会好一些了。

**Comment by hihitoni** [comment]
@yanggis  选择标清模式可以愉快的观看，不过测试这段时间 会发生错误 404，不知道是不是dns被攻击有关。网上找了几个移动的代理测试了 可以愉快的看超清。
谢谢你们的工作

**Comment by yanggis** [comment]
@hihitoni 4开头的错误是客户端的问题，5开头的是服务器端的问题。应该是暂时性的。

**Comment by gitawego** [comment]
我也是小米盒子，大半年前还可以，现在一直不成功，爱奇艺和youku TV客户端里很多片子，都提示不在大陆区，无法观看。

**Comment by yanggis** [comment]
@gitawego, 现在手里没有小米盒子，没法确定该怎么解锁，现在只能看谁有小米盒子能抓到需要解锁的Link,我加到服务器上了。

**Comment by AgentKWang** [comment]
[xiaomiBox-1997-sun.zip](https://github.com/Unblocker/Unblock-Youku/files/194246/xiaomiBox-1997-sun.zip)

hi, 我上传了一段从小米盒子抓取的流量。期间我在小米盒子上随机点进两个电视剧，然后都是返回无法获取视频地址。

**Comment by jason51122** [comment]
@AgentKWang 请问下必须越狱的盒子才可以抓取吗 求详细步骤

**Comment by yanggis** [comment]
@AgentKWang 我现在根据你提供的文件修改了服务器配置，你现在把小米盒子断电1-2分钟，再重新连上开机进去，看看昨天点的那几个电视剧现在能不能看了。

**Comment by jason51122** [comment]
@AgentKWang 我试了还是不行 GITV的视频还是不能看 显示不在中国大陆

**Comment by yanggis** [comment]
@AgentKWang, 测试一下回复我哈。

**Comment by AgentKWang** [comment]
@yanggis, Sorry, 测试晚了。我用的是158.69.209.100这个DNS，还是不行。新抓了一个包，还有小米盒子的返回错误页面。
[test2.zip](https://github.com/Unblocker/Unblock-Youku/files/201179/test2.zip)


我注意到有两个url比较可疑：
http://data2.itv.ptqy.gitv.tv/itv/playCheck/404/223791400 
http://feedback.ptqy.gitv.tv/f/b/p.html

麻烦分析一下，谢谢！

**Comment by AgentKWang** [comment]
@jason51122, 最新版本的小米盒子系统好像还不能root. 我的办法是用PC创建一个HostedNetwork, 然后小米盒子连上，在PC上用WireShark抓包。

**Comment by yanggis** [comment]
@AgentKWang 我已经把您说的这2个链接加到158服务器上了，你现在把小米盒子断电清空一下DNS缓存，重新连一下试试。

**Comment by gitawego** [comment]
刚测试了下，发现GITV可以用了，没有出现版权提示了：）
万分感谢！

**Comment by yanggis** [comment]
@gitawego 感谢反馈，能说一下播放速度怎么样嘛？够不够流畅？

**Comment by gitawego** [comment]
GITV一直很流畅，用了代理也没发现有影响。
我是250M的光纤

**Comment by yanggis** [comment]
@gitawego  OK, noted.
你的网络很牛X，我还用这20M的小水管呢……。

**Comment by gitawego** [comment]
国内是个大局域网，国外网速再快，进入国内就全部降速了。所以我250m的速度和你20m的速度连国内是一样的故事。。。

**Comment by jason51122** [comment]
太感谢你们了 我的GITV也能用了

**Comment by li0001** [comment]
我用小米盒子看爱奇异有时候可以有时候不可以看。今天用了DNS也不太能看。所在地美国

**Comment by jason51122** [comment]
爱奇艺的内容基本gitv都有 我的爱奇艺一直不能看

**Comment by jason51122** [comment]
刚刚又测试了一下 我的爱奇艺也可以看了

**Comment by yanggis** [comment]
@li0001 你用的158的服务器吗？这次针对小米盒子的解锁测试就只放在了158那个服务器上，等测试成功后会在最近1-2天都同步到45的服务器上。这样几台DNS服务器就完全一样了。
所以你现在要是用的是45的服务器应该还不能解锁。
另外，每一代小米盒子解锁方法略有不同，我手里没有这些盒子，没法测试，你自己抓包的话，我可以帮你分析一下。

**Comment by yanggis** [comment]
@jason51122 乐视网客户端for TV box,谁用电视盒子，可以下载安装看乐视视频和直播。我只是搬运工，不回答关于这个软体的任何使用问题。
[乐视网TV版.zip](https://github.com/Unblocker/Unblock-Youku/files/201692/TV.zip)

**Comment by AgentKWang** [comment]
我把DNS改为158.69.209.100后，GITV全面瘫痪不能用了，连节目简介页面都load不出来。是不是DNS又被攻击了？

**Comment by yanggis** [comment]
@AgentKWang 把你的盒子断电重启一下呢？

**Comment by AgentKWang** [comment]
@yanggis,重启过了。DNS代理的原理是不是把流量都导向到一个proxy server? 我看到我的盒子一直在请求一个IP 124.243.204.78，但是我本地是ping不通这个IP的。可能是我本地的网络的问题。我是美东Verizon FIOS,

**Comment by yanggis** [comment]
@AgentKWang 不是的，你的需要解锁的流量是应该被倒向了158的DNS服务器才对。

**Comment by yanggis** [comment]
@AgentKWang 在你的盒子的浏览器里上输入 http://int.dpool.sina.com.cn/iplookup/iplookup.php 看看显示的你现在的IP位置是多少。
然后看看你盒子上的其他视频软件，比如优酷视频，腾讯视频之类可以不可以正常解锁。

**Comment by jason51122** [comment]
@yanggis 直播和视频都可以看 但是这个tv版的排版很混乱 左右图片和文字都挤在一起 有时候根本没法选择 不过能看已经很好了 速度很快 多谢多谢

**Comment by yanggis** [comment]
@jason51122 将就着看吧，这个是从乐视超级电视里提出去来的，换了定制的平台之后，很多原来平台的字体都没了，就会出这样的问题。

**Comment by jason51122** [comment]
@yanggis 能用很好了 哈哈 多谢多谢 这个是你们自己制作的吗

**Comment by yanggis** [comment]
@jason51122 我只是搬运工……

**Comment by gitawego** [comment]
这乐视视频真是好啊，看4K都超级流畅。界面就将就着用吧:) 
多谢分享

**Comment by jason51122** [comment]
@gitawego 请问你试过搜索吗 我进入搜索找不到在哪输入

**Comment by gitawego** [comment]
@jason51122 我的是小米盒子增强版，界面全是乱七八糟的，搜索界面更不用说了，只显示一半的屏幕。呵呵，所以我也用不了搜索。。。

**Comment by Migflyway** [comment]
小米盒子解锁好给力，满速。

**Comment by zhuzhuor** [comment]
@yanggis 给力！ :+1:

**Comment by jason51122** [comment]
小米盒子今天系统更新 又提示版权限制了 能再抓一下url吗 谢谢

**Comment by yanggis** [comment]
@jason51122 等有小米盒子的并且升级了小米系统的人帮忙吧……这个没有小米盒子就没办法帮你抓包了。
视频软件和电视盒子系统，我觉得能看着好好的，尽量不要升级，升级就可能面临新的破解。

**Comment by li0001** [comment]
我昨天用dns158看爱奇艺可以看，今天又不能看了，我就把重启路由器，然后重启小米盒子，又可以看了。大家可以试试看

**Comment by jason51122** [comment]
重启后可以看了 多谢多谢
