### ISSUE TITLE
iPad设置了pac文件或DNS之后依旧不能在Safari中观看腾讯体育视频

### ISSUE THREAD

**Issue by enerai** [Unblocker/Unblock-Youku#620]
**您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:**
PAC 和 DNS

**请具体描述您遇到的问题（例如有问题的视频网址）：**
**http://sports.qq.com/kbsweb/kbsshare/game.htm?mid=100000%3A1467851**

访问检测页面显示true，但是在iPad的Safari里面打开上面的页面提示“很抱歉，当前IP地址所在地区暂不支持播放”，但是设置了DNS之后通过腾讯视频APP是可以正确观看视频的，不知道这是什么原因造成的
测试过程中使用的**PAC地址是：http://pac.uku.im/proxy.pac**，使用的**DNS地址是：158.69.209.100**

**您所处的国家或地区：**
香港

**Comment by mc16888** [comment]
iOS 用Browser 的話,要加這一個 URL去 DNS, 加去PAC無效,原因未明. 

http://h5vv.video.qq.com/getvinfo*

**Comment by enerai** [comment]
如果我用surge的话，请问我该怎么添加这个条目呢，是要代理到哪个服务器上呢？

**Comment by mc16888** [comment]
用surge的話, 加 domain h5vv.video.qq.com , 服務器隨便找一個內地的代理服務器應該就可以了.

**Comment by yanggis** [comment]
这个问题我已经修改了，现在再测试一下看看能不能用哈。

**Comment by yanggis** [comment]
@mc16888，有些Link在PAC文件上是不支持的。

**Comment by enerai** [comment]
DNS已经好用了，不过最近感觉DNS好像有点慢🤔️

**Comment by yanggis** [comment]
如果你所在区域158的服务器比较慢，可以换45的服务器试试。设置办法看这里。
https://github.com/Unblocker/Unblock-Youku/issues/618

**Comment by zhuzhuor** [comment]
@yanggis `h5vv.video.qq.com` 这个为啥 DNS 管用但是 PAC 不行？是因为浏览器缓存还是  DNS 的原因？或者是别的原因？

**Comment by yanggis** [comment]
@zhuzhuor h5vv.video.qq.com里面有个查询字符串和pac语法用冲突，验证会出问题，所以会跳过这个link.

**Comment by zhuzhuor** [comment]
@yanggis 这。。。能再详细解释解释吗？

**Comment by zhuzhuor** [comment]
我刚把这个 URL 加到 urls.js 里 https://github.com/Unblocker/Unblock-Youku/commit/9ddc27d909d863210dd4d95f41e35c42e4ddd9f4 刚要 push 到 chrome web store 来着

**Comment by yanggis** [comment]
@zhuzhuor urls.js加进去没问题；
但是那个link里面很多查询的字符串比如&cv=1233.23&pl=12@2343&fs=1323?123等等之类的，在PAC验证的时候就会异常跳出了。所以就不会把这个链接走代理了。

**Comment by zhuzhuor** [comment]
@yanggis 不会吧，应该都是 regex 检查的。有实际的 url 吗，方便我试试吗？或者你有 error message 给我看看？

**Comment by yanggis** [comment]
@zhuzhuor，我用的linux上的pactester工具

**Comment by yanggis** [comment]
https://github.com/manugarg/pactester

**Comment by zhuzhuor** [comment]
@yanggis 是说 link 很复杂出错了吗？你那边有实际的 link 可以来看看嘛

**Comment by yanggis** [comment]
额，现在没有。还有bilibili的有一个Link在PAC方法上也会出问题，和这个比较类似。反正PAC检测就那个link就不会走代理，不知道是什么问题。还有LeTV里的基于IP验证的几个link也是这样。不过那几个link现在好像不怎么用了。

**Comment by zhuzhuor** [comment]
@yanggis @mc16888 好，你们要是回头要是看到这样的 link 发来给我看看，我对这挺好奇的

**Comment by yanggis** [comment]
@zhuzhuor 给你几个链接测试一下。

http://h5vv.video.qq.com/getinfo?callback=tvp_request_getinfo_callback_554616&platform=170308&charge=0&otype=json&sphls=1&sb=1&nocache=1&_rnd=1458217473774&cKey=kSEtaVWsRo9D71caoleGaFdhaHKSZhR

LeTV的：
http://115.182.200.53:80/heartBeat?arealevel1=CN&arealevel2=10&arealevel3=127&expect=38&groupId=cctv1HD_1800ver_00_101.3m3u8_12272000&ispId=2&module=cde&neighbors=0&peerId=c7fd2b479838c926b344cbdceb5b79d00498a5ab5e2193c65cdbbe68d3b25a81&pos=1458232018&query=1&rtmfpId=115.182.200.51:8125&tid=1&ver=liv.CDE-1.0.19

**Comment by zhuzhuor** [comment]
@yanggis 多谢，有意思

第一个 QQ 的是因为 URL 没在 urls.js 里面。`http://h5vv.video.qq.com/getinfo` 和 @mc16888 上面说的有一个字母的区别
LETV的两个估计是有端口号 `:80` 在  URL 里面，PAC 没处理好
bilibili 的那个会经过代理呀，我刚才试了试

**Comment by mc16888** [comment]
@zhuzhuor @yanggis orz. I need a new pair of glasses
should be 
http://h5vv.video.qq.com/getinfo
not 
http://h5vv.video.qq.com/get**v**info
