### ISSUE TITLE
使用新DNS 優酷及bilibili頁面底部出現廣告

### ISSUE THREAD

**Issue by klib9739** [Unblocker/Unblock-Youku#621]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等)：DNS

请具体描述您遇到的问题（例如有问题的视频网址）：如題

您所处的国家或地区：台灣

http://imgur.com/B0GzLq2
http://imgur.com/eTWzIQ3

是被劫持嗎還是?
另外新DNS的速度似乎比以前慢不少

**Comment by yanggis** [comment]
@klib9739，如果你在的区域访问158的服务器比较慢，可以访问测试服务器45.32.72.192试试。

**Comment by yanggis** [comment]
DNS里是肯定没有恶意添加广告的，另外搜狐视频，优酷视频，腾讯视频和乐视视频开头的广告在DNS服务器是都专门去掉了的，更不会专门添加广告了，这种情况您可以换个别的浏览器试试，或者检查一下浏览器有没有安装恶意插件。
另外，如果有些地方觉得服务区器比比较慢，可以用45.32.72.192 测试服务器。或者你干脆在电脑配置配置2个DNS，一个158的，一个42的这个，哪个您觉得比较快，就把哪个放在前面。如果有一个不能访问，系统就会自动跳到另外一个DNS服务器上。

**Comment by tommyzhaozbh** [comment]
我测试了一下所有优酷的页面都没有出现类似的现象。是不是你用了别的浏览器，或者是你的浏览器被劫持了？

**Comment by klib9739** [comment]
我用的是Android上的Chrome
應該是沒辦法安裝插件的
當然我也相信unblock不可能在裡面添加廣告
只是不知道路由哪裡出問題

這廣告目前暫時沒出現了

**Comment by klib9739** [comment]
目前發現bilibili也有這種現象
和優酷一樣是出現在行動版網頁

**Comment by Coyoter** [comment]
我也來自台灣，用的是中華電信光世代300M。手機是三星S6 Edge、瀏覽器Chrome，搭配DNS：158.69.209.100，連上手機版優酷看影片，除了一開始的Pre-Roll廣告50秒外，沒出現別的廣告，樓主截圖的廣告一樣沒出現。
　
根據經驗，那種廣告多是跟著你的Wifi走的，問題應該是出在你使用的路由器上，路由器有可能被綁架、或是裝上廣告軟體了？
　
試試看換一個地點（例如公司），再用那個地方的網路試試看。再不然就是手機有被安裝上不好的軟體，不過這情況其實不多見就是了。

**Comment by klib9739** [comment]
嗨同樣來自台灣的朋友你好
網路部分我有用亞太+台星4G還有台灣大寬頻的網路測試
中華要等過幾天才測得到
手機的部分我也有用ZF2和MI3交換測試
而且我發現使用電腦的Chrome
User Agent改為Android開這兩個行動版網站也會出現廣告

繁體是因為我有使用簡轉繁的字體😂😂😂

**Comment by Coyoter** [comment]
連電腦改User Agent 都會出現，真是奇了怪了。有辦法使用固網測試嗎？我是直接在Android 連光世代WiFi
時，使用手機內建修改方式改的DNS 。

klib9739 <notifications@github.com> 於 2016年3月14日週一 01:23 寫道：

**Comment by Coyoter** [comment]
連電腦改User Agent 都會出現，真是奇了怪了。有辦法使用固網測試嗎？我是直接在Android 連光世代WiFi 時，使用手機內建修改方式改的DNS 。

明天我也開電腦試試看。

**Comment by zhuzhuor** [comment]
@yanggis 你这台服务器是国内的 rasp pi 吧，可能是家里的 ISP 作祟。国内 ISP 乱插广告已经很久了 http://lmgtfy.com/?q=%E7%94%B5%E4%BF%A1+%E8%81%94%E9%80%9A+%E5%8A%AB%E6%8C%81+%E5%B9%BF%E5%91%8A

有谁遇到了这个广告可以看看页面的 HTML，检查一下植入的方式

**Comment by zhuzhuor** [comment]
@yanggis 另外你说你把视频开始的广告去掉了？我觉得不太好，还是不要屏蔽广告吧

**Comment by yanggis** [comment]
@klib9739,能提供几个出现广告的链接，发上来我这边打开看一下吗？现在大家用的是同样的DNS，但是仅仅是个别用户才有这个问题。

**Comment by yanggis** [comment]
@zhuzhuor，你说的国内IPS插入广告的可能性不大，大家是用的同样的服务器，如果有，应该是对所有的人都可以看到才对，不会只专门投放个别人啊。
@zhuzhuor 广告过滤那个whitelist已经去掉了。

**Comment by klib9739** [comment]
@zhuzhuor @yanggis 
HTML和廣告連結我晚點再發上來
目前新DNS我這邊PING的到但連不上

**Comment by klib9739** [comment]
@zhuzhuor 
http://pos.baidu.com/acom?sz=775x117&rdid=2444520&dc=2&di=u2444520&dri=0&dis=0&dai=1&ps=645x0&dcb=BAIDU_SSP_define&dtm=BAIDU_DUP_SETJSONADSLOT&dvi=0.0&dci=-1&dpt=none&tsr=0&tpr=1457932097232&ti=%E4%BC%98%E9%85%B7-%E4%B8%AD%E5%9B%BD%E9%A2%86%E5%85%88%E8%A7%86%E9%A2%91%E7%BD%91%E7%AB%99%2C%E6%8F%90%E4%BE%9B%E8%A7%86%E9%A2%91%E6%92%AD%E6%94%BE%2C%E8%A7%86%E9%A2%91%E5%8F%91%E5%B8%83%2C%E8%A7%86%E9%A2%91%E6%90%9C%E7%B4%A2%20-%20%E4%BC%98%E9%85%B7%E8%A7%86%E9%A2%91&ari=1&dbv=2&drs=3&pcs=865x775&pss=865x14927&cfv=21&cpl=5&chi=3&cce=true&cec=UTF-8&tlm=1457932097&ltu=http%3A%2F%2Fwww.youku.com%2F&ltr=https%3A%2F%2Fwww.google.com.tw%2F&ecd=1&psr=x&par=x&pis=-1x-1&ccd=0&cja=false&cmi=7&col=zh-TW&cdo=-1&tcn=1457932097&qn=864933dcbdaaa509&tt=1457932096829.407.929.943

**Comment by klib9739** [comment]
PC直接訪問這網址更明顯
基本整個頁面都是廣告

http://www.youku.com/?screen=phone

http://imgur.com/OD97Jvd

**Comment by yanggis** [comment]
其他收到消息的，用158的DNS服务器的，访问http://www.youku.com/?screen=phone看看有没有广告。来这回复一下。

**Comment by yanggis** [comment]
@klib9739 你这个很明显是百度推广的广告，但是你发的那个这个链接很明显能发现问题。

http://pos.baidu.com/acom?sz=775x117&rdid=2444520&dc=2&di=u2444520&dri=0&dis=0&dai=1&ps=645x0&dcb=BAIDU_SSP_define&dtm=BAIDU_DUP_SETJSONADSLOT&dvi=0.0&dci=-1&dpt=none&tsr=0&tpr=1457932097232&ti=%E4%BC%98%E9%85%B7-%E4%B8%AD%E5%9B%BD%E9%A2%86%E5%85%88%E8%A7%86%E9%A2%91%E7%BD%91%E7%AB%99%2C%E6%8F%90%E4%BE%9B%E8%A7%86%E9%A2%91%E6%92%AD%E6%94%BE%2C%E8%A7%86%E9%A2%91%E5%8F%91%E5%B8%83%2C%E8%A7%86%E9%A2%91%E6%90%9C%E7%B4%A2%20-%20%E4%BC%98%E9%85%B7%E8%A7%86%E9%A2%91&ari=1&dbv=2&drs=3&pcs=865x775&pss=865x14927&cfv=21&cpl=5&chi=3&cce=true&cec=UTF-8&tlm=1457932097&ltu=http%3A%2F%2Fwww.youku.com%2F&ltr=https%3A%2F%2Fwww.google.com.tw%2F&ecd=1&psr=x&par=x&pis=-1x-1&ccd=0&cja=false&cmi=7&col=zh-TW&cdo=-1&tcn=1457932097&qn=864933dcbdaaa509&tt=1457932096829.407.929.943

看你这个链接里面有一项ltr=http://www.google.com.tw，这个就能说明，这个移植广告是来自台湾的。google在大陆是全部禁止的，更不会有大陆的人人在推广里加一个根本就访问不了的网页，而且即便是加也会是google.com,或者google.com.hk的香港网页，不太可能会用.tw的网页。

**Comment by klib9739** [comment]
這是bilibili的

http://pos.baidu.com/acom?sz=775x117&rdid=2444520&dc=2&di=u2444520&dri=0&dis=0&dai=1&ps=645x0&dcb=BAIDU_SSP_define&dtm=BAIDU_DUP_SETJSONADSLOT&dvi=0.0&dci=-1&dpt=none&tsr=0&tpr=1457937157522&ti=%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E5%BC%B9%E5%B9%95%E8%A7%86%E9%A2%91%E7%BD%91%20-%20(%20%E3%82%9C-%20%E3%82%9C)%E3%81%A4%E3%83%AD%20%E4%B9%BE%E6%9D%AF~%20-%20bilibili&ari=1&dbv=2&drs=3&pcs=865x775&pss=865x5878&cfv=21&cpl=5&chi=2&cce=true&cec=UTF-8&tlm=1457937157&ltu=http%3A%2F%2Fwww.bilibili.com%2Fmobile%2Findex.html&ecd=1&psr=1440x900&par=1440x860&pis=-1x-1&ccd=24&cja=false&cmi=7&col=zh-TW&cdo=-1&tcn=1457937158&qn=e30870f7f3b8b64e&tt=1457937157088.438.958.962

@yanggis 
以上就沒出現www.google.com.tw
我想會出現www.google.com.tw是因為當次我是由www.google.com.tw搜尋youku然後進入優酷網站的
至於zh-TW應當是pos.baidu.com檢測到我的台灣IP?

另外我現在是用42這個DNS也還是有廣告

**Comment by klib9739** [comment]
http://pos.baidu.com/acom?rdid=2552892&dc=2&di=u2552892&dri=0&dis=0&dai=1&ps=520x560&dcb=BAIDU_SSP_define&dtm=BAIDU_DUP_SETJSONADSLOT&dvi=0.0&dci=-1&dpt=none&tsr=0&tpr=1457937402843&ti=%E4%BC%98%E9%85%B7-%E4%B8%AD%E5%9B%BD%E9%A2%86%E5%85%88%E8%A7%86%E9%A2%91%E7%BD%91%E7%AB%99%2C%E6%8F%90%E4%BE%9B%E8%A7%86%E9%A2%91%E6%92%AD%E6%94%BE%2C%E8%A7%86%E9%A2%91%E5%8F%91%E5%B8%83%2C%E8%A7%86%E9%A2%91%E6%90%9C%E7%B4%A2%20-%20%E4%BC%98%E9%85%B7%E8%A7%86%E9%A2%91&ari=1&dbv=2&drs=3&pcs=865x775&pss=865x14899&cfv=0&cpl=5&chi=1&cce=true&cec=UTF-8&tlm=1457937402&ltu=http%3A%2F%2Fwww.youku.com%2F%3Fscreen%3Dphone&ecd=1&psr=x&par=x&pis=-1x-1&ccd=0&cja=false&cmi=7&col=zh-TW&cdo=-1&tcn=1457937403&qn=8a681c8d4111306b&tt=1457937402355.495.950.960

@yanggis 
這是我剛剛直接開www.youku.com
可以看到內容裡也沒有www.google.com.tw了

**Comment by Coyoter** [comment]
我用Mac Safari 9.1、Mac Chrome來測試，將DNS調整到158.69.209.100，測試bilibili以及http://www.youku.com/?screen=phone，都沒有出現廣告。測試兩種網路，分別是公司網路，以及中華電信4G。

<img width="1280" alt="2016-03-14 2 40 32" src="https://cloud.githubusercontent.com/assets/13643173/13736928/f5e86db2-e9f3-11e5-961b-a4f3bd7288bb.png">

<img width="1280" alt="2016-03-14 2 46 11" src="https://cloud.githubusercontent.com/assets/13643173/13736935/ffed3234-e9f3-11e5-97f6-a9b58d800dc8.png">

<img width="653" alt="2016-03-14 2 46 59" src="https://cloud.githubusercontent.com/assets/13643173/13736942/0f979c06-e9f4-11e5-90ab-49a6c45f2a52.png">

<img width="766" alt="2016-03-14 2 47 46" src="https://cloud.githubusercontent.com/assets/13643173/13736944/15f31080-e9f4-11e5-9ae4-c8ae5ebc7081.png">

**Comment by klib9739** [comment]
![default](https://cloud.githubusercontent.com/assets/6081203/13737032/091f63bc-e9f5-11e5-928a-c9b9d06754b1.png)

@Coyoter 其實我這問題大概開10次有8次會出現
另外對比我們bilibili右上角開發人員那邊
我的是不是多了一段百度的東西

**Comment by yanggis** [comment]
@klib9739,我刚才又检查了一下，我觉得很有可能是你那边本地的广告，因为这个DNS事实上是一个代理服务器，它只允许whitelist里的links才能通过。其他的就是特意去请求这个服务器去请求whitelist以外的任何link都会被拒绝掉的。我看了pos.baidu.com是不在这个whitelist里的，所以它肯定没法通过这个代理服务器的呀。

**Comment by yanggis** [comment]
不要管浏览器的事情，你的电脑上很有可能安装的有恶意的软件在后台运行，不管你换任何浏览器，它都可以在数据到浏览器的时候给你插入广告，想要移除它就要把这个恶意软件在后台的进程结束掉。

**Comment by Coyoter** [comment]
@klib9739 對的，你的被植入了一段js，放在<head>之上。如果你的手機、電腦都會出現，就很奇怪了。

一、手機電腦都出現，暫時斷定與瀏覽器插件無關。手機Chrome無法有插件。
二、但是我使用這個DNS不會出現廣告，暫時斷定也與DNS無關。
三、這時候的問題，我認為是出在你使用的網路有關，包括你習慣的Proxy、VPN、甚至你的路由器（如果手機跟電腦用一樣的AP，但是AP本身就有廣告，不管你換什麼設備可能都一樣了。）

**Comment by klib9739** [comment]
@yanggis 
1.我沒有管瀏覽器的事
而這狀況不只出現在我的電腦 手機上也出現

2.沒錯pos.baidu.com不在whitelist裡所以他才會偵測到zh-TW

3.但我有嘗試過更換設備以及後端ISP
甚至手機直接連4G
還是都會出現
一把unblock取消掉改回原本DNS
就不會出現廣告

到現在我也還查找不到原因

**Comment by Coyoter** [comment]
@klib9739 你用的是158的DNS？（直接修改電腦、手機DNS，不透過任何軟體）還是你用的是Unblock插件？

**Comment by klib9739** [comment]
@Coyoter 
我的使用158和45的DNS

不過正確來說也不算是使用DNS
應該說是反向代理?

設置是這樣的 在hosts裡面添加像以下的內容
45.32.72.192  www.bilibili.com
45.32.72.192  www.soku.com
45.32.72.192  www.tudou.com
45.32.72.192  www.xiami.com
45.32.72.192  www.yinyuetai.com
45.32.72.192  www.youku.com
.......

**Comment by Coyoter** [comment]
@klib9739 我網易云音樂也是這樣用的。直接設定host...

你試試看不要用反向代理，直接修改全局DNS試試看呢？

<img width="319" alt="2016-03-14 3 13 10" src="https://cloud.githubusercontent.com/assets/13643173/13737336/610336ba-e9f7-11e5-8b74-c99ba9a077a9.png">

**Comment by klib9739** [comment]
@Coyoter 
昨天我有在手機上刪除HOSTS改用DNS試過
會出現廣告

剛剛又在PC上復現一次
還是會出現廣告...

**Comment by klib9739** [comment]
45.32.72.192 www.bilibili.com
45.32.72.192 www.soku.com
45.32.72.192 www.tudou.com
45.32.72.192 www.xiami.com
45.32.72.192 www.yinyuetai.com
45.32.72.192 www.youku.com

基本上我上面隨便列的這幾個網站
有些甚至連PC版都出現廣告了

![default](https://cloud.githubusercontent.com/assets/6081203/13737544/13e271a0-e9f9-11e5-8960-dc24f7c54c76.png)
![2](https://cloud.githubusercontent.com/assets/6081203/13737543/13e21d2c-e9f9-11e5-9288-91963edf4b55.png)
![3](https://cloud.githubusercontent.com/assets/6081203/13737545/13e744d2-e9f9-11e5-9420-6539c77125d5.png)

**Comment by yanggis** [comment]
你这种情况是什么时候开始出现的呢?

**Comment by klib9739** [comment]
@yanggis 
不確定不過我大概是前天左右發現的
但我從104換到新DNS也才沒幾天

**Comment by yanggis** [comment]
@klib9739，额，这个158，45的DNS服务器，和原来104的unblock用的软件和whitelist是一模一样的，连后台服务器都是一样的。不过有几种筛选的方法：
1.你找别人和你在同样网络环境的其他人的电脑，把他的电脑设置为158的DNS，设置后，访问一下www.youku.com看看是不是同样会出现广告。
2.去其他地方和你当前的网络环境不一样的地方，，比如麦当劳，或者KFC吃饭的时候带laptop去他们那里，用他们的网络，再设置158的DNS看看，会不会这样。
因为这个很奇怪，大家用的同样的DNS，只有个别人才有广告，而且是特定的人，所以很难判断，只能多换几个网络环境和设备才能找到规律。

**Comment by tommyzhaozbh** [comment]
不如打开后台的network看看浏览器怎么get数据的？F12-network然后刷新看看后面的连接记录

**Comment by klib9739** [comment]
@yanggis 其實後端網路和設備我都有交換測試過了但只要一unblock這些網站就出現AD

@tommyzhaozbh 我需要把network裡面的哪些資料給你們?

**Comment by Coyoter** [comment]
快訊：我也出現了！

我直接設定全局DNS的時候，的沒有出現這些廣告的；但是我剛剛試著使用反向連結的方式測試，發現廣告出現了。

<img width="1280" alt="2016-03-14 4 55 52" src="https://cloud.githubusercontent.com/assets/13643173/13739371/c8c7cc30-ea05-11e5-9058-9e86c9b6d9ab.png">

<img width="325" alt="2016-03-14 4 57 13" src="https://cloud.githubusercontent.com/assets/13643173/13739376/d46d484e-ea05-11e5-8b99-d6dd530e1acd.png">

**Comment by Coyoter** [comment]
<img width="943" alt="2016-03-14 4 59 27" src="https://cloud.githubusercontent.com/assets/13643173/13739442/25b87354-ea06-11e5-8547-d53ff332a85e.png">

發現瀏覽器被自動注入了js，生出了好幾個iframe。

例如：

http://un1.winasdaq.com/delivery/yn.do?codeId=10059&amp;cumid=&amp;clid=&amp;w=580&amp;h=88&amp;apGroupId=&amp;apTagId=&amp;cid=x32d9rne47_

這個。

**Comment by klib9739** [comment]
@Coyoter 終於有和我一樣的狀況了@@
不然好像從頭到尾只有我出現 ....

而且我發現她好像不是在一開始載入網頁就注入
就網頁開一下子才慢慢載入是嗎?

**Comment by Coyoter** [comment]
@klib9739 

對的，而且它拖累網頁很大。看來基本可以確定問題是出在DNS上了，只是不知道是哪個環節的問題。

**Comment by yanggis** [comment]
等我检查一下中国代理那边是不是上游的网络植入的广告。

**Comment by Coyoter** [comment]
@yanggis  感謝大大！

**Comment by klib9739** [comment]
@Coyoter @tommyzhaozbh @yanggis @zhuzhuor
感謝大家協助

@yanggis 代理那邊再麻煩您查看了

**Comment by yanggis** [comment]
@klib9739,现在关闭后台一个服务器，你再试试。因为后台后有2个服务器是借别人的，我没有控制权，只能大概猜测是其中一个被IPS植入广告了。

**Comment by Coyoter** [comment]
<img width="1172" alt="2016-03-14 6 01 05" src="https://cloud.githubusercontent.com/assets/13643173/13741011/c160e856-ea0e-11e5-92e5-81df47e343ee.png">

還是會出現，不過並不是每一次都出現。我大約開五次出現一次。

**Comment by klib9739** [comment]
![default](https://cloud.githubusercontent.com/assets/6081203/13741317/9286bcac-ea10-11e5-800d-b15da0e93da8.png)

我也還是會出現

**Comment by yanggis** [comment]
@klib9739 @Coyoter 把另外一个服务器也关掉了，再试一下看看还有广告没有。

**Comment by Coyoter** [comment]
@yanggis 我這邊開了二十次，沒出現廣告了。 
@klib9739 試試看。

**Comment by tommyzhaozbh** [comment]
那个，我好像追查到广告来源了，能不能先把服务器开一下，现在广告没了

**Comment by klib9739** [comment]
@Coyoter 我目前暫時也沒出現AD了
後續再麻煩 @yanggis 和 @tommyzhaozbh 追一下廣告來源了

**Comment by yanggis** [comment]
@tommyzhaozbh，谢谢哈，那个不用测试了，我刚才查了一下，加广告的就是杭州移动的2个服务器，但是我没有控制权去过滤广告，就把这两个服务器关掉暂时不用了。

**Comment by tommyzhaozbh** [comment]
追到来源了
出现广告只会在使用反向代理（也就是修改hosts）的时候出现，直接全局代理是不会有问题的。查看了一下后台的连接，发现有一些链接是来自baidu static的。正常情况下优酷主页不应该有百度的东西出现（优酷不支持百度帐号登录，里面的广告也跟百度推广无关），DNS的主服务器是在国外的，理论上不会有ISP插百度的广告。唯一的可能性就是后面的代理服务器被ISP劫持了。
至于ISP怎么劫持用户，这个我就不多说了。不过据说改DNS会有改善

**Comment by yanggis** [comment]
@tommyzhaozbh，你说的对，就是ISP劫持的，不过那是人家单位的服务器，没法登陆上去改，只能暂时不用这个2个服务器了。谢谢帮忙查找原因。
