### ISSUE TITLE
在DDWRT中的DNSmasq设定了新的IP地址158.69.209.100，但是还是提示版权限制。

### ISSUE THREAD

**Issue by eepocket** [Unblocker/Unblock-Youku#622]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）: DDWRT中的DNS Masq

请具体描述您遇到的问题（例如有问题的视频网址）：iqiyi, mgtv, letv,etc..提示您所在的区域由于版权限制，blablabla...
已经在DDWRT中更新了新的IP地址。
![screen shot 2016-03-13 at 10 44 20 pm](https://cloud.githubusercontent.com/assets/17819233/13733748/25b06fe0-e96d-11e5-934f-efded38ebb1e.png)

您所处的国家或地区：加拿大，魁北克。

**Comment by eepocket** [comment]
不知道和这次的DDos攻击有关没有。

**Comment by yanggis** [comment]
你在你的电脑上ping www.mgtv.com或者ipservice.163.com看返回的IP是不是158.69.209.100，如果不是，就说明你没配置好。
不过看你这个情况应该就是你的路由配置有问题。

**Comment by eepocket** [comment]
果然，这语句应该是address=不应该是server＝。。。谢谢@yanggls

**Comment by eepocket** [comment]
现在ping mgtv返回158.69.209.100了，但是还是提示版权限制。

**Comment by yanggis** [comment]
@eepocket ，现在这会158的服务器有点不稳定，网络高峰期就响应比较慢，你试试45那个服务器。或者你干脆配2个DNS，第一不响应的时候就会自动跳到第二个上。
