### ISSUE TITLE
DNS 現在有幾多组？

### ISSUE THREAD

**Issue by garydevil** [Unblocker/Unblock-Youku#623]
注意：因为最近持续的 DDoS 攻击，Unblock DNS 服务器已经由 @yanggis 迁移至 158.69.209.100，感谢 @yanggis 的工作！之前使用的 192.241.222.103 和 104.236.189.178 会在近期暂停服务。 ??/

**Comment by garydevil** [comment]
DNS IPv4地址：192.241.222.103  這組要改什????

**Comment by yanggis** [comment]
看看这个 https://github.com/Unblocker/Unblock-Youku/issues/618

**Comment by garydevil** [comment]
3q3q
