### ISSUE TITLE
youku电视剧用不了

### ISSUE THREAD

**Issue by Yuanchao-Xu** [Unblocker/Unblock-Youku#624]
人在香港，怎么搞都用不了……重装了chrome……然后无数次的重装了unblock youku……

想看的是珠光宝气的粤语版 
在这里 http://list.youku.com/albumlist/show?id=3891129&ascending=1&page=1

Lite和redirect都不管用……normal的话……就是无限等……一直load不出来……

应该不是本机的问题，因为在extension里面查unblock youku，查出来另外一个红豆的，用这个就可以观看，不过是收费的……

求帮助……还是说现在就unblock youku已经不能用了？

您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:

请具体描述您遇到的问题（例如有问题的视频网址）：

您所处的国家或地区：

**Comment by Migflyway** [comment]
没有问题呀。

**Comment by klib9739** [comment]
剛試播了幾次
有時候正常播放
有時候出現503
有時候出現頁面被多次跳轉

**Comment by Yuanchao-Xu** [comment]
@Migflyway 你是在香港吗？会跟我的ip有关系吗？我在家，在公司，我的电脑，朋友的mac……都用不了……就是一点开视频就直接跳转了……

**Comment by tommyzhaozbh** [comment]
我也在香港，测试了一下啥问题都没有……

**Comment by Yuanchao-Xu** [comment]
@tommyzhaozbh 卸载chrome，然后重装chrome，然后装unblock youku，中间还需要什么其他的步骤吗？

**Comment by tommyzhaozbh** [comment]
没别的步骤了，这样吧，测试一下这个看看结果是不是true。 http://uku.im/check 如果不是true的那证明网络有问题。

**Comment by Yuanchao-Xu** [comment]
@tommyzhaozbh 测试lite是false，normal直接没反应……redirect是true，不过依然看不了珠光宝气…依然跳转…就这个链接…
http://list.youku.com/albumlist/show?id=3891129&ascending=1&page=1

你可以点开看每一集吗？

**Comment by zhuzhuor** [comment]
@Yuanchao-Xu Youku 现在只有 normal 模式管用
你在 chrome://extensions 页面删除一下扩展程序，然后去 https://uku.im/chrome 重新安装一下 Unblock Youku 试试
另外你还安装了别的扩展程序或者代理软件吗，可能会有冲突

另外我试了下我这边可以观看没问题

**Comment by Yuanchao-Xu** [comment]
@zhuzhuor 谢谢，

请问一下，是需要把所有chrome的extension都删掉吗？里面还挺多的。

别的代理之前在国内的时候安装过好几个，不过都卸载了，现在用的psyphon就是一个绿色版的exe，用的时候打开就可以，不用的时候就关了。

我不知道这样会不会导致冲突，如果导致了，我需要如何修改成原来的样子……

谢啦

**Comment by zhuzhuor** [comment]
@Yuanchao-Xu 应该只需要卸载 Unblock Youku 就行了

不过你方便发个 chrome://extensions 页面的截图给我们吗，我们看看会不会你的某个扩展程序和 Unblock Youku 有冲突

**Comment by Yuanchao-Xu** [comment]
@zhuzhuor 我方便发……不过这里好像没法上传截图啊……您有邮箱吗？

**Comment by zhuzhuor** [comment]
@Yuanchao-Xu 直接把截图 drag & drop 到对话框就行
![screen shot 2016-03-17 at 8 35 22 pm](https://cloud.githubusercontent.com/assets/928905/13867776/c8acf438-ec7f-11e5-93df-ee1e0ad7f2de.png)

**Comment by Yuanchao-Xu** [comment]
额。。没注意看……

![_20160318113209](https://cloud.githubusercontent.com/assets/12883455/13867802/b02266d6-ecfd-11e5-8c35-11ff4add409a.png)
![_20160318113231](https://cloud.githubusercontent.com/assets/12883455/13867803/b1e7242a-ecfd-11e5-8580-d3d4cf1b8b61.png)
![_20160318113248](https://cloud.githubusercontent.com/assets/12883455/13867804/b4fefc0a-ecfd-11e5-99a2-03446445df14.png)
![_20160318113302](https://cloud.githubusercontent.com/assets/12883455/13867806/b9ce745e-ecfd-11e5-91ff-48455cb03124.png)

**Comment by zhuzhuor** [comment]
你装了 avast 是不
看看这个 issue https://github.com/Unblocker/Unblock-Youku/issues/611

**Comment by zhuzhuor** [comment]
另外 红豆 也是个代理软件，和 Unblock Youku 会有冲突，你只装一个吧

**Comment by Yuanchao-Xu** [comment]
@zhuzhuor  

已经把avast卸载了，红豆那个是unblock youku不管用之后用来试网的……现在也卸载了。
重装了unblock youku，然后重启浏览器……

选用normal 模式，还是load半天load不出来页面……

而且在setting页面，显示的也是 An extension unblock youku is controlling the setting.

请问还有没有其他方法？可以手动设置DNS吗？

**Comment by zhuzhuor** [comment]
这... 你这可真是奇怪的现象
`An extension unblock youku is controlling the setting.` 这个消息我没看到过，你的操作系统是什么，是 windows 吗

**Comment by Yuanchao-Xu** [comment]
@zhuzhuor 

就在chrome的设置里啊，是win，

![_20160318120319](https://cloud.githubusercontent.com/assets/12883455/13868217/74b44d40-ed01-11e5-96e1-37a95f58686f.png)

**Comment by zhuzhuor** [comment]
DNS 可以先改成 Google DNS https://developers.google.com/speed/public-dns/ 试试管不管用，希望这个能解决，我们也能了解一下问题的根本原因
实在不行可以把 DNS 改成 @yanggis 维护的那个再试试

**Comment by Yuanchao-Xu** [comment]
@zhuzhuor google那个是 8888 和 8844那两个吧？都不行……求@yanggis维护的DNS地址……

**Comment by tommyzhaozbh** [comment]
看 #618 另外你试试打开cmd，ping一下secure.uku.im并截图结果看看

**Comment by Yuanchao-Xu** [comment]
ok了，手动改了DNS之后，158那个地址可以看了……谢谢！！！但是还是不知道为什么unblock youku不能用……

**Comment by tommyzhaozbh** [comment]
看样子应该是你的电脑跟代理服务器的连接有问题，因为我看你连check 的连接都没有任何回应。
