### ISSUE TITLE
依旧返回403 

### ISSUE THREAD

**Issue by pwang2** [Unblocker/Unblock-Youku#625]
curl  http://ipservice.163.com/isFromMainland -x http://127.0.0.1:3128  --verbose

squid 应该是工作正常， node server 也能收到请求， 但会返回403.  求助！ 

* Connected to 127.0.0.1 (127.0.0.1) port 3128 (#0)
> GET http://ipservice.163.com/isFromMainland HTTP/1.1
> User-Agent: curl/7.38.0
> Host: ipservice.163.com
> Accept: */*
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 403 Forbidden
< Cache-Control: public, max-age=14400

**Comment by tommyzhaozbh** [comment]
你用的是3128端口?我记得如果按照教程里面给的方法是禁用除22和8888以外的端口的。

**Comment by pwang2** [comment]
@tommyzhaozbh 3128 是squid的默认端口。。我参照是这个[blogpost](http://blog.changecong.com/2013/10/raspberry-pi-shumeipai-tupozhongguoipxianzhi-squid-unblock-youku/).

**Comment by zhuzhuor** [comment]
@pwang2 这么高级，装了 Raspbmc 是能当电视用？

**Comment by yanggis** [comment]
Raspbmc看国内视频意义不大，没什么视频源，也没有直播源，偶尔有一两个还卡的厉害，可能过几天这个link又没了，就又不能看了。Raspbmc国外用的比较多，可以直接看网盘里的电视剧和电影比较方便。
