### ISSUE TITLE
PAC 文件不能处理好带有 :80 端口号的 URL

### ISSUE THREAD

**Issue by zhuzhuor** [Unblocker/Unblock-Youku#626]
多谢 @yanggis 在 #620 的反馈，发现 PAC 文件有个 bug
如果 URL 里面有 `:80` 这样的端口号信息，我们的 PAC 并不能正确地解析

```
http://115.182.200.53:80/heartBeat?arealevel1=CN&arealevel2=10&arealevel3=127&expect=38&groupId=cctv1HD_1800ver_00_101.3m3u8_12272000&ispId=2&module=cde&neighbors=0&peerId=c7fd2b479838c926b344cbdceb5b79d00498a5ab5e2193c65cdbbe68d3b25a81&pos=1458232018&query=1&rtmfpId=115.182.200.51:8125&tid=1&ver=liv.CDE-1.0.19

http://115.182.200.53:80/cde?arealevel1=CN&arealevel2=10&arealevel3=127&ckey=cctv1HD_1800ver_00_101.3m3u8_12272000&expect=38&format=1&inip=192.168.1.165&ispId=2&neighbors=0&op=3&pid=33-a02a74440ef0ea11b8c9a0ce56eadb0c-1443-1443&pos=1458232018&termid=2&ver=liv.CDE-1.0.19
```

**Comment by mc16888** [comment]
@zhuzhuor @yanggis 弄成這樣不知道行不行
PAC
`"115.182.200.53":[/^(?:\:80)?\//i],`
Proxy whitelist
`^http:\/\/115\.182\.200\.53(\:80)?\/.*$`

**Comment by zhuzhuor** [comment]
@mc16888 估计可以，但是转发模式不支持 regex
或者就先不管转发模式了，给普通模式和 PAC 弄好

**Comment by zhuzhuor** [comment]
更新了 PAC 文件 https://github.com/Unblocker/Unblock-Youku/commit/7e986124298da5b2198d2299c0231f52362f4d20
理论上应该修复了这个问题，但是 Chrome 里没法测试
如果直接用 PAC 有问题的话，请再来会汇报 @yanggis @mc16888 ，谢谢！
