### ISSUE TITLE
自动爬取网上的代理服务器的脚本，供测试使用

### ISSUE THREAD

**Issue by zhuzhuor** [Unblocker/Unblock-Youku#627]
我们代理服务器都有白名单做安全控制，不太方便给网上的朋友们做开发调试使用
但网上开放的代理服务器资源很多，例如

* http://www.proxynova.com/proxy-server-list/country-cn/
* http://gatherproxy.com/proxylist/country/?c=China
* http://www.proxylisty.com/country/China-ip-list

不知道有没有人有兴趣写个脚本 aggregate 这些开放的服务器？
大致的步骤可以搞成：

1. 爬取这些网站，获取服务器类型、IP 和 端口号
2. 用 `http://ipservice.163.com/isFromMainland` 测试这些服务器
3. 然后生成个实时的可用的代理服务器列表

进一步，可以做的更高级一点

4. 程序本身就可以启动一个本地的代理服务器，后台通过这些开放的代理服务器再做一层代理
5. 定时检查各个服务器状态，如果有个服务器不能用了就在弄一个新的来，一直维持个固定数量的可用服务器的 pool

这个稍微有点技术难度，也非常有用。回头可以在 Unblocker 下面专门开个 repo 给这个程序
不知道有人想 take on 这个 project 吗

**Comment by fiht** [comment]
Hello
I think I can take on this project
因为之前在学习一些网络安全方面的知识 所以曾写过一个脚本来抓取代理IP，觉得您的idea很有意思，期待与您进一步交流
但是由于电脑故障。又没有及时提交代码.
只剩了个这了.....  https://github.com/fiht/ProxyScaner
应该和您的意思差不多
期待进一步与您交流！

**Comment by zhuzhuor** [comment]
@fiht 多谢！欢迎帮忙！
我专门新建了个 repo 给这个 project https://github.com/Unblocker/dev-proxy-finder
你可以先从小部分做起，提交到那个 repo，我帮你做做 code review 什么的 :+1:

**Comment by zhuzhuor** [comment]
有什么技术上的难题也可以 post 出来，我也可能帮忙想想什么的

**Comment by zhuzhuor** [comment]
感谢 @JeanCui 的帮助，第一版已经在 https://github.com/Unblocker/dev-proxy-finder 了

这个 issue 就关闭了，之后有更新和改进就在新的 repo 吧
