### ISSUE TITLE
Dns － 192.241.222.103 失效

### ISSUE THREAD

**Issue by joyocho** [Unblocker/Unblock-Youku#630]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:

请具体描述您遇到的问题（例如有问题的视频网址）：

您所处的国家或地区：
日本

Dns
－ 192.241.222.103

该Dns已经正常使用一年了，最近突然不行了。
求Help，非常感谢！辛苦各位大神了！

**Comment by Migflyway** [comment]
#618

**Comment by klib9739** [comment]
呃
會來這裡po文居然不會稍微往下爬一下文

**Comment by joyocho** [comment]
@Migflyway 
@klib9739 
对不起。。。我应该爬一下issue list的，太感谢了！ >.<
