### ISSUE TITLE
转发模式看腾讯视频提示节目暂时不提供观看

### ISSUE THREAD

**Issue by fishforce** [Unblocker/Unblock-Youku#631]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:Unblock-Youku

请具体描述您遇到的问题（例如有问题的视频网址）：腾讯视频

您所处的国家或地区：日本

校园网使用局域网代理服务器，走普通模式网络就连接不上了，转发模式浏览网页正常但是看腾讯视频提示节目暂时不提供观看

希望能够得到帮助 谢谢

**Comment by zhuzhuor** [comment]
转发模式因为技术上的原因不能支持很多网站
你可以试试 @yanggis 维护的 DNS `158.69.209.100`

**Comment by fishforce** [comment]
直接修改本地的DNS吗？好像没什么效果

**Comment by tommyzhaozbh** [comment]
这个没有太好的办法，我也试过这样的问题。如果局域网的防火墙规则不允许使用除规定代理以外的其他代理服务器，你用哪种方法都不起作用，除了转发模式。我也试过直接指定hosts，但同样连网都上不了。所以尽量不要在学校机房使用。

**Comment by zhuzhuor** [comment]
@fishforce 改了 DNS 理论上应该会起效，你可以多刷新一下网页试试
要是还是不行，@yanggis 有什么可以 command line 测试 DNS 生效与否的命令范例吗

**Comment by yanggis** [comment]
@zhuzhuor 直接ping hot.vrs.sohu.com看返回的IP是多少，如果是158或者45的服务器，应该就是生效了。但是，校园网，如果禁用代理的话，DNS生效也没什么用，因为学校网络出口不允许使用代理，DNS服务器没法送到他的设备发来的解锁请求。

**Comment by zhuzhuor** [comment]
@yanggis 校园网应该是给所有人都设置了全局代理，所以才会和 Chrome Extension 冲突
用 DNS 的话，HTTP 请求就会发到我们自己的服务器了吧，通过校园网的代理应该也没问题

**Comment by zhuzhuor** [comment]
@yanggis 还是说，校园网的代理服务器也得用你的 DNS 才管用？

**Comment by yanggis** [comment]
@zhuzhuor 校园网很多地方是不允许用代理的，用DNS的话，其实也是代理的一种，也是会被学校的防火墙ban掉的，现在发现很多学校都会禁用代理，http请求会被防火墙拦截，就不会发送到我们自己的服务器，所以就没办法了。
