### ISSUE TITLE
bilibili iOS端连接失败问题

### ISSUE THREAD

**Issue by tommyzhaozbh** [Unblocker/Unblock-Youku#632]
有用户反馈说在iPad上使用pac测试代理正常，但在4.14.1的版本会出现“解析失败，切换失败”的提示，在4.8则会提示“分析视频地址失败”。因为我手上没有ios，有人测试到同样问题么？

**Comment by flamingtop** [comment]
有专门到国内的服务 http://jump.im/47 回国可以往外翻。

**Comment by Aiee** [comment]
用的手机b站客户端，版本4.16，配置了新的dns，同样pac测试代理正常但出现了 解析失败切换失败

**Comment by yanggis** [comment]
@Aiee bilibili在新版本的客户端上新加了验证，所以如果你还没升级bilibili客户端的最新版，最好不要升级。新版本的验证问题我正在想办法解决。应该最近一两天搞定。

**Comment by Aiee** [comment]
@yanggis 不好意思忘记说了是ios的客户端，4.16已经是最新版了

**Comment by yanggis** [comment]
@Aiee 是不是因为你那边访问158的服务器比较慢，导致解锁结果还没返回就超时断掉了啊？你有没有试过45.32.72.192这个服务器啊，或者45.63.69.42？bilibili新版本的这个验证问题我已经解决了。现在连应该没问题了。进入主界面有一个验证，加载有点慢，等一下就会加载成功。

**Comment by Aiee** [comment]
@yanggis 刚刚测试，成功了！原本用的两个dns，158的放在前面45的在后面，刚把158的删掉只留着45就加载成功了，谢谢！

**Comment by yanggis** [comment]
@Aiee 你自己要ping一下这两个服务器，哪个在你那边反应比较快，就把哪个放前面。

**Comment by Aiee** [comment]
@yanggis 好的，再次感谢～

**Comment by hoho97** [comment]
我在HK用158DNS+PAC也是看不了
後面改用BILIBILI純白倒是能看，原因不明

**Comment by yanggis** [comment]
@hoho97 45的服务器你试了没？

**Comment by hoho97** [comment]
@yanggis 手邊沒機子，明天回到宿舍再試

**Comment by hoho97** [comment]
@yanggis 換45就能看了
不過上一般網似乎有變比較慢，有解嗎？

**Comment by yanggis** [comment]
@hoho97 这个对于iOS设备尤其是IPhone和IPad基本无解，android你可以在goolge play里安装chinatunnel来实现。因为你用的是远程的DNS，它给你提供的服务器一般都是服务器所在地访问最快的，而不是那你那个地方(比如，香港，台湾)的（解锁链接除外），所以不会像本地DNS那样一直都是给你提供本地访问最快的服务器。chinatunnel它事实上就是只拦截了需要解锁的链接，对于其他链接还是用的本地DNS，所以基本速度没有影响。

**Comment by enerai** [comment]
@yanggis 有同样的情况，地点香港，用158的不能看bilibili，用45的就可以看。158是因为服务器上的程序没有更新吗？

**Comment by yanggis** [comment]
@enerai 158服务器不是不能看，是解锁比较慢，就是在点播放播放之后，获取视频链接那个地方，非常慢，有时候可能要等一分钟才能请求到链接。大多数情况下是你没等那么久，就以为是解锁不了，就关掉了。这个是158服务器和国内通信的问题。三台DNS服务器配置是完全一样的。

**Comment by enerai** [comment]
@yanggis 这样子啊。我在使用surge来实现临时的DNS修改。之前45和158都填写在surge里面，bilibili客户端直接返回“找不到视频”，现在surge设置里面只剩下45的服务器就能正常看了

**Comment by yanggis** [comment]
因为你的surge设置的超时时间太短了，158的服务器可能要1分钟才会给你返回结果，但是你的surge在30秒的时候就认为是服务器错误把链接关闭了，所以就认为是请求不到数据了。

**Comment by yanggis** [comment]
@enerai 如果158看bilibili不行，就把你的IPad或者IPhone重启一下，清空一下DNS缓存。

**Comment by zhuzhuor** [comment]
@yanggis 是因为 iPad 上的 b 站客户端有新的 URL 了？这个加在 PAC 上管用吗

**Comment by yanggis** [comment]
@zhuzhuor 没有新的URL，是原来的app.bilibili.com变成Https加密验证了。

**Comment by mc16888** [comment]
@zhuzhuor @yanggis iOS的客戶端播放的時候,會用TCP的方式連以下三個IP其中一個. pac 沒辦法代理.

107.182.165.170
192.161.173.58
103.3.61.22

Surge App 的 debug log.
![surge](https://cloud.githubusercontent.com/assets/6530873/14457659/9e7857f2-00de-11e6-967d-48490b28fbea.PNG)

**Comment by yanggis** [comment]
@mc16888 这三个link是负责数据传输的，不需要针对他们进行解锁。

**Comment by yanggis** [comment]
@mc16888 你现在用DNS不能解锁看bilibili视频吗？

**Comment by mc16888** [comment]
@yanggis 用DNS 沒問題. 

我剛剛做了一下packet capture, 上面那三個IP應該是這個URL
`http://interface.bilibili.com/playurl?platform=android&_device=iphone&_hwid=xxxxxxxxxx`
不知道為甚麼 bilibili iOS 客戶端 request 的時候會變成 TCP connection. 而不是 http get.

**Comment by yanggis** [comment]
@mc16888 那估计要更新一下P A C文件才行。

**Comment by Besezta** [comment]
@yanggis 所以PAC還是有機會對Bilibili湊效的？

因為我用Dns的時候，無論是158還是45，土豆都是卡得很嚴重，要不直接看不了，但Pac倒是正常

換B站了，Pac無法用，dns倒是跑得挺順暢，所以我只能兩邊換來換去

**Comment by yanggis** [comment]
@Besezta PAC我不太清楚，可以问问zhuZhuor。你说的土豆网播放很卡能不能给我提供一个视频，我测试一下，然后调整一下后台服务器应该就好了。

**Comment by Besezta** [comment]
@yanggis 隨便一個有版權的新番情況都一樣，例如銀魂。主要是土豆客戶端分享沒連結選項...

**Comment by yanggis** [comment]
@Besezta 能不能用电脑打开，找一个用DNS看土豆网视频比较卡的链接啊？我在喜马拉雅山出差，没有Android设备测试，只有电脑。

**Comment by Besezta** [comment]
@yanggis DNS問題突然好了哈哈，iOS客戶端和電腦也是，畢竟卡了好幾天的當時我沒想起用電腦試試，所以也不好說具體是哪方面有問題，辛苦你了，如果再有問題時再向你報告。

**Comment by zhuzhuor** [comment]
@Besezta @yanggis PAC 不能用可能是没有加新的那个 HTTPS 的 URL？是哪一个来着？

**Comment by yanggis** [comment]
@zhuzhuor 应该是http://app. bilibili. com or https://app. bilibili. com

**Comment by Besezta** [comment]
@zhuzhuor 我記得有人說過bilibili本來就無法用pac，所以我一直是用dns看的

**Comment by zhuzhuor** [comment]
@yanggis @Besezta Anyways 我把那个 b 站的新链接加到 PAC 里了，说不定以后能用到
另外我试了 b 站上的几个视频，网页版貌似没什么问题。如果之后发现有问题，欢迎再来反馈
