### ISSUE TITLE
望能支持ViuTV、Viu OTT视频网站

### ISSUE THREAD

**Issue by Kara-ism** [Unblocker/Unblock-Youku#633]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）:Chrome 插件 3.0.1.4

请具体描述您遇到的问题（例如有问题的视频网址）：

望能支持ViuTV、Viu OTT视频网站，
这两个网站是HK某电讯旗下的视频网站，仅限香港用户，可我人在海外阿……谢谢！ :laughing: 

您所处的国家或地区：海外

**Comment by tommyzhaozbh** [comment]
ViuTV的东西，除了一些自家的东西以外，日韩剧和综艺有很多在大陆的视频网站都有。除非你是有强迫症非要听粤语不可的，或者一些东西只有那上面才有的，其他的直接上大陆的视频网站即可。如果说要支持的话，恐怕要视乎总的需求人数了。毕竟如果需求人数不多的话，开设这个服务不是很划算。
（PS：如果是看韩国综艺的话那就算了，字幕的质素跟国内视频网站一个天一个地……）

**Comment by Kara-ism** [comment]
@tommyzhaozbh 

因为光电某局把戏剧剪的不像话（如最近的後裔…），
所以想上来问看看有没有支持这两个网站的可能性…

**Comment by zhuzhuor** [comment]
我们现在的代理服务器都在中国大陆，仅从技术上考虑也不行
