### ISSUE TITLE
Chrome插件看不了土豆

### ISSUE THREAD

**Issue by Besezta** [Unblocker/Unblock-Youku#634]
只能進首頁
http://www.tudou.com/

別的都進不了，例如銀魂
http://www.tudou.com/albumplay/92J2xqpSxWY.html

Chrome顯示
```
www.tudou.com 頁面無法正常運作

www.tudou.com 未傳送任何資料。
ERR_EMPTY_RESPONSE
```

關了就能進了

不是新番也不行，桂林神街访
http://www.tudou.com/listplay/aaAFZ7bJihc/bMaepgxJeeE/

**Comment by tommyzhaozbh** [comment]
那证明插件工作不正常，其他视频网站是不是也是这样？

**Comment by Besezta** [comment]
@tommyzhaozbh Bilibili正常

**Comment by Besezta** [comment]
位置香港、電訊商HKBN、Chrome版本50.0.2661.75 m、插件版本3.0.1.4

**Comment by tommyzhaozbh** [comment]
那是因为插件需要借用993端口进行代理，这跟avast的邮件监控有冲突

**Comment by zhuzhuor** [comment]
Avast 的问题可以看这个 https://github.com/Unblocker/Unblock-Youku/issues/611
你可以关闭邮件监控试试
