### ISSUE TITLE
盒子 腾讯视频 nba直播 DNS无效

### ISSUE THREAD

**Issue by chenluke** [Unblocker/Unblock-Youku#635]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）: DNS（158.69.209.100和45开头的两个都试过）

请具体描述您遇到的问题（例如有问题的视频网址）：盒子版腾讯视频TV版，无法观看NBA直播

您所处的国家或地区：美国

我用路由器设置的DNS，用电脑可以看，但是盒子怎么都不行，求解。

**Comment by yanggis** [comment]
@chenluke 你用的是企鹅云试听的最新版吗?NBA直播在电视盒子上被停掉了，因为腾讯没有电视直播的版权，只有网络视频直播的版权，仅限于手机，平板电脑和网页版直播。

**Comment by chenluke** [comment]
@yanggis 原来是这样。。。请问如果想在电视上看有啥办法吗？

**Comment by chenluke** [comment]
@yanggis 而且我发现貌似不是版权的问题，网上有人说现在的最新版又能在盒子上看了。我试了1.71.1003和1.7.0.1030版的云视听企鹅，错误是：您所在地区无法观看该节目(104,5)

**Comment by yanggis** [comment]
@chenluke 那企鹅云试听的其他节目可以看吗？比如电视剧，动漫之类的可以看吗？

**Comment by chenluke** [comment]
@yanggis 缓冲很慢，勉强可以播放，但是没有所在地区无法观看的错误信息。

**Comment by yanggis** [comment]
@chenluke 缓冲比较慢的时候退出播放，然后再点播放，这样后台会自动给你换服务器，就会跳到比较快的服务器上了。
