### ISSUE TITLE
可以在路由器上面直接设置dns吗?

### ISSUE THREAD

**Issue by Dummykid** [Unblocker/Unblock-Youku#639]
家里有2个路由器,一个主路由器A拿来上网,还有个路由器B我想能不能单独设置成给机顶盒用,这样我可以把家里3个机顶盒直接连到路由器B. 所以我想知道 如果我在路由器B里面改DNS的话,是不是也可以看国内的片子? 你们一般都是用哪2个DNS啊? 还是158.69.209.100 和45.32.72.192, 45.63.69.42么?

**Comment by tommyzhaozbh** [comment]
当然可以，地址就是上面的3个，哪个速度快就用哪个。
