### ISSUE TITLE
使用青云云主机搭建自己的服务器

### ISSUE THREAD

**Issue by ruijianw** [Unblocker/Unblock-Youku#640]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）: Chrome插件

请具体描述您遇到的问题（例如有问题的视频网址）：

你好，按照这个[教程](https://github.com/Unblocker/Unblock-Youku/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89-Unblock-Youku-%E6%89%A9%E5%B1%95%E7%A8%8B%E5%BA%8F%E6%89%80%E4%BD%BF%E7%94%A8%E7%9A%84%E4%BB%A3%E7%90%86%E6%9C%8D%E5%8A%A1%E5%99%A8)在青云的云主机上搭建了一个服务器，squid的服务已经是running状态
![image](https://cloud.githubusercontent.com/assets/3395519/14769568/84493cee-0a29-11e6-9c1c-3325e7be970a.png)
服务器的防火墙设置如下
![image](https://cloud.githubusercontent.com/assets/3395519/14769667/d44754cc-0a2b-11e6-8344-a00044cfb269.png)
但是在chrome插件中测试服务器的时候还是不行
![image](https://cloud.githubusercontent.com/assets/3395519/14769682/485b2212-0a2c-11e6-9278-aa7ef61e7034.png)
感觉是防火墙设置和插件中的端口设置有问题？

插件的端口设置上尝试了一下组合，都不行：
``http 443``
``http 993``
``https 443``
``https 993``
443和993都曾在防火墙中打开过。

不知能否给一些可以尝试debug的意见，谢谢！

您所处的国家或地区：美国东部

**Comment by zhuzhuor** [comment]
端口号用 8888？

**Comment by ruijianw** [comment]
多谢，HTTP+8888端口可行！

**Comment by zhuzhuor** [comment]
不客气，能用就好

有时间的话欢迎帮忙写个青云的配置教程？我可以挪到 wiki 上去
之后方便大家自己选择云主机服务商

**Comment by ruijianw** [comment]
没问题，正好可以作为我个人博客第一篇文章:)，直接把markdown原文发出来，省了排版的麻烦

**Comment by ruijianw** [comment]
@zhuzhuor 青云的教程已经写好，你可以建一个wiki的草稿页，我来更新上去，自己blog的链接在这里：http://ruijianw.github.io/2016/04/28/%E5%9C%A8%E9%9D%92%E4%BA%91%E4%B8%8A%E6%90%AD%E5%BB%BA%E8%87%AA%E5%B7%B1%E7%9A%84unblock-youku%E6%9C%8D%E5%8A%A1%E5%99%A8/

**Comment by zhuzhuor** [comment]
@ruijianw wow 教程写的不错！青云看起来挺好的呀，还可以用美金结算！

我刚刚弄了 Unblock Youku 的论坛 https://bbs.uku.im，你可以直接贴到那里去
可以直接贴 Markdown。之后有什么需要更新的，你也可以直接修改你的帖子 :D 

BTW, blog 搭建的不错！

**Comment by ruijianw** [comment]
@zhuzhuor 我受到伤害了。。。。把图重新上传了以后，结果告诉我。。。
![image](https://cloud.githubusercontent.com/assets/3395519/14919446/e62a14d0-0df6-11e6-8628-5f6d352ee0bb.png)

**Comment by zhuzhuor** [comment]
这.....
估计是什么 antispam 的设置，我去找找

**Comment by zhuzhuor** [comment]
刚刚设置了一下，你再试一下跟我说说效果

> ![screen shot 2016-04-29 at 11 08 41 pm](https://cloud.githubusercontent.com/assets/928905/14934234/5bf7a0de-0e5f-11e6-9bb7-0f8687a43163.png)

另外你在 bbs 上的 draft 还是自动保存了的，不用重新写吧

**Comment by ruijianw** [comment]
@zhuzhuor 发出去了，的确是有保存草稿功能，不错，话说这个论坛是用了什么框架么，还是完全自己写的？

**Comment by zhuzhuor** [comment]
@ruijianw 用了 Discourse，作者是 stackoverflow 的 cofounder
