### ISSUE TITLE
PAC文件对iOS下的「爱奇艺PPS」无效

### ISSUE THREAD

**Issue by ruijianw** [Unblocker/Unblock-Youku#641]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）
===
PAC
请具体描述您遇到的问题（例如有问题的视频网址）：
===
**测试连接** ``http://www.iqiyi.com/v_19rrlpgmt0.html#``
**具体现象**
* iOS下用Safari访问，一切正常，用「爱奇艺PPS」就会显示版权问题，怀疑是iOS app走的不一样的地址
* Chrome下用unblock优酷的插件也一切正常

您所处的国家或地区：
===
美东

**Comment by ruijianw** [comment]
播放了一个能看的视频，抓包的链接如下
http://akm591.inter.iqiyi.com/videos/v0/20150401/c8/11/9f02fe65c48daa8bad057c8942188e72.f4v?key=0239fe684bd55159befcbbd7a3777dd94&src=iqiyi.com&qd_tvid=236532400&qd_vipres=0&qd_index=1&qd_aid=200523301&qd_stert=0&qd_scc=3feda6297832d58a4d49d98bc4cda93f&qd_sc=bfe500544512bd919869440c8ffc983a&qd_src=03032001020000000000&qd_ip=6c27c374&qd_uid=156846296&qd_tm=1461562234622&qd_vip=1&qyid=EA8D1320-CFC0-4502-8A08-AA12AA4C7BC9&qypid=2022&la=OVERSEA|US&li=akm_oversea_hash&lsp=0&lc=0&uuid=6c27c374-571dab7b-5a

**Comment by tommyzhaozbh** [comment]
你要抓一个不能看的视频才行……把所有抓包记录都发来

**Comment by ruijianw** [comment]
这个是昨晚用wifi sharing抓的包，在播放不能用的链接的时候，不知道里面有没有有用的信息。
https://www.dropbox.com/s/8j8z73lmga9gm9z/catpure.pcapng?dl=0

**Comment by tommyzhaozbh** [comment]
抓到了，是这个，pac没有这个地址，回头加一个
![qq](https://cloud.githubusercontent.com/assets/8757104/14807088/872f5988-0bab-11e6-8ed4-1bf497693f7c.png)

**Comment by zhuzhuor** [comment]
@ruijianw 多谢你的反馈！
@tommyzhaozbh 超级感谢你这细致的工作！

**Comment by ruijianw** [comment]
加这个正则是对的，但是似乎还是看不了，再次抓包就没发现这个get请求了，但是有一些请求是在正则列表中没有出现的，不知道背后的工作原理是对每一个视频网站的请求做转发还是只针对地理位置验证的请求做转发？

**Comment by tommyzhaozbh** [comment]
当然是只对有检测地理位置的链接做代理。如果还是不行的话那可能还有链接做了检测

**Comment by mc16888** [comment]
@ruijianw @tommyzhaozbh @zhuzhuor 這個問題和 bilibili 一樣,要用DNS才可以.
