### ISSUE TITLE
28/04/2016 Bilibili无法正常观看新番

### ISSUE THREAD

**Issue by IMSOKAWAII** [Unblocker/Unblock-Youku#644]
您好目前在pad上使用的PAC如下 http://yo.uku.im/proxy.pac
今天更新B站app后新番就无法观看了。。
卸载B站从新安装4.1.1旧版本后,尝试使用新地址http://pac.uku.im/pac.pac与旧地址http://yo.uku.im/proxy.pac也均无效。
请问这个问题该如何解决呢？

**Comment by IMSOKAWAII** [comment]
明明几小时前还可以正常观看的说。。

**Comment by IMSOKAWAII** [comment]
连接PC用itools安装4.1.1版本的BilibiliI IOS文件，安装结束后pad内自动更新为4.18.0最新版了。。这是什么情况

**Comment by IMSOKAWAII** [comment]
http://uku.im./check检测结果为true

**Comment by IMSOKAWAII** [comment]
问题已解决，将DNS修改为45.63.69.42即可。。
原因不明啊 之前根本不需要改DNS的
观影速度变卡了很多 (抽泣

**Comment by zhuzhuor** [comment]
估计和这个问题一样吧  https://github.com/Unblocker/Unblock-Youku/issues/632
另外还有个 DNS 158.69.209.100，可以都试试，地区不同可能连接速度也有差异

回头等 @yanggis 有空了写个 DNS 的总结和设置教程吧
