### ISSUE TITLE
whitelist 無法更新

### ISSUE THREAD

**Issue by sdirichard** [Unblocker/Unblock-Youku#645]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）: 我是直接用 VST

请具体描述您遇到的问题（例如有问题的视频网址）：
機上盒用 DNS ：192.241.222.103  
（需要改成 ： 45 開頭那個嗎 ？）

您所处的国家或地区：Taiwan

**Comment by tommyzhaozbh** [comment]
192的那个早就停用了，换一个地址吧

**Comment by zhuzhuor** [comment]
158.69.209.100
45.32.72.192
45.63.69.42
你可以试试这三个 IP，哪个在你那里速度快就用哪个吧
