### ISSUE TITLE
新版本的unblock youku 用Normal Mode 访问bilibili.com 的视频明显变慢

### ISSUE THREAD

**Issue by charleyzhuyi** [Unblocker/Unblock-Youku#648]
您所使用的软件或服务（例如 Chrome 插件、PAC/DNS 服务等）: Chrome Unblock YouKu 插件

请具体描述您遇到的问题（例如有问题的视频网址）：

特别比较了两个版本的unblock youku 访问bilibili.com 的视频。 

旧版本(Unblock Youku v3.0.1.5) Normal Mode 和Lite Mode 访问bilibili.com 的视频都很快， 但是如果用新版本（v3.1.0.0)的 Normal Mode 看bilibili 的视频就会变得非常卡顿，改成Lite Mode 就变得很流畅了。

是不是新版本normal mode做了些改动导致bilibili使用了国内服务器而不是境外镜像服务器作为源？ 不确定这一定是个bug，至少有lite mode用起来很流畅

您所处的国家或地区：美国，加州

**Comment by zhuzhuor** [comment]
如果能观看的话，说明都是国内的源。可能不同的 b 站国内服务器在你那边速度有很大的差异
如果用 lite 模式可以正常工作的话那就先用一段时间，我们之后想想怎么处理
多谢反馈！
